### PR TITLE
Updated soil NOx scheme from Yi Wang et al. (2021) as an option

### PR DESCRIPTION
**Pull request by msulprizio**
### Name and Institution (Required)

Name: Melissa Sulprizio
Institution: Harvard

### Describe the update

This is the corresponding pull request for https://github.com/geoschem/geos-chem/issues/1288 and should be merged alongside https://github.com/geoschem/HEMCO/pull/287.

Yi Wang (@ywang37) updated the soil NOx algorithm in HEMCO to utilize soil temperature as described in Yi Wang et al. (ERL, 2021). Those updates require the addition of a new meteorology field, TSOIL1, for the soil temperature in layer 1. This field has been added to State_Met. 

A new option `UseSoilTemperature` has been added to the SoilNOx extension section in HEMCO_Config.rc. It is set to false by default. This option needs to be evaluated further before it can be made the default in the soil NOx extension. Additionally, the full archive of TSOIL1 fields needs to be processed and made available for GEOS-Chem. This updated algorithm will also require generating a new set of offline soil NOx emissions at native GEOS-FP and MERRA-2 resolutions.

### Expected changes

This is a zero-difference change with respect to the full-chemistry benchmark because this updated scheme is off by default. To view the expected changes when the algorithm is used, see [these plots](https://github.com/geoschem/geos-chem/issues/1288#issuecomment-1254031284) in the original Github issue.

### Reference(s)

- Wang, Y., C. Ge, L. Castro Garcia, G. D. Jenerette, P. Y. Oikawa, J. Wang, [Improved modelling of soil NOx emissions in a high temperature agricultural region: role of background emissions on NO2 trend over the US](https://iopscience.iop.org/article/10.1088/1748-9326/ac16a3), Environmental Research Letter, 16, 084061, 2021.

### Related Github Issue

- https://github.com/geoschem/geos-chem/issues/1288
- https://github.com/geoschem/HEMCO/pull/287

### CODE REVIEW

**Comment by msulprizio** [comment]
Integration tests are now running

**Comment by msulprizio** [comment]
All GCClassic and GCHP integration tests now pass for this PR in combination with https://github.com/geoschem/HEMCO/pull/287.

**Comment by msulprizio** [comment]
I have also confirmed that this is a zero difference update with respect to the full-chemistry benchmark simulation.

**Review by yantosca — APPROVED** [review]
Looks good to merge!  Thanks @msulprizio!

**Comment by yantosca** [comment]
After merging on top of 14.5.0-alpha.10, All GEOS-Chem Classic integration tests passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

CodeDir   : b577abe GEOS-Chem submod update: Merge PR #2452 (Reorder photo rxns for PNs, ANs)
GEOS-Chem : 94cda6a83 Hotfix: Add .zenodo.json file for GEOS-Chem science codebase
HEMCO     : 88b9e60 Hotfix: Add .zenodo.json file for HEMCO
Cloud-J   : 6bf4a36 Merge pull request #26 from geoschem/feature/define_max_rather_than_exact_num_jvalues
HETP      : 2a99b24 Merge pull request #2 from geoschem/bugfix/initialize_local_variables

Using 24 OpenMP threads
Number of execution tests: 30

Submitted as SLURM job: 46152832
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
After merging on top of 14.5.0-alpha.10, all GCHP integration tests passed:
```console
==============================================================================
GCHP: Execution Test Results

CodeDir       : cea4c24 Cloud-J submod update: Merge PR #26 (Define max J-values rather than exact)
MAPL          : 231d53c Merge pull request #36 from geoschem/feature/improve_hflux_regridding
GMAO_Shared   : 4ddb3ec Merge pull request #2 from geoschem/feature/mapl-upgrade
ESMA_cmake    : ad5deba Added ecbuild as a submodule of ESMA_cmake
gFTL-shared   : 4b82492 Merge branch 'upstream_v1.5.0' into feature/v1.5.0
FMS           : 259759d Merge pull request #3 from geoschem/feature/update_gmao_libs
FVdycoreCubed : af42462 Merge PR #8 (Add PLEadv diagnostic for offline advection in GCHP)
geos-chem     : 94cda6a83 Hotfix: Add .zenodo.json file for GEOS-Chem science codebase
HEMCO         : 88b9e60 Hotfix: Add .zenodo.json file for HEMCO
yaFyaml       : 19afe50 Merge branch 'upstream_v1.0.4' into feature/v1.0.4
pFlogger      : 2c4b724 Merge branch 'upstream_v1.9.1' into feature/v1.9.1
Cloud-J       : 6bf4a36 Merge pull request #26 from geoschem/feature/define_max_rather_than_exact_num_jvalues
HETP          : 2a99b24 Merge pull request #2 from geoschem/bugfix/initialize_local_variables

Number of execution tests: 12

Submitted as SLURM job: 46152940
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

CodeDir   : 5e00d7e GEOS-Chem update: Merge PR #2457 (Update Is_Photolysis tags)
GEOS-Chem : 084a8cf8d Merge PR #2462 (Bug fix: ALK6 in HEMCO_Config.rc should be ALK7)
HEMCO     : c6a9d46 Merge PR #287 (Updated Y. Wang soil NOx scheme as an option)
Cloud-J   : 6bf4a36 Merge pull request #26 from geoschem/feature/define_max_rather_than_exact_num_jvalues
HETP      : 2a99b24 Merge pull request #2 from geoschem/bugfix/initialize_local_variables

Using 24 OpenMP threads
Number of execution tests: 30

Submitted as SLURM job: 46770790
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
All GCHP integration tests also passed:
```console
==============================================================================
GCHP: Execution Test Results

CodeDir       : 984823f GEOS-Chem update: Merge PR #2457 (Update Is_Photolysis tags)
MAPL          : 231d53c Merge pull request #36 from geoschem/feature/improve_hflux_regridding
GMAO_Shared   : 4ddb3ec Merge pull request #2 from geoschem/feature/mapl-upgrade
ESMA_cmake    : ad5deba Added ecbuild as a submodule of ESMA_cmake
gFTL-shared   : 4b82492 Merge branch 'upstream_v1.5.0' into feature/v1.5.0
FMS           : 259759d Merge pull request #3 from geoschem/feature/update_gmao_libs
FVdycoreCubed : af42462 Merge PR #8 (Add PLEadv diagnostic for offline advection in GCHP)
geos-chem     : 084a8cf8d Merge PR #2462 (Bug fix: ALK6 in HEMCO_Config.rc should be ALK7)
HEMCO         : c6a9d46 Merge PR #287 (Updated Y. Wang soil NOx scheme as an option)
yaFyaml       : 19afe50 Merge branch 'upstream_v1.0.4' into feature/v1.0.4
pFlogger      : 2c4b724 Merge branch 'upstream_v1.9.1' into feature/v1.9.1
Cloud-J       : 6bf4a36 Merge pull request #26 from geoschem/feature/define_max_rather_than_exact_num_jvalues
HETP          : 2a99b24 Merge pull request #2 from geoschem/bugfix/initialize_local_variables

Number of execution tests: 12

Submitted as SLURM job: 46770957
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Review by lizziel — APPROVED** [review]

**Pull request merged**
