### PR TITLE
[PULL REQUEST] Feature/isop updates

### PR DESCRIPTION
**Pull request by kelvinhb**
Hi team - I've made all the updates that are required to get the code to run with (a) the new wet deposition parameters from Safieddine et al. 2017 that have been on the docket to go in for a while, and (b) the new isoprene chemistry from my paper this year with Daniel, which adds and removes a number of species. I've tested this code with all the unit test directories (I'll make a pull request for the unit tester too), and they all run with the exception of the premade nested grids, which will require new boundary conditions with the new species. I'm not sure what the protocol is for making those -- or for making new restart files for all the other simulation types, for that matter -- but let me know what I need to do to make that happen. The only other pieces of this that aren't included here are the new FJX_spec and FJX_j2j files required for the new mechanism (I made them but they don't go in these directories; I'll try to attach them here?) and new GMI prod/loss rates for strat chem. The new isoprene species don't really need those -- they're produced and lost so close to the surface that we don't need to worry about them in the stratosphere -- but if I'm supposed to make them anyway, I'll probably need some help figuring that out. Other than that, please let me know if you have any questions! 
-Kelvin

[FJX_files.zip](https://github.com/geoschem/geos-chem/files/3859552/FJX_files.zip)

### CODE REVIEW

**Comment by msulprizio** [comment]
Thanks, Kelvin! This is scheduled to go into GEOS-Chem 12.8.0. We're still wrapping up 12.7.0 and should get to this next month.

**Comment by msulprizio** [comment]
@kelvinhb I had a quick question about a difference between in your chemistry mechanism files. In Tropchem.eqn (and SOA_SVPOA.eqn), you deleted the line

```
OH + MAP = MCO3 :   GCARR(6.13E-13, 0.0E+00, 200.0);     {2013/03/22; Paulot2009; FP,EAM,JMAO,MJE}
```

However, that line is still included in Standard.eqn. Should that reaction be included in your updated chemistry mechanisms?

**Comment by kelvinhb** [comment]
> @kelvinhb I had a quick question about a difference between in your chemistry mechanism files. In Tropchem.eqn (and SOA_SVPOA.eqn), you deleted the line
> 
> ```
> OH + MAP = MCO3 :   GCARR(6.13E-13, 0.0E+00, 200.0);     {2013/03/22; Paulot2009; FP,EAM,JMAO,MJE}
> ```
> 
> However, that line is still included in Standard.eqn. Should that reaction be included in your updated chemistry mechanisms?

Hi Melissa - I figured out what was wrong here; in Tropchem.eqn and SOA_SVPOA.eqn I deleted the line you singled out in error, when instead I meant to delete a different line: HO2 + MCO3 = 0.410MAP + 0.150ACTA + 0.150O3 + 0.440OH + 0.440MO2 : GCARR(5.20E-13, 0.0E+00, 980.0);     {2013/03/22; Paulot2009; FP,EAM,JMAO,MJE}

So, in Tropchem and SOA_SVPOA, the OH+MAP line should be added back in and the old HO2+MCO3 line should be removed. Sorry about that!

**Comment by msulprizio** [comment]
> So, in Tropchem and SOA_SVPOA, the OH+MAP line should be added back in and the old HO2+MCO3 line should be removed. Sorry about that!

No problem. Thanks for providing the fix!

**Comment by msulprizio** [comment]
I ran an internal 1-month benchmark (tagged [12.8.0-beta.0](https://github.com/geoschem/geos-chem/releases/tag/12.8.0-beta.0)) to evaluate the impact of these changes. @kelvinhb At your earliest convenience, can you review the plots at the link below and let us know if you see anything of concern?

http://ftp.as.harvard.edu/pub/exchange/mpayer/GC_12.8.0_IsopChem/Plots/

**Comment by kelvinhb** [comment]
> @kelvinhb At your earliest convenience, can you review the plots at the link below and let us know if you see anything of concern?

Hi Melissa - mostly looks good! Here are the few things that caught my attention:
• The changes to complex and simple SOA look minor (as they should be), but AOD from IEPOX SOA appears to have gone to zero. Where does it pull the column loading from?
• What happened to ISOPN?! Looks like there's tons of it all over? The ISOPNB/D species should be replaced with IHN 1-4, which will have some differences, but they shouldn't be this stark.
• Is there an unrelated reason why DMS changed so drastically?
• I'm surprised how strong the decreases in GLYX are, and not just in regions with low-NOx isoprene chemistry (which is mostly what I changed in the glyoxal chemistry, and where we saw sharp decreases in my paper). Were there other changes to glyoxal chemistry in this update?

**Comment by msulprizio** [comment]
@kelvinhb See my responses below.

> • The changes to complex and simple SOA look minor (as they should be), but AOD from IEPOX SOA appears to have gone to zero. Where does it pull the column loading from?

The column AOD for SOA from aqueous isoprene is computed in aerosol_mod.F:

```
               ! Get the AOD contribution from isoprene SOA only (eam, 2014)
               IF ( N == 3 .and. Is_ComplexSOA ) THEN
                  ISOPOD(I,J,L,IWV) = SCALEOD*BXHEIGHT(I,J,L)*0.75d0
     &                              * ISOAAQ(I,J,L) * QQAA(IWV,1,N) /
     &                              ( MSDENS(N) * REAA(1,N) * 1.0D-6 )
               ENDIF
```

where ISOAAQ is

```
         !-------------------------------------------------------
         ! Mass loading of isoprene SOA (ISOAAQ) [kg/m3]
         !-------------------------------------------------------

         ! Glyoxal
         IF ( id_SOAGX > 0 ) THEN
            ISOAAQ(I,J,L) = Spc(I,J,L,id_SOAGX) / AIRVOL(I,J,L)
         ENDIF

         ! IEPOX
         IF ( id_SOAIE > 0 ) THEN
            ISOAAQ(I,J,L) = ISOAAQ(I,J,L) +
     &                      Spc(I,J,L,id_SOAIE) / AIRVOL(I,J,L)
         ENDIF

!------------------------------------------------------------------------------
! Exclude INDIOL from AOD and aerosol mass calculations. This results in lost
! mass. As noted in Fisher et al. (2016, ACP), this is a source of uncertainty
! and would benefit from an update when more information about this process
! becomes available. (eam, jaf, mps, 3/5/18)
!         ! SOA from alkyl nitrates (some contribution
!         ! from non-isoprene sources)
!         IF ( id_INDIOL > 0 ) THEN
!            ISOAAQ(I,J,L) = ISOAAQ(I,J,L) +
!     &                      Spc(I,J,L,id_INDIOL) / AIRVOL(I,J,L)
!         ENDIF
!------------------------------------------------------------------------------

         ! SOA from ISOPOOH oxidation product
         IF ( id_LVOCOA > 0 ) THEN
            ISOAAQ(I,J,L) = ISOAAQ(I,J,L) +
     &                      Spc(I,J,L,id_LVOCOA) / AIRVOL(I,J,L)
         ENDIF
```

In your updates, the contributions from methylglyoxal (SOAMG), IMAE (SOAME), and ISOP_NO3 (ISN1OA) were removed from the calculation of ISOAAQ, which would explain the decrease in value. The value doesn't quite go to zero, but it's very low (see the figure below with the color bar adjusted).
Screen Shot 2020-02-25 at 12 15 39 PM
Are there other species added in your updates that should be added to ISOAAQ in place of SOAMG, SOAME, and ISN1OA?

> • What happened to ISOPN?! Looks like there's tons of it all over? The ISOPNB/D species should be replaced with IHN 1-4, which will have some differences, but they shouldn't be this stark.

This is a GCPy plotting issue. In lumped_species.yml used by GCPy, it defined ISOPN as ISOPNB + ISOPND but when it couldn't find those fields, I think it may have replaced them with some other species from the GEOSChem.SpeciesConc output giving the high values we're seeing. This brings up a larger point, that we need to update the lumped species definitions used in our plotting routines. They're currently defined in [lumped_species.yml in the GCPy repository](https://github.com/geoschem/gcpy/blob/master/gcpy/lumped_species.yml). Could you have a look at that and provide us with any changes based on the species added/removed in your chemistry updates?

> • Is there an unrelated reason why DMS changed so drastically?

It looks like there was a change to the value of Henry_K0 for DMS in the species database from:

```
          CASE( 'DMS' )
             FullName      = 'Dimethyl sulfide'
             Formula       = '(CH3)2S'
             MW_g          = 62.0_fp
             Is_Gas        = F
             Is_Drydep     = F
             Is_Wetdep     = F
             Henry_K0      = 4.76e+1_f8
             Henry_CR      = 3100.0_f8
```
to:
```
          CASE( 'DMS' )
             FullName      = 'Dimethyl sulfide'
             Formula       = '(CH3)2S'
             MW_g          = 62.0_fp
             Is_Gas        = F
             Is_Drydep     = F
             Is_Wetdep     = F
             Henry_K0      = 4.76e+1_f8
             Henry_CR      = 3100.0_f8
```
Could that explain the differences? We look to you for guidance on any changes having to do with science.

DMS is also in our chemistry mechanism (see equations below), so presumably any change to OH or NO3 could impact DMS concentrations directly.
```
DMS + OH = SO2 + MO2 + CH2O :                GCARR(1.20E-11, 0.0E+00, -280.0);
DMS + OH = 0.750SO2 + 0.250MSA + MO2 :       GC_DMSOH(8.20E-39, 0.0E+00, 5376.0, 1.05E-5, 0.0, 3644.0);
DMS + NO3 = SO2 + HNO3 + MO2 + CH2O :        GCARR(1.90E-13, 0.0E+00, 530.0);
```

> • I'm surprised how strong the decreases in GLYX are, and not just in regions with low-NOx isoprene chemistry (which is mostly what I changed in the glyoxal chemistry, and where we saw sharp decreases in my paper). Were there other changes to glyoxal chemistry in this update?

I differenced the mechanism files (Standard.eqn) between 12.7.0 and this benchmark with your updates and sorted out the differences in GLYX reactions between the two. See 
[GLYX_Reaction_Diffs.txt](https://github.com/geoschem/geos-chem/files/4251571/GLYX_Reaction_Diffs.txt). It looks like there were many GLYX reactions that were in 12.7.0 and removed in your updates. Could that explain the decrease in GLYX? Again, we look to you for guidance on any changes having to do with science.

**Comment by kelvinhb** [comment]
@msulprizio thanks for all the details! Here are my thoughts on all these points:

• I'm still confused on the AOD drop. It's correct that SOAMG, SOAME, and ISN1OA are removed, and there's nothing that should go in to replace them, but that should only remove a small fraction of the ISOAAQ. This seems to be corroborated by the complex SOA plots in the Aerosols_500hPa and Aerosols_surface pages, which show only small changes in complex SOA loading. Also, the map you attached looks exactly like the AOD_Dust map, and doesn't show any of the isoprene patterns.

• For ISOPN: that makes sense, we just need to redefine the isoprene nitrate (and other) families. I'll write out a list of species to add/remove from each family below. I ran into a few questions while looking through those lists for which species should be adjusted: (1) do we know why OLNN and OLND are included in NOx? They appear to react like any other organonitrate to me, which would put them in NOy but not NOx. (2) Ox currently appears to include some organonitrates but not others (e.g. it includes ISOPNB but not ISOPND), and I'm not sure why that would be. In my list below I've added all the new organonitrates, but if there's a good reason to exclude some, that can be adjusted.

• For DMS: It's definitely the change in Henry_K0 that's doing it, and I got that out of Sarah Safieddine's paper with all the updates organic Henry's constants. Looking back through her paper and SI, though, I don't see where the documentation comes from for that DMS value, and it doesn't look like the changes it causes to the DMS budget were analyzed thoroughly. I think we should revert it to the old value (4.8e-1, I believe?) until someone does some further analysis on it.

• For GLYX: all those mechanism changes look correct, so let's stick with this. We knew glyoxal would decrease, I'm just surprised by the magnitude, but it's not entirely out of line with what we saw in our paper. 

Let me know if there are any other questions to address!

Edits to families:

ISOPN:
Remove: ISOPNB, ISOPND
Add: IHN1 (1), IHN2 (1), IHN3 (1), IHN4 (1)

NOy:
Remove: DHDN, IPMN, ISN1, ISN1OG, ISNP, ISOPNB, ISOPNBO2, ISOPND, ISOPNDO2, MACRN, MAN2, NPMN, PMNN
Add: ICN (1), ICNOO (1), IDHNBOO (1), IDHNDOO1 (1), IDHNDOO2 (1), IDN (2), IDNOO (2), IHN1 (1), IHN2 (1), IHN3 (1), IHN4 (1), IHPNBOO (1), IHPNDOO (1), INA (1), INO2B (1), INO2D (1), IPNB (1), INPD (1), ISOPNOO1 (1), ISOPNOO2 (1), ITCN (1), ITHN (1), MCRHN (1), MCRHNB (1), MPAN (1)

Ox:
Remove: IPMN, ISN1, ISNOHOO, ISNOOA, ISNOOB, ISNP, ISOPNB, MACRN, MAN2, NPMN, PMNN
Add: ICN (1), ICNOO (1), IDHNBOO (1), IDHNDOO1 (1), IDHNDOO2 (1), IDN (2), IDNOO (2), IHN1 (1), IHN2 (1), IHN3 (1), IHN4 (1), IHPNBOO (1), IHPNDOO (1), INA (1), INO2B (1), INO2D (1), IPNB (1), INPD (1), ISOPNOO1 (1), ISOPNOO2 (1), ITCN (1), ITHN (1), MCRHN (1), MCRHNB (1), MPAN (1), NPRNO3 (1), MENO3 (1), ETNO3 (1), OLNN (1), OLND (1)

RO2:
Remove: DHPCARP, DIBOO, HC5OO, HPC52O2, IEPOXOO, IMAO3, INO2, ISNOOA, ISNOOB, ISNP, ISOPNBO2, ISOPNDO2, MAN2, MAOPO2, MOBAOO, MRO2, NMAO3, RIO2, VRO2, 
Add: C4HVP1 (1), C4HVP2 (1), HPALD1OO (1), HPALD2OO (1), ICHOO (1), ICNOO (1), IDHNBOO (1), IDHNDOO1 (1), IDHNDOO2 (1), IDNOO (1), IEPOXAOO (1), IEPOXBOO (1), IHOO1 (1), IHOO4 (1), IHPNBOO (1), IHPNDOO (1), IHPOO1 (1), IHPOO2 (1), IHPOO3 (1), INO2B (1), INO2D (1), ISOPNOO1 (1), ISOPNOO2 (1), MACR1OO (1), MCROHOO (1), MVKOHOO (1), PO2 (1)

**Comment by msulprizio** [comment]
@kelvinhb Following up on the last remaining area of concern with the internal benchmark. The large decrease in AOD from IEPOX SOA is not solely due to your chemistry updates as originally thought. In 12.7.1, we added a fix for that diagnostic to remove the duplicate use of BXHEIGHT in the calculation. See https://github.com/geoschem/geos-chem/issues/208. Your updates were merged in on top of 12.7.1, so when comparing to 12.7.0 we see both the impacts of the isoprene SOA AOD diagnostic fix and your chemistry updates.

**Comment by msulprizio** [comment]
The `HENRY_K0` for DMS has been restored to the previously used value following @kelvinhb's recommendation above.

The `lumped_species.yml` file in https://github.com/geoschem/gcpy has also been updated following the recommendations above.

**Pull request closed without merging**
