### PR TITLE
[PULL REQUEST] Add C2H2 + C2H4 chemistry from Kelvin Bates plus CH3O2 + OH reaction (implemented by Mike Long)

### PR DESCRIPTION
**Pull request by msl3v**
## Overview
Include K. Bates' C2H2/C2H4 chem. Update run files. Add MO2 + OH = 0.13MOH + 0.87CH2O + 1.74HO2 : 1.60d-10.
MSL

Requires modified FJX_j2j.dat file, attached.
[FJX_j2j.dat.txt](https://github.com/geoschem/geos-chem/files/7197561/FJX_j2j.dat.txt)

## Reference
@kelvinhb wrote:

>   Simplified ethene and ethyne chemistry is incorporated into GEOS-Chem, including its reactions with the hydroxyl radical and ozone, based on IUPAC recommendations. The impacts of this chemistry are analyzed in Kwon et al. (below) with particular emphasis on Korea and the Seoul Metropolitan Area (SMA). Ethene has a relatively short lifetime of ~1.5 days and is emitted primarily by industrial sources, with additional biogenic and pyrogenic emissions. Ethene accounts for the second-largest amount of AVOC emissions in South Korea and was ranked fourth in contribution to OH reactivity in SMA during the KORUS-AQ campaign. Adding ethene chemistry to the model increases the HCHO mixing ratio over Korea, bringing it into closer alignment with observations, especially over the Daesan and Busan-Changwon-Geoje areas, for which the mixing ratio increases by 0.25 ppbv.
>
>  Kwon, H.-A., Park, R. J., Oak, Y., Nowlan, C. R., Janz, S. J., Kowalewski, M. G., Fried, A., Walega, J., Bates, K. H., Choi, J., Blake, D. R., Wisthaler, A, and Woo, J.-H.. Top-down estimates of anthropogenic VOC emissions in South Korea using formaldehyde vertical measurements from aircraft during the KORUS-AQ campaign. Elem. Sci. Anth. In review.

### CODE REVIEW

**Comment by msulprizio** [comment]
To properly save out emissions, the C2H2 and C2H4 sections in HEMCO_Diagn.rc file(s) should also be updated. Right now they are commented out.

```
###############################################################################
#####  C2H2 emissions                                                    ######
###############################################################################
# C2H2 is not an active species in GEOS-Chem; disable for now
#EmisC2H2_Total     C2H2   -1     -1  -1   3   kg/m2/s  C2H2_emission_flux_from_all_sectors
#EmisC2H2_Anthro    C2H2   0      1   -1   3   kg/m2/s  C2H2_emission_flux_from_anthropogenic
#EmisC2H2_Ship      C2H2   0      10  -1   2   kg/m2/s  C2H2_emission_flux_from_ships

###############################################################################
#####  C2H4 emissions                                                    ######
###############################################################################
# C2H4 is not an active species in GEOS-Chem; disable for now
#EmisC2H4_Total     C2H4   -1     -1  -1   3   kg/m2/s  C2H4_emission_flux_from_all_sectors
#EmisC2H4_Anthro    C2H4   0      1   -1   3   kg/m2/s  C2H4_emission_flux_from_anthropogenic
#EmisC2H4_Biogenic  C2H4   0      4   -1   2   kg/m2/s  C2H4_emission_flux_from_biogenic_sources
#EmisC2H4_Ship      C2H4   0      10  -1   2   kg/m2/s  C2H4_emission_flux_from_ships
```

**Comment by yantosca** [comment]
Several issues with the configuration files have now been fixed (commits, 9149a64ed68376d482c73ff68cdfa1025b95026a, ab3a2c8521036d6fb59214411f7d961451d65dcc, 6a4277a931a1ffc6256caf6a58bf2bb9c94ee9a4, 6fc59b9b7ab089a3318683334452626b238856cf). 

Also, the following species have been added to restart files:
  1. C2H2 
  2. C2H4
  3. ETHN
  4. ETHP
  5. ETO

**Review by msulprizio — CHANGES_REQUESTED** [review]
I'd like to request the following changes before approving this PR:

1. Update the FILE HISTORY section of the .eqn files for KPP to include recent updates (including C2H2 and C2H4 chemistry)

2. Add lines in HEMCO_Diagn.rc for C2H2 and C2H4 from biomass burning (to be obtained from the GFED extension)

**Review by msulprizio — APPROVED** [review]

**Comment by yantosca** [comment]
> 
> 
> I'd like to request the following changes before approving this PR:
> 
>     1. Update the FILE HISTORY section of the .eqn files for KPP to include recent updates (including C2H2 and C2H4 chemistry)
> 
>     2. Add lines in HEMCO_Diagn.rc for C2H2 and C2H4 from biomass burning (to be obtained from the GFED extension)

These are now done in commit: ce08239d957b980bd47d60dac7d07124be04d41a

**Comment by msulprizio** [comment]
Thanks! I approved these changes. Feel free to merge.

**Pull request merged**
