### PR TITLE
[PULL REQUEST] Meng offline dust

### PR DESCRIPTION
**Pull request by YanshunLi-washu**
Hi,

This pull request is for updating the offline dust emissions to a new version v2021-08. In the new version, the offline dust emissions needs no longer scaling factors. Only data paths are needed in HEMCO_Config.rc.

Thanks,
Yanshun

**Reference:**
Meng, J., Martin, R. V., Ginoux, P., Hammer, M. S., Sulprizio, M. P., Ridley, D. A. and van Donkelaar, A., Grid-independent high-resolution dust emissions (v1.0) for chemical transport models: application to GEOS-Chem (12.5.0)., Geosci. Model Dev., doi:10.5194/gmd-14-4249-2021, 2021. [[LINK]](https://gmd.copernicus.org/articles/14/4249/2021/)

### CODE REVIEW

**Review by msulprizio — APPROVED** [review]
These updates look good, and I will proceed with merging this PR into `dev` for 13.3.0. I will note that the date range for the offline dust emissions in this update remains through 2017, but files are available through 2019. I will update the end year to 2019 after merging into `dev`.

**Comment by msulprizio** [comment]
I have merged these updates with the current state of `dev` and pushed to branch `feature/Meng_OfflineDust`. Several simulations failed the integration test with GEOS-Chem Classic using gcc 10.2.0 as the compiler:

```
gc_2x25_aerosol_merra2...........................Execute Simulation.....FAIL
gc_2x25_fullchem_aciduptake_merra2...............Execute Simulation.....FAIL
gc_2x25_fullchem_APM_merra2......................Execute Simulation.....FAIL
gc_2x25_fullchem_marinePOA_merra2................Execute Simulation.....FAIL
gc_2x25_fullchem_merra2..........................Execute Simulation.....FAIL
gc_4x5_aerosol_merra2............................Execute Simulation.....FAIL
gc_4x5_fullchem_aciduptake_geosfp................Execute Simulation.....FAIL
gc_4x5_fullchem_aciduptake_merra2................Execute Simulation.....FAIL
gc_4x5_fullchem_APM_geosfp.......................Execute Simulation.....FAIL
gc_4x5_fullchem_APM_merra2.......................Execute Simulation.....FAIL
gc_4x5_fullchem_complexSOA_geosfp................Execute Simulation.....FAIL
gc_4x5_fullchem_complexSOA_merra2................Execute Simulation.....FAIL
gc_4x5_fullchem_complexSOA_SVPOA_geosfp..........Execute Simulation.....FAIL
gc_4x5_fullchem_complexSOA_SVPOA_merra2..........Execute Simulation.....FAIL
gc_4x5_fullchem_geosfp...........................Execute Simulation.....FAIL
gc_4x5_fullchem_LuoWd_geosfp.....................Execute Simulation.....FAIL
gc_4x5_fullchem_LuoWd_merra2.....................Execute Simulation.....FAIL
gc_4x5_fullchem_marinePOA_geosfp.................Execute Simulation.....FAIL
gc_4x5_fullchem_marinePOA_merra2.................Execute Simulation.....FAIL
gc_4x5_fullchem_merra2...........................Execute Simulation.....FAIL
gc_4x5_fullchem_merra2_47L.......................Execute Simulation.....FAIL
gc_4x5_fullchem_RRTMG_geosfp.....................Execute Simulation.....FAIL
gc_4x5_fullchem_RRTMG_merra2.....................Execute Simulation.....FAIL
gc_4x5_fullchem_TOMAS15_merra2...................Execute Simulation.....FAIL
gc_4x5_fullchem_TOMAS40_merra2...................Execute Simulation.....FAIL
geosfp_025x03125_fullchem_na_47L.................Execute Simulation.....FAIL
merra2_05x0625_fullchem_as_47L...................Execute Simulation.....FAIL
Execution tests failed: 27
```

Logs from the failed simulations suggests there may be an issue in the regridding routines. For example, from execute.gc_4x5_fullchem_merra2.log:

```
HEMCO: Opening /n/holyscratch01/external_repos/GEOS-CHEM/gcgrid/gcdata/ExtData/HEMCO/OFFLI
NE_DUST/v2021-08/0.5x0.625/2019/07/dust_emissions_05.20190701.nc

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:
#0  0x2ad6cdc443ff in ???
#1  0xe8f019 in __hco_regrid_a2a_mod_MOD_xmap_r4r4._omp_fn.0
        at /n/holyscratch01/jacob_lab/msulprizio/GC/rundirs/IntTest_GCC_13.3.0-alpha.1/Cod
eDir/src/HEMCO/src/Shared/GeosUtil/hco_regrid_a2a_mod.F90:1963
#2  0x2ad6cd3670a1 in GOMP_parallel
        at ../.././libgomp/parallel.c:171
#3  0xe80e6f in xmap_r4r4
        at /n/holyscratch01/jacob_lab/msulprizio/GC/rundirs/IntTest_GCC_13.3.0-alpha.1/Cod
eDir/src/HEMCO/src/Shared/GeosUtil/hco_regrid_a2a_mod.F90:1998
#4  0xe89cf8 in __hco_regrid_a2a_mod_MOD_map_a2a_r4r4
        at /n/holyscratch01/jacob_lab/msulprizio/GC/rundirs/IntTest_GCC_13.3.0-alpha.1/Cod
eDir/src/HEMCO/src/Shared/GeosUtil/hco_regrid_a2a_mod.F90:328
#5  0xe1c710 in __hco_interp_mod_MOD_regrid_mapa2a
        at /n/holyscratch01/jacob_lab/msulprizio/GC/rundirs/IntTest_GCC_13.3.0-alpha.1/CodeDir/src/HEMCO/src/Core/hco_interp_mod.F90:381
#6  0xdafe28 in __hcoio_read_mod_MOD_hcoio_read
        at /n/holyscratch01/jacob_lab/msulprizio/GC/rundirs/IntTest_GCC_13.3.0-alpha.1/CodeDir/src/HEMCO/src/Core/hcoio_read_std_mod.F90:1411
#7  0xd688e4 in __hcoio_dataread_mod_MOD_hcoio_dataread
        at /n/holyscratch01/jacob_lab/msulprizio/GC/rundirs/IntTest_GCC_13.3.0-alpha.1/CodeDir/src/HEMCO/src/Core/hcoio_dataread_mod.F90:202
#8  0xd51449 in readlist_fill
        at /n/holyscratch01/jacob_lab/msulprizio/GC/rundirs/IntTest_GCC_13.3.0-alpha.1/CodeDir/src/HEMCO/src/Core/hco_readlist_mod.F90:500
#9  0xd526e6 in __hco_readlist_mod_MOD_readlist_read
        at /n/holyscratch01/jacob_lab/msulprizio/GC/rundirs/IntTest_GCC_13.3.0-alpha.1/CodeDir/src/HEMCO/src/Core/hco_readlist_mod.F90:327
#10  0xcfd998 in __hco_driver_mod_MOD_hco_run
        at /n/holyscratch01/jacob_lab/msulprizio/GC/rundirs/IntTest_GCC_13.3.0-alpha.1/CodeDir/src/HEMCO/src/Core/hco_driver_mod.F90:155
#11  0x591aec in __hco_interface_gc_mod_MOD_hcoi_gc_run
        at /n/holyscratch01/jacob_lab/msulprizio/GC/rundirs/IntTest_GCC_13.3.0-alpha.1/CodeDir/src/GEOS-Chem/GeosCore/hco_interface_gc_mod.F90:1000
#12  0x4ad745 in __emissions_mod_MOD_emissions_run
        at /n/holyscratch01/jacob_lab/msulprizio/GC/rundirs/IntTest_GCC_13.3.0-alpha.1/CodeDir/src/GEOS-Chem/GeosCore/emissions_mod.F90:203
#13  0x406137 in geos_chem
        at /n/holyscratch01/jacob_lab/msulprizio/GC/rundirs/IntTest_GCC_13.3.0-alpha.1/CodeDir/src/GEOS-Chem/Interfaces/GCClassic/main.F90:741
#14  0x40b87c in main
        at /n/holyscratch01/jacob_lab/msulprizio/GC/rundirs/IntTest_GCC_13.3.0-alpha.1/CodeDir/src/GEOS-Chem/Interfaces/GCClassic/main.F90:32
srun: error: holy7c20304: task 0: Floating point exception (core dumped)
```

**Comment by YanshunLi-washu** [comment]
Thanks @msulprizio for identifying this. I found NaN values in dust_emissions_05.20190701.nc, which maybe cause this error. I'm rechecking the regridding routines now.

**Comment by msulprizio** [comment]
Excellent. Thanks @YanshunLi-washu! Do keep me posted please.

**Comment by YanshunLi-washu** [comment]
@msulprizio Will do! I found NaN values in Jun Meng's original products. I applied scaling factors upon his. I will contact Jun (cc you) to resolve this ASAP.

**Comment by YanshunLi-washu** [comment]
Hi @msulprizio Jun and I found NaN values only in the 05x0625 merra2 dust files. We're currently working on fixing it. The 025x03125 geosfp dust files look good. 

But I noticed there were also geosfp simulations failed in your tests. Could you kindly share me the log info?

Besides, Jun mentioned the version of the compiler might be a problem, but he's not sure. Have you tried different versions?

Thanks,
Yanshun

**Comment by msulprizio** [comment]
Thanks @YanshunLi-washu.

We always use the GFortran compiler (gcc 10.2.0) for our integration tests because they tend to be more strict and catch more bugs. We also turn on debug flags in integration tests, which will catch floating-point exception errors like the one we see here. Changing compilers and/or turning off debug flags may get us around the error, but that does not resolve the root problem.

For the GEOS-FP simulations that fail, there may be a bug in our integration test. I checked the log file for the gc_4x5_fullchem_geosfp simulation, and it appears to be reading the 0.5x0.625 offline dust file which is incorrect. That simulation should be using the 0.25x0.3125 simulation. I will double check the settings of the integration test to resolve that issue. Thanks for pointing that out!

**Comment by msulprizio** [comment]
The issue for the GEOS-FP integration tests has now been fixed in commit e7d00d045a2e9457cd7d5987e8136d8bf3d5ec58 (currently in the `dev` branch). I will rerun the integration tests for the offline dust updates when we have a fix for the MERRA-2 files.

**Comment by YanshunLi-washu** [comment]
Hi @msulprizio The updated offline dust emissions v2021-08 can be found at http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625. NaN values have been removed

**Comment by msulprizio** [comment]
Thanks @YanshunLi-washu! I can confirm that all of the integration tests are now passing with the updated files. I will merge into `dev` shortly for inclusion in 13.3.0.

**Comment by yantosca** [comment]
I have removed the warnings to use online dust instead of offline dust in  9bc0b9316712ac6d57b7a6a69487a80daaefabb7, which has been added to the 13.4.0 development stream.

**Pull request merged**
