### PR TITLE
[PULL REQUEST] HMS Chemistry, adding updates of Moch et al 2020 (replaces PR #456)

### PR DESCRIPTION
**Pull request by yantosca**
# HMS chemistry

##  Overview
  - Original code: PR #456 
  - Merged with PR #897, and resolved conflicts
  - Merged in additional updates from 13.3.0-alpha.1.  This allows a clean test of w/r/t 13.3.0-alpha.1.
  - This PR now supersedes #456.

## Description
This update includes hydroxymethanesulfonate (HMS) chemistry and cloud pH and ionic strength limitations for transition metal catalyzed SO2 oxidation.

HMS chemistry is described in: Moch, J.M., E. Dovrou, L.J. Mickley, F.N. Keutsch, Z. Liu, Y. Wang, T.L. Dombek, M. Kuwata, S.H. Budisulistiorini, L. Yang, S. Decesari, M. Paglione, B. Alexander, J. Shao, J.W. Munger, D.J. Jacob, Global importance of hydroxymethanesulfonate in ambient particulate matter: Implications for air quality, J. Geophys. Res., 125, e2020JD032706, https://doi.org/10.1029/2020JD032706, 2020

The cloud pH and ionic strength limitation for transition metal catalyzed SO2 oxidation is initially described in: Shao, J., Chen, Q., Wang, Y., Lu, X., He, P., Sun, Y., Shah, V., Martin, R. V., Philip, S., Song, S., Zhao, Y., Xie, Z., Zhang, L., & Alexander, B. (2019). Heterogeneous sulfate aerosol formation mechanisms during wintertime Chinese haze events: Air quality model assessment using observations of sulfate oxygen isotopes in Beijing. Atmospheric Chemistry and Physics, 19(9), 6107–6123. https://doi.org/10.5194/acp-19-6107-2019

HMS chemistry was initially implemented in 12.2.1 as described in Moch et al. (2020). Differences for HMS chemistry between Moch et al. (2020) and version 12.9.3 arise primarily from the inclusion of Na+ and Cl- in the cloud pH calculation in 12.9.3, differing default emissions inventories, and simulated cloud pH being too low over eastern China in 12.9.3. In Moch et al. (2020), this low bias in cloud pH over eastern China was addressed by setting a cloud pH floor of 5 over the North China Plain. This pH floor is not included in this pull request but more details can be found in the paper.

### CODE REVIEW

**Comment by yantosca** [comment]
Results of a 1-day simulation:

### Ref: 13.3.0-alpha.1
```
==============================================================================
GEOS-Chem FULL-CHEMISTRY SIMULATION METRICS

Simulation start : 2019-07-01 00:00:00z
Simulation end   : 2019-07-02 00:00:00z
============================================================================== 

Mass-weighted mean OH concentration    = 11.24561220053 x 10^5 molec cm-3

CH3CCl3 lifetime w/r/t tropospheric OH = 5.4776 years

CH4 lifetime w/r/t tropospheric OH     = 9.2152 years
```

### Dev: PR #905
```
==============================================================================
GEOS-Chem FULL-CHEMISTRY SIMULATION METRICS

Simulation start : 2019-07-01 00:00:00z
Simulation end   : 2019-07-02 00:00:00z
============================================================================== 

Mass-weighted mean OH concentration    = 11.24524496737 x 10^5 molec cm-3

CH3CCl3 lifetime w/r/t tropospheric OH = 5.4779 years

CH4 lifetime w/r/t tropospheric OH     = 9.2158 years
```

**Comment by yantosca** [comment]
## Integration tests

### GEOS-Chem Classic

```
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 79
Execution tests failed: 1
Execution tests not yet completed: 0
```
The failing test is:
```
geosfp_025x03125_fullchem_na_47L.................Execute Simulation.....FAIL
```
which failed due to a SLURM "Out-of-memory" error.  We need to therefore bump up the requested amount of memory in the integration test run script.

### GCHP
```
==============================================================================
GCHP: Execution Test Results

Number of execution tests: 3
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gchp_fullchem_benchmark_merra2_c48...............Execute Simulation.....PASS
gchp_fullchem_standard_merra2_c24................Execute Simulation.....PASS
gchp_TransportTracers_geosfp_c24.................Execute Simulation.....PASS
 
Summary of execution test results:
------------------------------------------------------------------------------
Execution tests passed:        3
Execution tests failed:        0
Execution tests not completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
There are a couple of outstanding modifications to make:

  1. Add `SpeciesRst_HMS` to the `ExtData/GEOSCHEM_RESTARTS/v2021-09/GEOSChem.Restart.fullchem.20190701_0000z.nc4` file
  2. Add `SpeciesRst_HMS` to the `ExtData/GEOSCHEM_RESTARTS/v2021-09/GEOSChem.Restart.aerosol.20190701_0000z.nc4`
  3. Update `run/GCClassic/createRunDir.sh` to get these restart files.

**Review by msulprizio — CHANGES_REQUESTED** [review]
There is no formula provided for HMS in `species_database.yml` but one should be provided. According to Moch et al. (2020) it is HOCH2SO3−.

Can you also confirm if a parallelization test was performed on these updates? I see code was added to a parallel loop in `sulfate_mod.F90` so it would be good to ensure we're not introducing any differences between single and multi-processor runs.

**Comment by yantosca** [comment]
@msulprizio, thanks for the comments.  I will definitely do a parallelization test.  I am will also add the formula.

**Comment by yantosca** [comment]
> 
> 
> There are a couple of outstanding modifications to make:
> 
>     1. Add `SpeciesRst_HMS` to the `ExtData/GEOSCHEM_RESTARTS/v2021-09/GEOSChem.Restart.fullchem.20190701_0000z.nc4` file
> 
>     2. Add `SpeciesRst_HMS` to the `ExtData/GEOSCHEM_RESTARTS/v2021-09/GEOSChem.Restart.aerosol.20190701_0000z.nc4`
> 
>     3. Update `run/GCClassic/createRunDir.sh` to get these restart files.

These updates have been done in commit 885a198c4ca79d7cb80b7cfd44e3eccd922e6108

**Comment by yantosca** [comment]
A parallelization test failed.  Digging into this now @msulprizio

**Comment by yantosca** [comment]
> 
> 
> > A parallelization test failed. Digging into this now @msulprizio
> 
> Thanks @yantosca. Glad we checked!

Seems to not be in the chemistry or aerosol thermodynamics.  Digging further.

**Comment by yantosca** [comment]
Side note: I have isolated the parallelization issue to the HEMCO MEGAN extension (see https://github.com/geoschem/HEMCO/issues/109).  With MEGAN emissions turned off we obtain identical results, indicating that the parallelization in GEOS-Chem is OK.  We will pursue resolution of https://github.com/geoschem/HEMCO/issues/109 separately.

**Comment by yantosca** [comment]
Need to still fix some issues in the aerosol-only simulation.  This does not affect the full-chemistry simulation
```
Fortran runtime error: Index '-1' of dimension 4 of array 'spc' below lower bound of 1
```
Maybe some arrays are not allocated for HMS when doing an aerosol-only simulation.

**Review by msulprizio — APPROVED** [review]
I am OK with merging these updates as soon as the integration tests are all passing.

**Comment by yantosca** [comment]
Fixed bugs in commits d4aebf2b07d117c27a13ec3e81d5d4859970fdd8 and e0935cceb345764bdd4191b933fc4aea4898567a.  Also created new TOMAS15 and TOMAS40 restart files in `GEOSCHEM_RESTARTS/v2021-09/` by taking the ones from `GEOSCHEM_RESTARTS/v2020-02` and adding HMS, HSO3m, and SO3mm species.  A new set of integration tests is pending.

**Comment by yantosca** [comment]
Pushed more commits: 8bf24a15351d26eaeae9dffad82470c6d06f4fcf, 6f5db0c7d556d42828487d423d0e829028e5a962, and 5167c68d17345cb5ddb43d8870eca6b5c8a9c700.  Also re-re-generated TOMAS15 and TOMAS40 restart files in `GEOSCHEM_RESTARTS/v2021-09/` to add HMS.  Furthermore, made sure that TOMAS integration tests use 47 levels instead of 72 levels.  Integration tests now pending.

**Pull request merged**
