### PR TITLE
Update sample fullchem restart files and specialty simulation oxidant fields to 14.0.0 10-year benchmark output 

### PR DESCRIPTION
**Pull request by msulprizio**
The script `createRunDir.sh` has been updated so that full-chemistry simulations now use restart files from the 10-year benchmark for 14.0.0-rc.3.

The fields for offline oxidants used in specialty simulations have also been updated to use output from the 10-year benchmark simulation. These file paths for these fields are specified in `run/shared/settings/gmao_hemco.txt`.

### CODE REVIEW

**Comment by msulprizio** [comment]
The Hg simulation currently uses 2016 oxidant and aerosol fields stored in [`ExtData/HEMCO/MERCURY/v2022-04/`](http://geoschemdata.wustl.edu/ExtData/HEMCO/MERCURY/v2022-04/README). Should we update these entries to also use output from the 10-year (2020-2019) benchmark for 14.0.0? 

@viral211 @jennyfisher @cdholmes Any thoughts?

**Comment by jennyfisher** [comment]
I think we discussed this on the other Hg thread (apologies, I don't have the number/link in front of me), and the recommendation was not to update the oxidant fields for Hg as the Br fields would change a lot and this would require re-calibrating the reduction rates. @arifein - is that correct?

**Comment by arifein** [comment]
@jennyfisher yes, I agree with you. We had said [here](https://github.com/geoschem/geos-chem/pull/1356#issuecomment-1280075039) that we would leave all other oxidants pointing to the 13.0.0 versions.

**Comment by msulprizio** [comment]
@jennyfisher @arifein Thanks for confirming . We will leave those fields as they are in the Hg simulation.

**Comment by msulprizio** [comment]
This update passes all GCClassic and GCHP integration tests:

```
==============================================================================
GEOS-Chem Classic: Execution Test Results

Using 24 OpenMP threads
Number of execution tests: 48
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gc_025x03125_CH4_geosfp_47L_na...................Execute Simulation.....PASS
gc_025x03125_fullchem_geosfp_47L_na..............Execute Simulation.....PASS
gc_05x0625_CH4_merra2_47L_na.....................Execute Simulation.....PASS
gc_05x0625_fullchem_merra2_47L_na................Execute Simulation.....PASS
gc_2x25_aerosol_merra2...........................Execute Simulation.....PASS
gc_2x25_CH4_merra2...............................Execute Simulation.....PASS
gc_2x25_CO2_merra2...............................Execute Simulation.....PASS
gc_2x25_fullchem_merra2..........................Execute Simulation.....PASS
gc_2x25_Hg_merra2................................Execute Simulation.....PASS
gc_2x25_metals_merra2............................Execute Simulation.....PASS
gc_2x25_POPs_BaP_merra2..........................Execute Simulation.....PASS
gc_2x25_tagCH4_merra2............................Execute Simulation.....PASS
gc_2x25_tagCO_merra2.............................Execute Simulation.....PASS
gc_2x25_tagO3_merra2.............................Execute Simulation.....PASS
gc_2x25_TransportTracers_merra2..................Execute Simulation.....PASS
gc_2x25_TransportTracers_merra2_LuoWd............Execute Simulation.....PASS
gc_4x5_aerosol_geosfp............................Execute Simulation.....PASS
gc_4x5_aerosol_merra2............................Execute Simulation.....PASS
gc_4x5_CH4_geosfp................................Execute Simulation.....PASS
gc_4x5_CH4_merra2................................Execute Simulation.....PASS
gc_4x5_fullchem_aciduptake_merra2................Execute Simulation.....PASS
gc_4x5_fullchem_APM_merra2.......................Execute Simulation.....PASS
gc_4x5_fullchem_benchmark_merra2.................Execute Simulation.....PASS
gc_4x5_fullchem_complexSOA_merra2................Execute Simulation.....PASS
gc_4x5_fullchem_complexSOA_SVPOA_merra2..........Execute Simulation.....PASS
gc_4x5_fullchem_geosfp...........................Execute Simulation.....PASS
gc_4x5_fullchem_marinePOA_merra2.................Execute Simulation.....PASS
gc_4x5_fullchem_merra2...........................Execute Simulation.....PASS
gc_4x5_fullchem_merra2_47L.......................Execute Simulation.....PASS
gc_4x5_fullchem_merra2_LuoWd.....................Execute Simulation.....PASS
gc_4x5_fullchem_RRTMG_merra2.....................Execute Simulation.....PASS
gc_4x5_fullchem_TOMAS15_merra2_47L...............Execute Simulation.....PASS
gc_4x5_fullchem_TOMAS40_merra2_47L...............Execute Simulation.....PASS
gc_4x5_Hg_geosfp.................................Execute Simulation.....PASS
gc_4x5_Hg_merra2.................................Execute Simulation.....PASS
gc_4x5_metals_merra2.............................Execute Simulation.....PASS
gc_4x5_POPs_BaP_geosfp...........................Execute Simulation.....PASS
gc_4x5_POPs_BaP_merra2...........................Execute Simulation.....PASS
gc_4x5_tagCH4_geosfp.............................Execute Simulation.....PASS
gc_4x5_tagCH4_merra2.............................Execute Simulation.....PASS
gc_4x5_tagCO_geosfp..............................Execute Simulation.....PASS
gc_4x5_tagCO_merra2..............................Execute Simulation.....PASS
gc_4x5_tagO3_geosfp..............................Execute Simulation.....PASS
gc_4x5_tagO3_merra2..............................Execute Simulation.....PASS
gc_4x5_TransportTracers_geosfp...................Execute Simulation.....PASS
gc_4x5_TransportTracers_geosfp_LuoWd.............Execute Simulation.....PASS
gc_4x5_TransportTracers_merra2...................Execute Simulation.....PASS
gc_4x5_TransportTracers_merra2_LuoWd.............Execute Simulation.....PASS
 
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 48
Execution tests failed: 0
Execution tests not yet completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

```
==============================================================================
GCHP: Execution Test Results

Number of execution tests: 3
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gchp_fullchem_benchmark_merra2_c48...............Execute Simulation.....PASS
gchp_fullchem_standard_merra2_c24................Execute Simulation.....PASS
gchp_TransportTracers_geosfp_c24.................Execute Simulation.....PASS
 
Summary of execution test results:
------------------------------------------------------------------------------
Execution tests passed:        3
Execution tests failed:        0
Execution tests not completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Review by yantosca — CHANGES_REQUESTED** [review]
These changes look good.  Do we have to hardwire the paths to the oxidant fields for the HEMCO_Config.rc.Hg template file to GC_13.0.0?

**Comment by msulprizio** [comment]
> These changes look good. Do we have to hardwire the paths to the oxidant fields for the HEMCO_Config.rc.Hg template file to GC_13.0.0?

No, these are currently hardcoded to use the fields in `HEMCO/MERCURY/v2022-04/` and should remain that way as discussed above.

https://github.com/geoschem/geos-chem/blob/230098b8848a7ea2a9fae9413f7071a4d3ef7141/run/shared/settings/gmao_hemco.txt#L68-L124

**Review by yantosca — APPROVED** [review]
Good to merge.  Thanks @msulprizio!

**Pull request merged**
