### PR TITLE
HEMCO 3.0 Restructuring of Module Interfaces

### PR DESCRIPTION
**Pull request by jimmielin**
Hi GCST,

I'm creating this PR to document the first stage of work I'm doing to restructure HEMCO and GEOS-Chem's model interface. **This update renames a lot of the HEMCO modules in GEOS-Chem** and thus changes a lot of files.

Summary of the changes:
* `HCO_Interface_Mod` **removed**.
   * `HcoState` and `ExtState` are now stored in `HCO_State_GC_Mod`, which only contains those, so dependencies from other modules that require `HcoState` and `ExtState` directly are easier.
   * Other "utility" functions have been moved to HEMCO (`HEMCO/src/Interfaces/hco_interface_common.F90`) or `HCO_Utilities_GC_Mod`.

* `HCOI_GC_Main_Mod` **renamed** to `HCO_Interface_GC_Mod`.
   * This new module will contain the Init-Run-Final routines in HEMCO for GEOS-Chem.
   * `Get_Met_Fields`, `Get_Boundary_Conditions`, `Get_GC_Restart` have been moved to `HCO_Utilities_GC_Mod`.
   * Other misc. "utility" functions that may be reused will also be moved into `Utilities`, otherwise they'll be kept here.

The goal is to have other-model-usable components be in HEMCO (`hco_interface_common.F90` so they can be shared); if they touch upon GEOS-Chem data structures, they go into `GeosCore/hco_utilities_gc_mod.F90`.

The plan according to Slack chat with @lizziel and @msulprizio is to probably merge this in `dev/12.9.0` as this changes so many files and code divergence should be minimized. This means HEMCO will come as a submodule earlier than expected, though.

Discussion and suggestions are always welcome! This work is not finished - this is a first stage to lay down the file structure then we can do more restructuring going forward.

Thank you!

Best,
Haipeng

**Original commit message below:**
This commit includes updates to streamline the HEMCO to GC interface to prepare for coupling HEMCO to other models.

Generic functions pertaining to interfacing HEMCO with other models has been moved to HEMCO/Interfaces/HCO_Interface_Common.F90.

 - GetHcoId (by name) has been removed and now HCO_GetHcoId in HCO_State_Mod should be used.
 - GetHcoVal has been split into GetHcoValEmis and GetHcoValDep to clarify purpose and accept HcoState. They are mapped through HCO_Utilities_GC_Mod through a simple pass-through for now, but will be changed in the future to accommodate for an on-demand mapping of species IDs from GC-to-HEMCO (currently the same) and an intermediate grid feature which will require regridding of HEMCO data to the GEOS-Chem grid.

HCO_Interface_Mod and HCOI_GC_Main_Mod have been merged to HCO_Interface_GC_Mod and will be further cleaned up in a future commit.

Generic function wrappers will now live in HCO_Utilities_GC_Mod, along with GEOS-Chem specific "data broker" functions like Get_Met_Fields, Bdy conditions, and Restart.

HEMCO state objects (HcoState, ExtState) now live in HCO_State_GC_Mod to prevent circular dependencies.

This build has been tested with cmake. Compatibility with GNU Make is a best-attempt but due to slated removal of GNU Make in 13.0.0, it has not been thoroughly tested.

Signed-off-by: Haipeng Lin <hplin@seas.harvard.edu>

### CODE REVIEW

**Comment by lizziel** [comment]
This PR was just closed but the branch it was on was deleted. dev/13.0.0 is obsolete and not going to be merged in. I am creating a new dev/13.0.0 branch in the line of development that will be merged and will manually add updates for this PR.

**Comment by lizziel** [comment]
Reading through this it sounds like this is not ready to be merged. @jimmielin , can you give an update on status? I can bring in updates to the new dev/13.0.0 whenever.

**Comment by jimmielin** [comment]
Hi Lizzie, as the changes will be substantial it’d be good to merge these
in first as they rearrange the module files and quite a lot of routines.
This will make merging further HEMCO changes easier. I plan to make a
further batch of updates that add more interfaces later. Thanks!

**Comment by lizziel** [comment]
Okay, sounds great. So I can expect everything to be functional as is.

**Comment by jimmielin** [comment]
Yes! Please let me know if there are any issues. I’m using the new
interfaces here for HEMCO-CESM so they should be working, but I only did a
compile test and quick run in GEOS-Chem classic. I did update the interface
for GCHP too. The difference test was not available with CMake to do a
further evaluation.

**Pull request closed without merging**
