### PR TITLE
Add nitrate aerosol to Ox family definition in gckpp.kpp

### PR DESCRIPTION
**Pull request by msulprizio**
### Name and Institution (Required)

Name: Melissa Sulprizio
Institution: Harvard / GCST

### Describe the update

Nitrate aerosol (NIT + NITs) were previously not included in the Ox family definitions (POx, LOx) in KPP/fullchem/gckpp.kpp. This is now fixed. The fullchem mechanism has also been rebuilt with KPP to incorporate this fix.

### Expected changes

This update may cause differences on the level of numerical noise due to rebuilding the fullchem mechanism. It will also change the model output for the Ox family.

### Related Github Issue(s)

- https://github.com/geoschem/geos-chem/issues/2070

### CODE REVIEW

**Comment by msulprizio** [comment]
Also tagging @jimmielin @viral211

**Review by yantosca — CHANGES_REQUESTED** [review]
Looks good @msulprizio, but we also need to add the same change to `#FAMILIES` in `KPP/custom/custom.kpp`.

**Comment by msulprizio** [comment]
> Looks good @msulprizio, but we also need to add the same change to `#FAMILIES` in `KPP/custom/custom.kpp`.

Thanks for catching that. It is now fixed in https://github.com/geoschem/geos-chem/pull/2071/commits/6520fc1f776da578df89ec26a693250eb9ffefbe.

**Review by yantosca — APPROVED** [review]
Thanks @msulprizio!  Now good to merge.

**Pull request merged**
