### PR TITLE
Add GCHP diagnostics for GCHPctmEnv and FV3 gridded components

### PR DESCRIPTION
**Pull request by lizziel**
### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### Describe the update

This PR adds three new collections to GCHP `HISTORY.rc` files. These collections are to output the exports of the GCHPctmEnv and FV3 advection gridded components. The upwards mass flux diagnostic which is part of GCHPctmEnv and which was previously included in the `LevelEdgeDiags` collection is now in the `GCHPctmEnvLevEdge` collection with other exports in that gridded component.

### Expected changes

This is a no diff update. The new collections will be off by default for all GCHP simulations.

### Reference(s)

None

### Related PRs (should be brought in at the same time)

- https://github.com/geoschem/GCHP/pull/395
- https://github.com/geoschem/FVdycoreCubed_GridComp/pull/8

### Collaborators or others who may be interested in this PR

@sdeastham

### CODE REVIEW

**Review by yantosca — CHANGES_REQUESTED** [review]
Hi @lizziel: Looks good but we should also add the new collections to the `HISTORY.rc.carbon` template file as well.

**Comment by lizziel** [comment]
Done!

**Comment by lizziel** [comment]
I also turned on the collections by default for transport tracer simulation.

**Review by yantosca — APPROVED** [review]
Thanks @lizziel!  Approved and I'll start bringing into the no-diff branch.

**Comment by yantosca** [comment]
All GEOS-Chem Classic integration tests passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

GCClassic #159752f GEOS-Chem submod update: Merge PR #2224 (Fix units of State_Met%PHIS)
GEOS-Chem #ff6db31a6 Merge PR #2199 (Add GCHP diags for GCHPctmEnv and FV3 grid comps)
HEMCO     #2a4bb12 Merge PR #268 (Handle 3D NEI emissions)

Using 24 OpenMP threads
Number of execution tests: 26

Submitted as SLURM job: 25453401
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

All GEOS-Chem Classic integration tests are zero-diff w/r/t 14.3.0, except for
- APM (known parallelization issue)
- RRTMG (numerical noise in RRTMG collection)

Also note: geos-chem PR #2224 has now changed the units of State_Met%PHIS, so these show up as differences in the StateMet collection.

All GCHP integration tests passed:

```console
==============================================================================
GCHP: Execution Test Results

GCHP      #5ebded8 Merge PR #395 (Expand GCHP advection diagnostics)
GEOS-Chem #ff6db31a6 Merge PR #2199 (Add GCHP diags for GCHPctmEnv and FV3 grid comps)
HEMCO     #2a4bb12 Merge PR #268 (Handle 3D NEI emissions)

Number of execution tests: 6

Submitted as SLURM job: 25454095
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
All GCHP integration tests were zero-diff w/r/t 14.3.0,

Also note: geos-chem PR #2224 has now changed the units of State_Met%PHIS, so these show up as differences in the StateMet collection.

Furthermore: The TransportTracers PR has additional diagnostics not present in the 14.3.0 integration tests, so these show up as differences.

**Pull request merged**
