### PR TITLE
Added a 'DefaultCollection' to GCHP

### PR DESCRIPTION
**Pull request by LiamBindle**
By default, this is the only colllection enabled for a standard chemistry simulation. The default variables are
- O3, NO, NO2, OH, CO
- PM25
- T, RH, PBLH, AIRDEN, PMID, PMIDDRY, TropHt, TropP, BXHEIGHT, PS1DRY, PS1WET

### CODE REVIEW

**Comment by yantosca** [comment]
Integration tests are in progress.

**Comment by yantosca** [comment]
GCHP integration tests passed
```console
==============================================================================
GCHP: Execution Test Results

Number of execution tests: 3
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gchp_fullchem_benchmark_merra2_c48...............Execute Simulation.....PASS
gchp_fullchem_standard_merra2_c24................Execute Simulation.....PASS
gchp_TransportTracers_geosfp_c24.................Execute Simulation.....PASS
 
Summary of execution test results:
------------------------------------------------------------------------------
Execution tests passed:        3
Execution tests failed:        0
Execution tests not completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
Several GEOS-Chem Classic integration tests failed, we are investigating.
```console
gc_2x25_fullchem_APM_geosfp......................Execute Simulation.....FAIL
gc_2x25_fullchem_APM_merra2......................Execute Simulation.....FAIL
gc_2x25_fullchem_complexSOA_geosfp...............Execute Simulation.....FAIL
gc_2x25_fullchem_complexSOA_merra2...............Execute Simulation.....FAIL
gc_2x25_fullchem_complexSOA_SVPOA_geosfp.........Execute Simulation.....FAIL
gc_2x25_fullchem_complexSOA_SVPOA_merra2.........Execute Simulation.....FAIL
gc_2x25_fullchem_geosfp..........................Execute Simulation.....FAIL
gc_2x25_fullchem_marinePOA_geosfp................Execute Simulation.....FAIL
gc_2x25_fullchem_marinePOA_merra2................Execute Simulation.....FAIL
gc_2x25_fullchem_merra2..........................Execute Simulation.....FAIL
gc_2x25_Hg_geosfp................................Execute Simulation.....FAIL
gc_2x25_Hg_merra2................................Execute Simulation.....FAIL
gc_2x25_metals_merra2............................Execute Simulation.....FAIL
gc_2x25_POPs_BaP.geosfp..........................Execute Simulation.....FAIL
```

**Comment by yantosca** [comment]
These seem to be due to some kind of SLURM scheduler error:
```console
srun: error: Unable to confirm allocation for job 52315653: Socket timed out on send/recv operation
srun: Check SLURM_JOB_ID environment variable. Expired or invalid job 52315653
```console

**Comment by yantosca** [comment]
I re-ran the GC-Classic integration tests and they all passed.  Several jobs had failed previously but this was an issue with our scratch disk and nothing to do with GEOS-Chem.
```console
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 80
Execution tests failed: 0
Execution tests not yet completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by lizziel** [comment]
I think this might catch some users off-guard. What do you think about adding a print in interactive run directory creation warning that the default diagnostic collection contains a reduced set of fields and users may enabled other diagnostics in HISTORY.rc?

**Comment by lizziel** [comment]
For reference, below is an example of what we currently print when creating a standard simulation:

>   -- Using default directory name gchp_merra2_fullchem
> 
>   -- This run directory has been set up for 20190701 000000 - 20190701 010000.
>   -- The default diagnostic frequency, duration, and mode is hourly average.
>   -- You may modify these settings in runConfig.sh.

We could have something like this instead:

>   -- This run directory has been set up for 20190701 000000 - 20190701 010000.
>.  -- The default diagnostic frequency, duration, and mode is hourly average.
>   -- You may modify these settings in runConfig.sh.
>   -- Only one diagnostic collection is turned on by default and it contains a minimal set of variables.
>   -- You may modify which collections are turned on in HISTORY.rc. 

This message made me realize the default collection must be added to the collection list in `runConfig.sh` for the auto-update of diagnostic collection attributes to apply. If it is intended to be skipped then the message above needs to be further changed.

**Comment by LiamBindle** [comment]
I don't see a need for `runConfig.sh` to manage HISTORY collections because there aren't any settings that are shared with other config files. I think the downside of runConfig.sh managing HISTORY collections is it makes using custom collections more complicated because it isn't obvious which parts of HISTORY.rc should/shouldn't be edited manually. For science simulations, I think users should almost always be using custom collections, so I'd favor removing all HISTORY handling in runConfig.sh.

Regarding a warning about the changes with the new default collection, I don't think it's a big deal because I think those collections are more-so suited for testing/development. 

Thoughts?

**Comment by lizziel** [comment]
Manually changing the settings for all collections in HISTORY.rc is a requirement in GC-Classic and it's a huge pain. It is in runConfig.sh for convenience. We could change auto-setting to off by default, and reduce/redesign the functionality, but I wouldn't want to see it deleted. If there is consensus to remove it, however, I could just have my own script to auto-update HISTORY for my test runs.

@sdeastham, any thoughts on this?

**Comment by LiamBindle** [comment]
In the GCST meeting today we discussed future handling of `HISTORY.rc` in `runConfig.sh`. In 13.4 the diagnostic auto-update will be turned off by default in `runConfig.sh`, but it will remain in runConfig.sh. That way it's still there for convenience but doesn't interfere with HISTORY.rc instructions.

(side note: I'll try to wrap this PR up today)

**Pull request merged**
