### PR TITLE
Add ModelE2.1 (GCAP 2.0) simulation to GCClassic integration tests

### PR DESCRIPTION
**Pull request by msulprizio**
### Name and Institution (Required)

Name: Melissa Sulprizio
Institution: Harvard

### Describe the update

We now run a 2x2.5 ModelE2.1 (aka GCAP 2.0) full-chemistry simulation in the GCClassic integration tests. Only one scenario (SSP2-4.5) is evaluated here simply to ensure these future scenario simulations compile and run for 1 hour successfully. I will defer to @ltmurray for guidance on whether additional simulations are needed.

The GCAP 2.0 integration test is passing off of 14.4.1, confirming that the fixes in https://github.com/geoschem/geos-chem/pull/2342 should have resolved the issues of GCAP 2.0 not working in 14.0.0 (as reported by Lee Murray at IGC11).

Sample integration test output:

```
==============================================================================
GEOS-Chem Classic: Execution Test Results

GCClassic #c49fcec Submod updates: Merge GEOS-Chem PR #2353 and Cloud-J PR #19
GEOS-Chem #7e4001658 Merge PR #2369 (Fix several issues with satellite diagnostics)
HEMCO     #2192e0e HEMCO 3.9.1 release

Using 24 OpenMP threads
Number of execution tests: 29

Submitted as SLURM job: 40462513
==============================================================================

Execution tests:
------------------------------------------------------------------------------
gc_05x0625_NA_47L_merra2_CH4........................Execute Simulation....PASS
gc_05x0625_NA_47L_merra2_fullchem...................Execute Simulation....PASS
gc_2x25_ModelE2.1_fullchem..........................Execute Simulation....PASS
```
### Expected changes

This is a zero difference update w/r/t the benchmark simulation.

### Reference(s)

If this is a science update, please provide a literature citation.

### CODE REVIEW

**Comment by msulprizio** [comment]
[Lee Murray commented](https://github.com/geoschem/geos-chem/commit/2c8910869728a58fdc5786dbdf08d1c145077fbc#commitcomment-144439777):

>Thanks, @msulprizio ! This should catch any issues that would affect any GCAP2.0 simulations using GCClassic, so no need for extra tests.

**Review by yantosca — APPROVED** [review]
Thanks @msulprizio!  Good to merge.  I'll start bringing this in.

**Comment by yantosca** [comment]
I merged this into dev/no-diff-to-benchmark (locally) and am running integration tests.  Stay tuned.

**Comment by yantosca** [comment]
@msulprizio: The ModelE2.1 integration test failed with:
```console
===============================================================================
GEOS-Chem ERROR: No diagnostic output will be created for collection: 
"Restart"!  Make sure that the length of the simulation as specified in 
geoschem_config.yml (check the start and end dates) is not shorter than the 
frequency setting in HISTORY.rc! For example, if the frequency is 010000 (1 
hour) but the simulation is set up to run for only 20 minutes, then this error 
will occur.
 -> at History_ReadCollectionData (in module History/history_mod.F90)

 -> ERROR occurred at (or near) line     78 of the HISTORY.rc file
===============================================================================

===============================================================================
GEOS-Chem ERROR: Error encountered in "History_ReadCollectionData"!
 -> at History_Init (in module History/history_mod.F90)
===============================================================================
```
Looks like we haven't set the HISTORY.rc properly.  I can look.

**Comment by yantosca** [comment]
@msulprizio: I have pushed a fix in 39df8a6 that also changes the duration of the HISTORY.rc from `00000100 000000` to `00000000 002000` so that the duration is consistent with the simulation length.  Now re-testing.

**Comment by yantosca** [comment]
@msulprizio: The fix in 39df8a6 works!
```console
gc_2x25_ModelE2.1_fullchem..........................Execute Simulation....PASS
```
I'll post the results of the integration tests one they finish and then will merge into the "no-diff-to-benchmark" branch.

**Comment by msulprizio** [comment]
Great. Thanks @yantosca!

**Comment by yantosca** [comment]
All GEOS-Chem Classic integration tests passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

GCClassic #da0c60f GCClassic 14.4.2 release
GEOS-Chem #38b5bfe0d Merge PR #2394 (Add int ModelE2.1 (GCAP 2.0) integration test)
HEMCO     #e68ebae HEMCO 3.9.2 release

Using 24 OpenMP threads
Number of execution tests: 29

Submitted as SLURM job: 41373626
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
All GCHP integration tests passed:
```console
==============================================================================
GCHP: Execution Test Results

GCHP      #8560108 GCHP 14.4.2 release
GEOS-Chem #38b5bfe0d Merge PR #2394 (Add int ModelE2.1 (GCAP 2.0) integration test)
HEMCO     #

Number of execution tests: 11

Submitted as SLURM job: 41373704
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
Also, all tests were zero-diff w/r/t 14.4.2.

**Pull request merged**
