### PR TITLE
[PULL REQUEST] Clean up heterogenous chemistry rate-law functions -- excluding sulfur chemistry updates to KPP

### PR DESCRIPTION
**Pull request by yantosca**
This PR will supersede #827.  This contains modifications for heterogenous chemistry reactions and rate law functions WITHOUT the sulfur chemistry modifications of Mike Long (as these need further testing & validation).  

Other chemistry updates will be added after this PR has been merged into dev.

Integration tests are pending.  I will report the results here.

### CODE REVIEW

**Comment by yantosca** [comment]
GEOS-Chem Classic integration tests all passed:
```
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 76
Execution tests failed: 0
Execution tests not yet completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Review by msulprizio — COMMENTED** [review]
I am reviewing these changes now. I see that `flexchem_mod.F90` is renamed to `fullchem_mod.F90`. I like this change, but I'm wondering if this means that for any new mechanism that we introduce we will also need to add a new module or routine to interface between GEOS-Chem and KPP?

**Comment by yantosca** [comment]
GCHP integration test results:
```
==============================================================================
GCHP: Execution Test Results

Number of execution tests: 3
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gchp_fullchem_benchmark_merra2_c48...............Execute Simulation.....PASS
gchp_fullchem_standard_merra2_c24................Execute Simulation.....PASS
gchp_TransportTracers_geosfp_c24.................Execute Simulation.....PASS
 
Summary of execution test results:
------------------------------------------------------------------------------
Execution tests passed:        3
Execution tests failed:        0
Execution tests not completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
> I am reviewing these changes now. I see that `flexchem_mod.F90` is renamed to `fullchem_mod.F90`. I like this change, but I'm wondering if this means that for any new mechanism that we introduce we will also need to add a new module or routine to interface between GEOS-Chem and KPP?

That was our idea.  For full-chemistry mechanisms we can link to fullchem mod (as eventually the aciduptake will be a new mechanism with dust aciduptake rxns handled by KPP).  For the Hg code, the interface between GEOS-Chem and the solver is done in mercury_mod.F90.   If we make a CO-CO2-CH4-OCS mechanism, then we'll need to write a new interface module because there wouldn't be the need to burden `fullchem_mod.F90` with that.

**Review by msulprizio — COMMENTED** [review]
Hi @yantosca. I finished reviewing the files. All changes look OK to me, but I had some comments and questions.

1. Is there a reason State_Chm%Do_SulfateMod_Seasalt and State_Chm%Do_SulfateMod_Cld are stored in State_Chm and not Input_Opt with other switches? It seems strange to have logical switches in State_Chm and set them there, but maybe it's fine since these are temporary?

2. What is the `Is_Forge` field added in species_mod.F90? It doesn't seem to be used.

3. I notice a new KPP mechanism for `aciduptake`. The `aciduptake.eqn` file appears to be identical to `fullchem.eqn` with the exception of additional reactions needed for acid uptake. We have been moving away from multiple full-chemistry mechanisms. Are there plans to eventually only include the relevant additional acid uptake reactions/species in this mechanism and then combine with the fullchem mechanism? The idea would be to avoid having to update reactions in multiple locations if a change is made anywhere in `fullchem.eqn`. Maybe it's fine to leave this unaddressed for now if it's not activated here, but I just wanted to jot down my thoughts.

4. There are some hardcoded paths (`/home/ilcentro/Work/Harvard/GC/v13/KPP/fullchem/...`) in many files in `KPP/fullchem/CMakeFiles/KPPFirstPass_fullchem.dir/`. These should be removed or made more flexible. If this is output produced by CMake, we should consider adding them to .gitignore.

6. There are also hardcoded paths to `/home/ilcentro/Work/Harvard/GC/v13` in `KPP/fullchem/Makefile`.

7. `KPP/fullchem/aciduptake_DustChemFuncs.F90` appears to be a stub. Is this a work in progress or still needed here?

8. In fullchem.eqn reaction HO2 = O2 is changed to HO2 = H2O. Is this a bug fix or science update? Are impacts from this change quantified?

**Comment by msulprizio** [comment]
@yantosca Could you also please link to the 1-month benchmark results here for record keeping and to confirm that changes from this update are mainly due to numerical noise?

**Comment by yantosca** [comment]
>     1. Is there a reason State_Chm%Do_SulfateMod_Seasalt and State_Chm%Do_SulfateMod_Cld are stored in State_Chm and not Input_Opt with other switches? It seems strange to have logical switches in State_Chm and set them there, but maybe it's fine since these are temporary?

These are temporary switches.  They could go into Input_Opt if you wish.  They won't be around forever, but right now we need them to tell the code to use sulfate_mod.F90 instead of KPP for certain reactions.
 
>     2. What is the `Is_Forge` field added in species_mod.F90? It doesn't seem to be used.

I have no idea.  Maybe Mike put that in.  I can take it out.

>     3. I notice a new KPP mechanism for `aciduptake`. The `aciduptake.eqn` file appears to be identical to `fullchem.eqn` with the exception of additional reactions needed for acid uptake. We have been moving away from multiple full-chemistry mechanisms. Are there plans to eventually only include the relevant additional acid uptake reactions/species in this mechanism and then combine with the fullchem mechanism? The idea would be to avoid having to update reactions in multiple locations if a change is made anywhere in `fullchem.eqn`. Maybe it's fine to leave this unaddressed for now if it's not activated here, but I just wanted to jot down my thoughts.

So eventually aciduptake will be a new chemical mechanism with dust uptake reactions handled by KPP.  This was done in order to avoid burdening the user with having all of the 12 extra dust uptake species in the standard "fullchem" mechanism.  The KPP/aciduptake folder is left for further development.  I can put a README.md file there to denote that.   Right now the aciduptake chemistry is handled by sulfate_mod.F90.

>     4. There are some hardcoded paths (`/home/ilcentro/Work/Harvard/GC/v13/KPP/fullchem/...`) in many files in `KPP/fullchem/CMakeFiles/KPPFirstPass_fullchem.dir/`. These should be removed or made more flexible. If this is output produced by CMake, we should consider adding them to .gitignore.

Yeah, that should probably not be there.  It might be a CMake-generated file.  I'll take a look.

>     5. There are also hardcoded paths to `/home/ilcentro/Work/Harvard/GC/v13` in `KPP/fullchem/Makefile`.

I'll delete that.

>     6. `KPP/fullchem/aciduptake_DustChemFuncs.F90` appears to be a stub. Is this a work in progress or still needed here?

That is a stub module that is needed to get the code to compile, since both the fullchem and aciduptake KPP code will share fullchem_mod.F90.

>     7. In fullchem.eqn reaction HO2 = O2 is changed to HO2 = H2O. Is this a bug fix or science update? Are impacts from this change quantified?

Daniel told me to do that.  That had been a long-standing typo.  I believe the impacts are not large.

**Comment by msulprizio** [comment]
> > 1. Is there a reason State_Chm%Do_SulfateMod_Seasalt and State_Chm%Do_SulfateMod_Cld are stored in State_Chm and not Input_Opt with other switches? It seems strange to have logical switches in State_Chm and set them there, but maybe it's fine since these are temporary?
> 
> These are temporary switches. They could go into Input_Opt if you wish. They won't be around forever, but right now we need them to tell the code to use sulfate_mod.F90 instead of KPP for certain reactions.
> 

I'm fine with leaving as-is since they are temporary. I suppose they should not be easily toggled since users aren't meant to use those options right now.

> > 1. What is the `Is_Forge` field added in species_mod.F90? It doesn't seem to be used.
> 
> I have no idea. Maybe Mike put that in. I can take it out.
>

Thanks!

> > 1. I notice a new KPP mechanism for `aciduptake`. The `aciduptake.eqn` file appears to be identical to `fullchem.eqn` with the exception of additional reactions needed for acid uptake. We have been moving away from multiple full-chemistry mechanisms. Are there plans to eventually only include the relevant additional acid uptake reactions/species in this mechanism and then combine with the fullchem mechanism? The idea would be to avoid having to update reactions in multiple locations if a change is made anywhere in `fullchem.eqn`. Maybe it's fine to leave this unaddressed for now if it's not activated here, but I just wanted to jot down my thoughts.
> 
> So eventually aciduptake will be a new chemical mechanism with dust uptake reactions handled by KPP. This was done in order to avoid burdening the user with having all of the 12 extra dust uptake species in the standard "fullchem" mechanism. The KPP/aciduptake folder is left for further development. I can put a README.md file there to denote that. Right now the aciduptake chemistry is handled by sulfate_mod.F90.

OK. Sounds good. Perhaps we can discuss and clean it up / consolidate later, but getting it working for now is fine.

> > 1. There are some hardcoded paths (`/home/ilcentro/Work/Harvard/GC/v13/KPP/fullchem/...`) in many files in `KPP/fullchem/CMakeFiles/KPPFirstPass_fullchem.dir/`. These should be removed or made more flexible. If this is output produced by CMake, we should consider adding them to .gitignore.
> 
> Yeah, that should probably not be there. It might be a CMake-generated file. I'll take a look.

Thanks!

> > 1. There are also hardcoded paths to `/home/ilcentro/Work/Harvard/GC/v13` in `KPP/fullchem/Makefile`.
> 
> I'll delete that.

Thanks!

> > 1. `KPP/fullchem/aciduptake_DustChemFuncs.F90` appears to be a stub. Is this a work in progress or still needed here?
> 
> That is a stub module that is needed to get the code to compile, since both the fullchem and aciduptake KPP code will share fullchem_mod.F90.

Sounds good.

> > 1. In fullchem.eqn reaction HO2 = O2 is changed to HO2 = H2O. Is this a bug fix or science update? Are impacts from this change quantified?
> 
> Daniel told me to do that. That had been a long-standing typo. I believe the impacts are not large.

OK. Thanks for confirming.

@yantosca After you make the minor changes indicated above, please feel free to merge into `dev`. We can tag with `13.3.0-alpha.1` and I can run GCClassic and GCHP internal benchmarks over the weekend (or early next week if needed).

**Pull request merged**
