### PR TITLE
Updates from NASA GMAO

### PR DESCRIPTION
**Pull request by lizziel**
### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### Describe the update

This pull request brings in updates developed for GEOS-Chem within the NASA GEOS model. Contributors include Christoph Keller (@christophkeller) and Viral Shah (@viral211).

### Expected changes

This is a zero diff update for offline GEOS-Chem, including both GC-Classic and GCHP.

### Reference(s)

None

### Related Github Issue(s)

None

### CODE REVIEW

**Comment by lizziel** [comment]
GC-Classic and GCHP integration tests pass and diff tests show zero diff.

**Review by msulprizio — APPROVED** [review]
Thanks @lizziel. These updates look good to merge.

**Comment by yantosca** [comment]
All GEOS-Chem Classic integration tests passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

GCClassic #ce9777e HEMCO submod update: Merge PR #274 (Use "stale" GitHub action)
GEOS-Chem #c87160743 Merge PR #2249 (Updates from NASA GMAO)
HEMCO     #d3fae96 Merge PR #274 (Replace stalebot with "stale" GitHub action)

Using 24 OpenMP threads
Number of execution tests: 29

Submitted as SLURM job: 29614869
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
All tests were identical to PR #2261, except:
- TOMAS (1 difference in restart file)
- APM (known parallelization issue)
- RRTMG (numerical noise in RRTMG collection)

**Comment by yantosca** [comment]
All GCHP integration tests passed:
```console
==============================================================================
GCHP: Execution Test Results

GCHP      #44d1dd1 HEMCO submod update: Merge PR #274 (Use "stale" GitHub action)
GEOS-Chem #c87160743 Merge PR #2249 (Updates from NASA GMAO)
HEMCO     #d3fae96 Merge PR #274 (Replace stalebot with "stale" GitHub action)

Number of execution tests: 11

Submitted as SLURM job: 29614914
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
Also all tests were zero-diff w/r/t PR #2261.

**Comment by yantosca** [comment]
All GEOS-Chem Classic integration tests passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

GCClassic #ce9777e HEMCO submod update: Merge PR #274 (Use "stale" GitHub action)
GEOS-Chem #c87160743 Merge PR #2249 (Updates from NASA GMAO)
HEMCO     #d3fae96 Merge PR #274 (Replace stalebot with "stale" GitHub action)

Using 24 OpenMP threads
Number of execution tests: 29

Submitted as SLURM job: 29614869
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
All tests were zero-diff to PR #2249, except:
- TOMAS (1 difference in restart file)
- APM (known parallelization issue)
- RRTMG (numerical noise in RRTMG collection)

**Pull request merged**
