### PR TITLE
Remove NcdfUtil/perl folder

### PR DESCRIPTION
**Pull request by yantosca**
This PR does the following:

1. Removes the `NcdfUtil/perl` folder, which contained copies of `isCoards`, `nc_chunk.pl`, as well as some obsolete netCDF scripts.  Now that we have created the new https://github.com/geoschem/netcdf-scripts folder, we no longer need to keep these scripts within the GEOS-Chem code.  GEOS-Chem users should look to the netcdf-scripts repo for the most recent versions of netCDF utility scripts.

2. Adds a `NcdfUtil/README.md` file.

### CODE REVIEW

**Comment by yantosca** [comment]
See companion HEMCO PR #183

**Comment by yantosca** [comment]
Integration tests in progress

**Comment by yantosca** [comment]
I have brought this up to 14.0.0-rc.0.  Integration tests are pending.

**Comment by yantosca** [comment]
All GCHP integration tests pass:
```console
==============================================================================
GCHP: Execution Test Results

Number of execution tests: 3
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gchp_fullchem_benchmark_merra2_c48...............Execute Simulation.....PASS
gchp_fullchem_standard_merra2_c24................Execute Simulation.....PASS
gchp_TransportTracers_geosfp_c24.................Execute Simulation.....PASS
 
Summary of execution test results:
------------------------------------------------------------------------------
Execution tests passed:        3
Execution tests failed:        0
Execution tests not completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
I have brought this PR up to 14.1.0-rc.1 and have resubmitted the integration tests.  All GEOS-Chem Classic integration test passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

Using 24 OpenMP threads
Number of execution tests: 51
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gc_025x03125_CH4_geosfp_47L_na......................Execute Simulation....PASS
gc_025x03125_fullchem_geosfp_47L_na.................Execute Simulation....PASS
gc_05x0625_CH4_merra2_47L_na........................Execute Simulation....PASS
gc_05x0625_fullchem_merra2_47L_na...................Execute Simulation....PASS
gc_2x25_aerosol_merra2..............................Execute Simulation....PASS
gc_2x25_carbon_merra2...............................Execute Simulation....PASS
gc_2x25_CH4_merra2..................................Execute Simulation....PASS
gc_2x25_CO2_merra2..................................Execute Simulation....PASS
gc_2x25_fullchem_merra2.............................Execute Simulation....PASS
gc_2x25_Hg_merra2...................................Execute Simulation....PASS
gc_2x25_metals_merra2...............................Execute Simulation....PASS
gc_2x25_POPs_BaP_merra2.............................Execute Simulation....PASS
gc_2x25_tagCH4_merra2...............................Execute Simulation....PASS
gc_2x25_tagCO_merra2................................Execute Simulation....PASS
gc_2x25_tagO3_merra2................................Execute Simulation....PASS
gc_2x25_TransportTracers_merra2.....................Execute Simulation....PASS
gc_2x25_TransportTracers_merra2_LuoWd...............Execute Simulation....PASS
gc_4x5_aerosol_geosfp...............................Execute Simulation....PASS
gc_4x5_aerosol_merra2...............................Execute Simulation....PASS
gc_4x5_carbon_geosfp................................Execute Simulation....PASS
gc_4x5_carbon_merra2................................Execute Simulation....PASS
gc_4x5_CH4_geosfp...................................Execute Simulation....PASS
gc_4x5_CH4_merra2...................................Execute Simulation....PASS
gc_4x5_fullchem_aciduptake_merra2...................Execute Simulation....PASS
gc_4x5_fullchem_APM_merra2..........................Execute Simulation....PASS
gc_4x5_fullchem_benchmark_merra2....................Execute Simulation....PASS
gc_4x5_fullchem_complexSOA_merra2...................Execute Simulation....PASS
gc_4x5_fullchem_complexSOA_SVPOA_merra2.............Execute Simulation....PASS
gc_4x5_fullchem_geosfp..............................Execute Simulation....PASS
gc_4x5_fullchem_marinePOA_merra2....................Execute Simulation....PASS
gc_4x5_fullchem_merra2..............................Execute Simulation....PASS
gc_4x5_fullchem_merra2_47L..........................Execute Simulation....PASS
gc_4x5_fullchem_merra2_LuoWd........................Execute Simulation....PASS
gc_4x5_fullchem_RRTMG_merra2........................Execute Simulation....PASS
gc_4x5_fullchem_TOMAS15_merra2_47L..................Execute Simulation....PASS
gc_4x5_fullchem_TOMAS40_merra2_47L..................Execute Simulation....PASS
gc_4x5_Hg_geosfp....................................Execute Simulation....PASS
gc_4x5_Hg_merra2....................................Execute Simulation....PASS
gc_4x5_metals_merra2................................Execute Simulation....PASS
gc_4x5_POPs_BaP_geosfp..............................Execute Simulation....PASS
gc_4x5_POPs_BaP_merra2..............................Execute Simulation....PASS
gc_4x5_tagCH4_geosfp................................Execute Simulation....PASS
gc_4x5_tagCH4_merra2................................Execute Simulation....PASS
gc_4x5_tagCO_geosfp.................................Execute Simulation....PASS
gc_4x5_tagCO_merra2.................................Execute Simulation....PASS
gc_4x5_tagO3_geosfp.................................Execute Simulation....PASS
gc_4x5_tagO3_merra2.................................Execute Simulation....PASS
gc_4x5_TransportTracers_geosfp......................Execute Simulation....PASS
gc_4x5_TransportTracers_geosfp_LuoWd................Execute Simulation....PASS
gc_4x5_TransportTracers_merra2......................Execute Simulation....PASS
gc_4x5_TransportTracers_merra2_LuoWd................Execute Simulation....PASS
 
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 51
Execution tests failed: 0
Execution tests not yet completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

As did all of the GCHP integration tests:
```console
==============================================================================
GCHP: Execution Test Results

Number of execution tests: 3
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gchp_fullchem_benchmark_merra2_c48...............Execute Simulation.....PASS
gchp_fullchem_standard_merra2_c24................Execute Simulation.....PASS
gchp_TransportTracers_geosfp_c24.................Execute Simulation.....PASS
 
Summary of execution test results:
------------------------------------------------------------------------------
Execution tests passed:        3
Execution tests failed:        0
Execution tests not completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
@msulprizio: Since we have already merged the logfile updates into GC and HEMCO, I think it's OK if this PR goes into GEOS-Chem 14.2.0 and HEMCO 3.7.0.  Otherwise I'd have to make a HEMCO 3.6.1 version.

**Review by msulprizio — APPROVED** [review]
This is a straightforward PR removing the `NcdfUtil/perl` directory and adding a `NcdfUtil/README.md` file. Good to merge.

**Pull request merged**
