### PR TITLE
Fix bugs in PDER, OCPISOA and TotalOC in complexSOA

### PR DESCRIPTION
**Pull request by yuanjianz**
### Name and Institution (Required)

Name: Yuanjian Zhang
Institution: WashU

### Describe the update

```console
SimpleSOA:           OCPISOA = OCPI*OCFOPOA + SOAS 
ComplexSOA_nonSVPOA: OCPISOA = OCPI*OCFOPOA + TSOA + ASOA + ISOAAQ
ComplexSOA_SVPOA:    OCPISOA = OPOA + TSOA + ASOA + ISOAAQ
```
- Simplify verbose calculations.
- Use OCPISOA+OCPO in dry effective radius calculation instead of summing up each species.
- Use OCPISOA+OCPO for TotalOA, enabling TotalOA diagnostic for SimpleSOA.
- Match TotalOC calculation consistent with aerosol_mod.F90.

### Expected changes

- Parameterized dry effective radius for SNA and OM will correctly handle SVPOA scenario (OCPI replaced by OPOA).
- ~This update should be no-diff-to-benchmark since SVPOA is not activated in benchmark simulation.~
- OCPISOA in benchmark(both simpleSOA and complexSOA are activated) will no longer double count ISOAAQ as was in PM2.5 before.
- TotalOC will no longer omit TSOA, ASOA, OCPI and OCPO in complexSOA_nonSVPOA (benchmark falls into this).

### Reference(s)

Tagging @Haihui-Zhu for confirmation about the PDER update.

### Related Github Issue
#2314
#2321

### CODE REVIEW

**Comment by Haihui-Zhu** [comment]
I reviewed this revision and didn't notice any issues. The parameterized effective radius is calculated correctly using more concise code.

**Comment by yantosca** [comment]
Thanks @yuanjianz and @Haihui-Zhu.  I will try to look at this as soon as possible.  We can get this into our 14.5.0 development stream.

**Comment by yuanjianz** [comment]
Note this pull request is no longer no-diff-to-benchmark.
1. OCPISOA in benchmark(both simpleSOA and complexSOA are activated) will no longer double count ISOAAQ as were in PM2.5 before.
2. TotalOC will no longer omit TSOA, ASOA, OCPI and OCPO in complexSOA_nonSVPOA (benchmark falls into this).

**Comment by yantosca** [comment]
Thanks @yuanjianz.  I'll take a look at this.

**Review by yantosca — CHANGES_REQUESTED** [review]
Thanks @yuanjianz and @Haihui-Zhu.  This looks very good and I think it will simplify the computations (as well as being more efficient).

Would you be able to update the CHANGELOG.md file with a sentence about this update?  Once that's done we can proceed to merging & testing.  Thanks!

**Review by yantosca — APPROVED** [review]

**Comment by yantosca** [comment]
All GEOS-Chem integration tests passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

GCClassic #600ce53 GEOS-Chem submod update: Merge hotfix from PR #2363 atop PR #2359
GEOS-Chem #eabf06c88 Update setCommonRunSettings.sh.template
HEMCO     #2192e0e HEMCO 3.9.1 release

Using 24 OpenMP threads
Number of execution tests: 28

Submitted as SLURM job: 40084006
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\
```

**Comment by yantosca** [comment]
All GCHP integration tests passed as well:
```console
==============================================================================
GCHP: Execution Test Results

GCHP      #7065c1c GEOS-Chem submod update: Merge hotfix from PR #2363 atop PR #2359
GEOS-Chem #eabf06c88 Update setCommonRunSettings.sh.template
HEMCO     #

Number of execution tests: 11

Submitted as SLURM job: 40086511
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Pull request merged**
