### PR TITLE
Bug fix for TOMAS sulfate production rates

### PR DESCRIPTION
**Pull request by BettyCroft**
These updates are a bug fix for TOMAS sulfate production rates as discussed in issue #1511. With the migration of sulfate chemistry to KPP, TOMAS does not have the correct sulfate production rates in v14. Primary updates are to KPP/fullchem/fullchem.eqn and GeosCore/fullchem_mod.F90 and tomas_mod.F90. Two new species are added in fullchem.eqn PSO4AQ and PH2SO4 and KPP was rebuilt. These species are not in the GC restart file - so replace EFYO with CYS for the SPC_ in HEMCO_COnfig.rc for the simulation to run.

### CODE REVIEW

**Comment by BettyCroft** [comment]
Hi @msulprizio - these updates are ready to be implemented as is. This fix is an important one to enable TOMAS to run correctly with the in-cloud sulfate chemistry migrated into KPP. Can you assist with this update and can we add a never stale label?

**Comment by msulprizio** [comment]
@BettyCroft Sure thing. We plan to implement this shortly after 14.1.0 is released -- it's in the benchmark stages now.

**Comment by BettyCroft** [comment]
Thanks @msulprizio!

**Review by msulprizio — APPROVED** [review]
These updates will impact TOMAS only. Looks good to merge.

**Comment by BettyCroft** [comment]
Thank you @msulprizio !

**Pull request merged**
