### PR TITLE
Rename tags in geoschem_config.yml for nitrate aerosol photolysis as per GCSC suggestion

### PR DESCRIPTION
**Pull request by yantosca**
### Name and Institution (Required)

Name: Bob Yantosca
Institution: Harvard + GCST

### Confirm you have reviewed the following documentation

- [x] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/reference/CONTRIBUTING.html)

### Describe the update
This is the companion PR to #1968.  We have renamed the YAML tags in `geoschem_config.yml` from:

```yaml
    photolyze_nitrate_aerosol:
      activate: true
      NITs_Jscale_JHNO3: 100.0
      NIT_Jscale_JHNO2: 100.0
```
to
```yaml
    photolyze_nitrate_aerosol:
      activate: true
      NITs_Jscale: 100.0
      NIT_Jscale: 100.0
```
as per discussion at the 19 Sep 2023 GEOS-Chem Steering Committee meeting.

### Expected changes
This should be a zero-diff update.  It can go into the next feature version, because it changes the `geoschem_config.yml` run directory configuration file.

### Reference(s)
N/A

### Related Github Issue(s)

- #1968

### CODE REVIEW

**Comment by yantosca** [comment]
All GEOS-Chem Classic integration tests except TOMAS passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

GCClassic #ad68c48 GEOS-Chem 14.2.1 and HEMCO 3.7.1 release
GEOS-Chem #15701ee41 Rename tags in geoschem_config.yml for nitrate aerosol photolysis
HEMCO     #00aaf65 Update HEMCO 3.7.1 release date in CHANGELOG.md

Using 24 OpenMP threads
Number of execution tests: 27

Submitted as SLURM job: 5205266
==============================================================================
 
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 25
Execution tests failed: 2
Execution tests not yet completed: 0
```
Also, all integration tests were zero-diff w/r/t 14.2.1 except for APM and RRTMG (diagnostic output only), which have known parallelization issues.

**Comment by yantosca** [comment]
All GCHP integration tests passed:
```console
==============================================================================
GCHP: Execution Test Results

GCClassic #6413378 GEOS-Chem/GCHP 14.2.1 and HEMCO 3.7.1 release
GEOS-Chem #15701ee41 Rename tags in geoschem_config.yml for nitrate aerosol photolysis
HEMCO     #00aaf65 Update HEMCO 3.7.1 release date in CHANGELOG.md

Number of execution tests: 5

Submitted as SLURM job: 5206314
==============================================================================
 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Review by msulprizio — APPROVED** [review]
This is a straightforward update renaming `NITs_Jscale_JHNO3` to `NITs_Jscale` and `NIT_Jscale_JHNO2` to `NIT_Jscale`. Good to merge.

**Comment by yantosca** [comment]
All GEOS-Chem Classic integration tests passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

GCClassic #f261845 GEOS-Chem submodule update: Merge PR #1979 (Updated NOAA GMD surface BCs)
GEOS-Chem #800db9974 Bring PR #1998 on top of 14.4.0-alpha.3 (PR #1979)
HEMCO     #f807e1a Update HEMCO version number to 3.8.0 in preparation for release

Using 24 OpenMP threads
Number of execution tests: 26

Submitted as SLURM job: 21726783
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
All GCHP integration tests passed:
```console
==============================================================================
GCHP: Execution Test Results

GCHP      #2e516f8 GEOS-Chem submodule update: Merge PR #1979 (Updated NOAA GMD surface BCs)
GEOS-Chem #800db9974 Bring PR #1998 on top of 14.4.0-alpha.3 (PR #1979)
HEMCO     #f807e1a Update HEMCO version number to 3.8.0 in preparation for release

Number of execution tests: 6

Submitted as SLURM job: 21727499
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Pull request merged**
