### PR TITLE
Now use consistent behavior when the first call to "Integrate" fails

### LINKED ISSUE #1606: [FEATURE REQUEST] Add consistent behavior for failed integrations in fullchem_mod.F90
I've noticed some inconsistent behavior (and possibly an error) for the block where the integration fails in fullchem_mod.F90:

```F90
       !=====================================================================
       ! Try another time if it failed
       !=====================================================================
       IF ( IERR < 0 ) THEN

#if defined( MODEL_GEOS ) || defined( MODEL_WRF )
          ! Save a copy of the C vector (GEOS and WRF only)
          localC    = C
#endif

          ! Reset first time step and start concentrations
          ! Retry the integration with non-optimized settings
          RCNTRL(3) = 0.0_dp
          C         = 0.0_dp

          ! Disable auto-reduce solver for the second iteration for safety
          IF ( Input_Opt%Use_AutoReduce ) THEN
             RCNTRL(12) = -1.0_dp ! without using ICNTRL
          ENDIF

          ! Update rates again
          CALL Update_RCONST( )

          ! Start timer
          IF ( Input_Opt%useTimers ) THEN
             CALL Timer_Start( TimerName = "     Integrate 2",               &
                               InLoop    =  .TRUE.,                          &
                               ThreadNum = Thread,                           &
                               RC        = RC                               )
          ENDIF

          ! Integrate again
          CALL Integrate( TIN,    TOUT,    ICNTRL,                           &
                          RCNTRL, ISTATUS, RSTATE, IERR                     )

          ! Stop timer
          IF ( Input_Opt%useTimers ) THEN
             CALL Timer_End( TimerName = "     Integrate 2",                 &
                             InLoop    =  .TRUE.,                            &
                             ThreadNum = Thread,                             &
                             RC        = RC                                 )
          ENDIF
```
In particular:
1. For GEOS and WRF, a `localC` array is defined to store the values of C (but not for CLASSIC or GCHP)
2. The `C` array is zeroed out instead of being reset to pre-chemistry concentrations.'

I would recommend adding this change:

```F90
       !=====================================================================
       ! Initialize the KPP "C" vector of species concentrations [molec/cm3]
       !=====================================================================
       DO N = 1, NSPEC
          SpcID = State_Chm%Map_KppSpc(N)
          C(N)  = 0.0_dp
          IF ( SpcId > 0 ) C(N) = State_Chm%Species(SpcID)%Conc(I,J,L)
       ENDDO
    
       ! Store pre-chemistry values in a vector
       C_pre_chem = C

       ...

       IF ( IERR < 0 ) THEN
   

          ! Reset first time step and start concentrations
          ! Retry the integration with non-optimized settings
          RCNTRL(3) = 0.0_dp
   
          ! Reset concentrations to pre-chemistry values
          C         = C_pre_Chem

          ...
```
Thoughts?  Would this mess anything up for GEOS or WRF?

@msulprizio @lizziel @Jourdan-He @SaptSinha @christophkeller @jimmielin

### PR DESCRIPTION
**Pull request by yantosca**
This is the companion PR to #1606.  We copy the values of KPP concentration vector `C` into the `C_before_integrate` vector (in `GeosCore/fullchem_mod.F90` and `GeosCore/mercury_mod.F90`) before the first call to `Integrate`.  

If the first call to `Integrate` fails, then we reset the `C` vector with the values from `C_before_integrate` and then call `Integrate` a second time.  This is done regardless of which context in which you are running GEOS-Chem (i.e. GC-Classic, GCHP, GEOS, WRF, etc.)

This also fixes an error where the `C` array had previously been zeroed before the 2nd call to `Integrate`.  This should not have been done.

Integration tests are running.  A parallelization test with 8 cores and 5 cores passed.

Closes #1606

### CODE REVIEW

**Comment by yantosca** [comment]
GEOS-Chem Classic integration tests all pass:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

Using 24 OpenMP threads
Number of execution tests: 48
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gc_025x03125_CH4_geosfp_47L_na...................Execute Simulation.....PASS
gc_025x03125_fullchem_geosfp_47L_na..............Execute Simulation.....PASS
gc_05x0625_CH4_merra2_47L_na.....................Execute Simulation.....PASS
gc_05x0625_fullchem_merra2_47L_na................Execute Simulation.....PASS
gc_2x25_aerosol_merra2...........................Execute Simulation.....PASS
gc_2x25_CH4_merra2...............................Execute Simulation.....PASS
gc_2x25_CO2_merra2...............................Execute Simulation.....PASS
gc_2x25_fullchem_merra2..........................Execute Simulation.....PASS
gc_2x25_Hg_merra2................................Execute Simulation.....PASS
gc_2x25_metals_merra2............................Execute Simulation.....PASS
gc_2x25_POPs_BaP_merra2..........................Execute Simulation.....PASS
gc_2x25_tagCH4_merra2............................Execute Simulation.....PASS
gc_2x25_tagCO_merra2.............................Execute Simulation.....PASS
gc_2x25_tagO3_merra2.............................Execute Simulation.....PASS
gc_2x25_TransportTracers_merra2..................Execute Simulation.....PASS
gc_2x25_TransportTracers_merra2_LuoWd............Execute Simulation.....PASS
gc_4x5_aerosol_geosfp............................Execute Simulation.....PASS
gc_4x5_aerosol_merra2............................Execute Simulation.....PASS
gc_4x5_CH4_geosfp................................Execute Simulation.....PASS
gc_4x5_CH4_merra2................................Execute Simulation.....PASS
gc_4x5_fullchem_aciduptake_merra2................Execute Simulation.....PASS
gc_4x5_fullchem_APM_merra2.......................Execute Simulation.....PASS
gc_4x5_fullchem_benchmark_merra2.................Execute Simulation.....PASS
gc_4x5_fullchem_complexSOA_merra2................Execute Simulation.....PASS
gc_4x5_fullchem_complexSOA_SVPOA_merra2..........Execute Simulation.....PASS
gc_4x5_fullchem_geosfp...........................Execute Simulation.....PASS
gc_4x5_fullchem_marinePOA_merra2.................Execute Simulation.....PASS
gc_4x5_fullchem_merra2...........................Execute Simulation.....PASS
gc_4x5_fullchem_merra2_47L.......................Execute Simulation.....PASS
gc_4x5_fullchem_merra2_LuoWd.....................Execute Simulation.....PASS
gc_4x5_fullchem_RRTMG_merra2.....................Execute Simulation.....PASS
gc_4x5_fullchem_TOMAS15_merra2_47L...............Execute Simulation.....PASS
gc_4x5_fullchem_TOMAS40_merra2_47L...............Execute Simulation.....PASS
gc_4x5_Hg_geosfp.................................Execute Simulation.....PASS
gc_4x5_Hg_merra2.................................Execute Simulation.....PASS
gc_4x5_metals_merra2.............................Execute Simulation.....PASS
gc_4x5_POPs_BaP_geosfp...........................Execute Simulation.....PASS
gc_4x5_POPs_BaP_merra2...........................Execute Simulation.....PASS
gc_4x5_tagCH4_geosfp.............................Execute Simulation.....PASS
gc_4x5_tagCH4_merra2.............................Execute Simulation.....PASS
gc_4x5_tagCO_geosfp..............................Execute Simulation.....PASS
gc_4x5_tagCO_merra2..............................Execute Simulation.....PASS
gc_4x5_tagO3_geosfp..............................Execute Simulation.....PASS
gc_4x5_tagO3_merra2..............................Execute Simulation.....PASS
gc_4x5_TransportTracers_geosfp...................Execute Simulation.....PASS
gc_4x5_TransportTracers_geosfp_LuoWd.............Execute Simulation.....PASS
gc_4x5_TransportTracers_merra2...................Execute Simulation.....PASS
gc_4x5_TransportTracers_merra2_LuoWd.............Execute Simulation.....PASS
 
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 48
Execution tests failed: 0
Execution tests not yet completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
All GCHP integration tests passed:
```console
==============================================================================
GCHP: Execution Test Results

Number of execution tests: 3
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gchp_fullchem_benchmark_merra2_c48...............Execute Simulation.....PASS
gchp_fullchem_standard_merra2_c24................Execute Simulation.....PASS
gchp_TransportTracers_geosfp_c24.................Execute Simulation.....PASS
 
Summary of execution test results:
------------------------------------------------------------------------------
Execution tests passed:        3
Execution tests failed:        0
Execution tests not completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
I have merged this development stream up to 14.1.0-rc.1, and am running new integration tests.

**Comment by msulprizio** [comment]
@yantosca What is the status of this pull request? Is it still a draft? Should it be included in 14.2.0?

**Comment by yantosca** [comment]
@msulprizio, thanks for the reminder. I think it is OK for review.  I'll mark it as such and set up new integration tests.

**Comment by yantosca** [comment]
I have merged this up to 14.2.0-alpha.3 and also put in a trap to prevent displaying KPP integrate error messages after the first 20 messages happen (to avoid cluttering up log files).  Will rerun integration tests

**Review by msulprizio — APPROVED** [review]
These changes look good to merge

**Review by msulprizio — CHANGES_REQUESTED** [review]
@yantosca I just realized CHANGELOG.md hasn't been updated for these updates. Could you add that before I merge?

**Comment by yantosca** [comment]
Integration tests passed except for the `gc_05x0625_merra2_fullchem_NA`, which will be fixed by #1706. 
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

GCClassic #b9a7772 GEOS-Chem submodule update: Turn SSA debromination on
GEOS-Chem #e6c7b8987 Fix bugs in suppression of KPP integration error messages
HEMCO     #a4f8517 Merge PR #189 (branch 'feature/add-lumped-furans') into dev/3.7.0

Using 24 OpenMP threads
Number of execution tests: 26

Submitted as SLURM job: 46343592
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gc_05x0625_NA_47L_merra2_CH4........................Execute Simulation....PASS
gc_05x0625_NA_47L_merra2_fullchem...................Execute Simulation....FAIL
gc_4x5_47L_merra2_fullchem..........................Execute Simulation....PASS
gc_4x5_47L_merra2_fullchem_TOMAS15..................Execute Simulation....PASS
gc_4x5_47L_merra2_fullchem_TOMAS40..................Execute Simulation....PASS
gc_4x5_merra2_aerosol...............................Execute Simulation....PASS
gc_4x5_merra2_carbon................................Execute Simulation....PASS
gc_4x5_merra2_CH4...................................Execute Simulation....PASS
gc_4x5_merra2_CO2...................................Execute Simulation....PASS
gc_4x5_merra2_fullchem..............................Execute Simulation....PASS
gc_4x5_merra2_fullchem_aciduptake...................Execute Simulation....PASS
gc_4x5_merra2_fullchem_APM..........................Execute Simulation....PASS
gc_4x5_merra2_fullchem_benchmark....................Execute Simulation....PASS
gc_4x5_merra2_fullchem_complexSOA...................Execute Simulation....PASS
gc_4x5_merra2_fullchem_complexSOA_SVPOA.............Execute Simulation....PASS
gc_4x5_merra2_fullchem_LuoWd........................Execute Simulation....PASS
gc_4x5_merra2_fullchem_marinePOA....................Execute Simulation....PASS
gc_4x5_merra2_fullchem_RRTMG........................Execute Simulation....PASS
gc_4x5_merra2_Hg....................................Execute Simulation....PASS
gc_4x5_merra2_metals................................Execute Simulation....PASS
gc_4x5_merra2_POPs_BaP..............................Execute Simulation....PASS
gc_4x5_merra2_tagCH4................................Execute Simulation....PASS
gc_4x5_merra2_tagCO.................................Execute Simulation....PASS
gc_4x5_merra2_tagO3.................................Execute Simulation....PASS
gc_4x5_merra2_TransportTracers......................Execute Simulation....PASS
gc_4x5_merra2_TransportTracers_LuoWd................Execute Simulation....PASS
 
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 25
Execution tests failed: 1
Execution tests not yet completed: 0
```

**Review by msulprizio — APPROVED** [review]

**Pull request merged**
