### PR TITLE
KPP 3.0.0 with auto-reduction solver

### PR DESCRIPTION
**Pull request by yantosca**
This PR now supersedes #1411.  @lizziel has added some updates for compiling in the NASA GEOS ESM on top of what was originally in #1411.

### CODE REVIEW

**Comment by yantosca** [comment]
also tagging @jimmielin

**Comment by yantosca** [comment]
Also I have rebuilt the fullchem and Hg mechanisms with KPP 3.0.0-rc.3, which is the latest version.  KPP 3.0.0 will be released with Lin et al 2022.

**Comment by yantosca** [comment]
Integration tests running.

**Comment by jimmielin** [comment]
Thanks @yantosca! Please let me know if there are any questions about the code.

**Comment by yantosca** [comment]
Note: the Hg simulation is failing with these compile errors:

```console
 1191 |              State_Diag%KppcNONZERO(I,J,L) = cNONZERO
      |                                                     1
Error: Symbol ‘cnonzero’ at (1) has no IMPLICIT type; did you mean ‘nonzero’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:466:33:

  466 |            keepSpcActive(ind_AERI )      = .true.  ! Iodine on aerosol
      |                                 1
Error: Symbol ‘ind_aeri’ at (1) has no IMPLICIT type; did you mean ‘ind_br’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:468:32:

  468 |            keepSpcActive(ind_Br2 )       = .true.
      |                                1
Error: Symbol ‘ind_br2’ at (1) has no IMPLICIT type; did you mean ‘ind_br’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:469:33:

  469 |            keepSpcActive(ind_BrCl)       = .true.
      |                                 1
Error: Symbol ‘ind_brcl’ at (1) has no IMPLICIT type; did you mean ‘ind_br’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:470:34:

  470 |            keepSpcActive(ind_BrNO2)      = .true.
      |                                  1
Error: Symbol ‘ind_brno2’ at (1) has no IMPLICIT type; did you mean ‘ind_bro’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:471:34:

  471 |            keepSpcActive(ind_BrNO3)      = .true.
      |                                  1
Error: Symbol ‘ind_brno3’ at (1) has no IMPLICIT type; did you mean ‘ind_bro’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:473:35:

  473 |            keepSpcActive(ind_BrSALA)     = .true.
      |                                   1
Error: Symbol ‘ind_brsala’ at (1) has no IMPLICIT type; did you mean ‘ind_br’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:474:35:

  474 |            keepSpcActive(ind_BrSALC)     = .true.
      |                                   1
Error: Symbol ‘ind_brsalc’ at (1) has no IMPLICIT type; did you mean ‘ind_br’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:478:32:

  478 |            keepSpcActive(ind_Cl2)        = .true.
      |                                1
Error: Symbol ‘ind_cl2’ at (1) has no IMPLICIT type; did you mean ‘ind_cl’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:479:34:

  479 |            keepSpcActive(ind_Cl2O2)      = .true.
      |                                  1
Error: Symbol ‘ind_cl2o2’ at (1) has no IMPLICIT type; did you mean ‘ind_clo’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:480:34:

  480 |            keepSpcActive(ind_ClNO2)      = .true.
      |                                  1
Error: Symbol ‘ind_clno2’ at (1) has no IMPLICIT type; did you mean ‘ind_clo’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:481:34:

  481 |            keepSpcActive(ind_ClNO3)      = .true.
      |                                  1
Error: Symbol ‘ind_clno3’ at (1) has no IMPLICIT type; did you mean ‘ind_clo’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:483:33:

  483 |            keepSpcActive(ind_ClOO)       = .true.
      |                                 1
Error: Symbol ‘ind_cloo’ at (1) has no IMPLICIT type; did you mean ‘ind_clo’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:475:32:

  475 |            keepSpcActive(ind_HBr )       = .true.
      |                                1
Error: Symbol ‘ind_hbr’ at (1) has no IMPLICIT type; did you mean ‘ind_br’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:485:32:

  485 |            keepSpcActive(ind_HCl )       = .true.
      |                                1
Error: Symbol ‘ind_hcl’ at (1) has no IMPLICIT type; did you mean ‘ind_cl’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:491:31:

  491 |            keepSpcActive(ind_HI   )      = .true.
      |                               1
Error: Symbol ‘ind_hi’ at (1) has no IMPLICIT type; did you mean ‘ind_’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:476:33:

  476 |            keepSpcActive(ind_HOBr)       = .true.
      |                                 1
Error: Symbol ‘ind_hobr’ at (1) has no IMPLICIT type; did you mean ‘ind_hgbr’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:486:33:

  486 |            keepSpcActive(ind_HOCl)       = .true.
      |                                 1
Error: Symbol ‘ind_hocl’ at (1) has no IMPLICIT type; did you mean ‘ind_hgcl’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:501:32:

  501 |            keepSpcActive(ind_HOI)        = .true.
      |                                1
Error: Symbol ‘ind_hoi’ at (1) has no IMPLICIT type; did you mean ‘ind_ho2’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:487:30:

  487 |            keepSpcActive(ind_I)          = .true.
      |                              1
Error: Symbol ‘ind_i’ at (1) has no IMPLICIT type; did you mean ‘ind_’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:488:31:

  488 |            keepSpcActive(ind_I2   )      = .true.
      |                               1
Error: Symbol ‘ind_i2’ at (1) has no IMPLICIT type; did you mean ‘ind_’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:490:33:

  490 |            keepSpcActive(ind_I2O2)       = .true.
      |                                 1
Error: Symbol ‘ind_i2o2’ at (1) has no IMPLICIT type; did you mean ‘ind_ho2’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:495:33:

  495 |            keepSpcActive(ind_I2O3 )      = .true.
      |                                 1
Error: Symbol ‘ind_i2o3’ at (1) has no IMPLICIT type; did you mean ‘ind_o3’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:494:33:

  494 |            keepSpcActive(ind_I2O4 )      = .true.
      |                                 1
Error: Symbol ‘ind_i2o4’ at (1) has no IMPLICIT type; did you mean ‘ind_bro’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:500:32:

  500 |            keepSpcActive(ind_IBr  )      = .true.
      |                                1
Error: Symbol ‘ind_ibr’ at (1) has no IMPLICIT type; did you mean ‘ind_br’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:499:32:

  499 |            keepSpcActive(ind_ICl  )      = .true.
      |                                1
Error: Symbol ‘ind_icl’ at (1) has no IMPLICIT type; did you mean ‘ind_cl’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:496:32:

  496 |            keepSpcActive(ind_INO  )      = .true.
      |                                1
Error: Symbol ‘ind_ino’ at (1) has no IMPLICIT type; did you mean ‘ind_no’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:489:31:

  489 |            keepSpcActive(ind_IO)         = .true.
      |                               1
Error: Symbol ‘ind_io’ at (1) has no IMPLICIT type; did you mean ‘ind_co’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:497:33:

  497 |            keepSpcActive(ind_IONO)       = .true.
      |                                 1
Error: Symbol ‘ind_iono’ at (1) has no IMPLICIT type; did you mean ‘ind_no’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:498:34:

  498 |            keepSpcActive(ind_IONO2)      = .true.
      |                                  1
Error: Symbol ‘ind_iono2’ at (1) has no IMPLICIT type; did you mean ‘ind_no2’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:492:34:

  492 |            keepSpcActive(ind_ISALA)      = .true.
      |                                  1
Error: Symbol ‘ind_isala’ at (1) has no IMPLICIT type; did you mean ‘ind_cl’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:493:34:

  493 |            keepSpcActive(ind_ISALC)      = .true.
      |                                  1
Error: Symbol ‘ind_isalc’ at (1) has no IMPLICIT type; did you mean ‘ind_cl’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:484:33:

  484 |            keepSpcActive(ind_OClO)       = .true.
      |                                 1
Error: Symbol ‘ind_oclo’ at (1) has no IMPLICIT type; did you mean ‘ind_clo’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:504:35:

  504 |            keepSpcActive(ind_SALAAL)     = .true.
      |                                   1
Error: Symbol ‘ind_salaal’ at (1) has no IMPLICIT type; did you mean ‘ind_cl’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:502:35:

  502 |            keepSpcActive(ind_SALACl)     = .true.
      |                                   1
Error: Symbol ‘ind_salacl’ at (1) has no IMPLICIT type; did you mean ‘ind_cl’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:505:35:

  505 |            keepSpcActive(ind_SALCAL)     = .true.
      |                                   1
Error: Symbol ‘ind_salcal’ at (1) has no IMPLICIT type; did you mean ‘ind_cl’?
[ 93%] Building Fortran object src/GEOS-Chem/GeosCore/CMakeFiles/GeosCore.dir/hco_interface_gc_mod.F90.o
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:503:35:

  503 |            keepSpcActive(ind_SALCCl)     = .true.
      |                                   1
Error: Symbol ‘ind_salccl’ at (1) has no IMPLICIT type; did you mean ‘ind_cl’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:576:17:

  576 |        keepActive = .true.
      |                 1
Error: Symbol ‘keepactive’ at (1) has no IMPLICIT type
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:1186:65:

 1186 |              State_Diag%KppAutoReduceThres(I,J,L) = RSTATE(NARthr)
      |                                                                 1
Error: Symbol ‘narthr’ at (1) has no IMPLICIT type; did you mean ‘naer’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:1181:57:

 1181 |              State_Diag%KppAutoReducerNVAR(I,J,L) = rNVAR
      |                                                         1
Error: Symbol ‘rnvar’ at (1) has no IMPLICIT type; did you mean ‘cnvar’?
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:467:11:

  467 |            keepSpcActive(ind_Br)         = .true.
      |           1
Error: Function ‘keepspcactive’ at (1) has no IMPLICIT type
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:472:11:

  472 |            keepSpcActive(ind_BrO)        = .true.
      |           1
Error: Function ‘keepspcactive’ at (1) has no IMPLICIT type
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:477:11:

  477 |            keepSpcActive(ind_Cl  )       = .true.
      |           1
Error: Function ‘keepspcactive’ at (1) has no IMPLICIT type
/n/holyscratch01/jacob_lab/ryantosca/tests/kpp300/GCC_kpp300/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90:482:11:

  482 |            keepSpcActive(ind_ClO )       = .true.
      |           1
```
The fix should be to move KPP-species-specific code out of fullchem_Mod.F90 and into a module such as `KPP/fullchem/fullchem_HetStateFuncs.F90`.  That will keep fullchem species from being referenced in Hg code.  I will submit a fix.

**Comment by yantosca** [comment]
@jimmielin: doesn't 
```F90
! KEEPSPCACTIVE -
  LOGICAL :: KEEPSPCACTIVE(NVAR)
```
also have to be held THREADPRIVATE?

**Comment by yantosca** [comment]
Oh nevermind, I think I see.  If that is set outside of the parallel loop then it doesn't have to be threadprivate.

**Comment by jimmielin** [comment]
Thanks Bob, I didn't realize that putting species-specific data in `fullchem_mod.F90` won't work due to the Hg simulation. Thanks for helping move this to somewhere under `fullchem` instead.

**Comment by yantosca** [comment]
No problem @jimmielin.  It's a circumstance of having all of the mechanisms build as gckpp.  Otherwise it gets to be a bit of a mess because then you have to include differently named code in modules depending on the mechanism.  I'm on it.

**Comment by yantosca** [comment]
@lizziel @jimmielin: I've pushed updates to abstract the rosenbrock_autoreduce-specific code out of `fullchem_mod.F90`.  This should avoid compilation issues when building the Hg mechanism.

**Comment by yantosca** [comment]
After the fixes in commit 2b350862baa64c80bdbd20ea5d68e796b1218d21, the Hg executable now compiles properly:
```console
==============================================================================
GEOS-Chem Classic: Compilation Test Results

Using 8 OpenMP threads
Number of compilation tests: 8
==============================================================================
 
Compiliation tests:
------------------------------------------------------------------------------
GCClassic........................................Configure & Build......PASS
GCClassic with APM...............................Configure & Build......PASS
GCClassic with BPCH diagnostics..................Configure & Build......PASS
GCClassic with Hg (as a KPP mechanism)...........Configure & Build......PASS
GCClassic with Luo et al wetdep..................Configure & Build......PASS
GCClassic with RRTMG.............................Configure & Build......PASS
GCClassic with TOMAS15...........................Configure & Build......PASS
GCClassic with TOMAS40...........................Configure & Build......PASS
 
Summary of compilation test results:
------------------------------------------------------------------------------
Complilation tests passed:        8
Complilation tests failed:        0
Complilation tests not completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All compilation tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
```

**Comment by yantosca** [comment]
Integration tests timed out to to latency on Cannon.  Resubmitted.

**Comment by yantosca** [comment]
Integration tests timed out due to latency on Cannon. Resubmitted.

**Comment by yantosca** [comment]
Resubmitted GC-Classic integration tests all passed
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

Using 24 OpenMP threads
Number of execution tests: 48
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gc_025x03125_CH4_geosfp_47L_na...................Execute Simulation.....PASS
gc_025x03125_fullchem_geosfp_47L_na..............Execute Simulation.....PASS
gc_05x0625_CH4_merra2_47L_na.....................Execute Simulation.....PASS
gc_05x0625_fullchem_merra2_47L_na................Execute Simulation.....PASS
gc_2x25_aerosol_merra2...........................Execute Simulation.....PASS
gc_2x25_CH4_merra2...............................Execute Simulation.....PASS
gc_2x25_CO2_merra2...............................Execute Simulation.....PASS
gc_2x25_fullchem_merra2..........................Execute Simulation.....PASS
gc_2x25_Hg_merra2................................Execute Simulation.....PASS
gc_2x25_metals_merra2............................Execute Simulation.....PASS
gc_2x25_POPs_BaP_merra2..........................Execute Simulation.....PASS
gc_2x25_tagCH4_merra2............................Execute Simulation.....PASS
gc_2x25_tagCO_merra2.............................Execute Simulation.....PASS
gc_2x25_tagO3_merra2.............................Execute Simulation.....PASS
gc_2x25_TransportTracers_merra2..................Execute Simulation.....PASS
gc_2x25_TransportTracers_merra2_LuoWd............Execute Simulation.....PASS
gc_4x5_aerosol_geosfp............................Execute Simulation.....PASS
gc_4x5_aerosol_merra2............................Execute Simulation.....PASS
gc_4x5_CH4_geosfp................................Execute Simulation.....PASS
gc_4x5_CH4_merra2................................Execute Simulation.....PASS
gc_4x5_fullchem_aciduptake_merra2................Execute Simulation.....PASS
gc_4x5_fullchem_APM_merra2.......................Execute Simulation.....PASS
gc_4x5_fullchem_benchmark_merra2.................Execute Simulation.....PASS
gc_4x5_fullchem_complexSOA_merra2................Execute Simulation.....PASS
gc_4x5_fullchem_complexSOA_SVPOA_merra2..........Execute Simulation.....PASS
gc_4x5_fullchem_geosfp...........................Execute Simulation.....PASS
gc_4x5_fullchem_marinePOA_merra2.................Execute Simulation.....PASS
gc_4x5_fullchem_merra2...........................Execute Simulation.....PASS
gc_4x5_fullchem_merra2_47L.......................Execute Simulation.....PASS
gc_4x5_fullchem_merra2_LuoWd.....................Execute Simulation.....PASS
gc_4x5_fullchem_RRTMG_merra2.....................Execute Simulation.....PASS
gc_4x5_fullchem_TOMAS15_merra2_47L...............Execute Simulation.....PASS
gc_4x5_fullchem_TOMAS40_merra2_47L...............Execute Simulation.....PASS
gc_4x5_Hg_geosfp.................................Execute Simulation.....PASS
gc_4x5_Hg_merra2.................................Execute Simulation.....PASS
gc_4x5_metals_merra2.............................Execute Simulation.....PASS
gc_4x5_POPs_BaP_geosfp...........................Execute Simulation.....PASS
gc_4x5_POPs_BaP_merra2...........................Execute Simulation.....PASS
gc_4x5_tagCH4_geosfp.............................Execute Simulation.....PASS
gc_4x5_tagCH4_merra2.............................Execute Simulation.....PASS
gc_4x5_tagCO_geosfp..............................Execute Simulation.....PASS
gc_4x5_tagCO_merra2..............................Execute Simulation.....PASS
gc_4x5_tagO3_geosfp..............................Execute Simulation.....PASS
gc_4x5_tagO3_merra2..............................Execute Simulation.....PASS
gc_4x5_TransportTracers_geosfp...................Execute Simulation.....PASS
gc_4x5_TransportTracers_geosfp_LuoWd.............Execute Simulation.....PASS
gc_4x5_TransportTracers_merra2...................Execute Simulation.....PASS
gc_4x5_TransportTracers_merra2_LuoWd.............Execute Simulation.....PASS
 
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 48
Execution tests failed: 0
Execution tests not yet completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
Resubmitted GCHP integration tests all passed:
```console
==============================================================================
GCHP: Execution Test Results

Number of execution tests: 3
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gchp_fullchem_benchmark_merra2_c48...............Execute Simulation.....PASS
gchp_fullchem_standard_merra2_c24................Execute Simulation.....PASS
gchp_TransportTracers_geosfp_c24.................Execute Simulation.....PASS
 
Summary of execution test results:
------------------------------------------------------------------------------
Execution tests passed:        3
Execution tests failed:        0
Execution tests not completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
We have merged the chemical mechanism updates from 14.1.0-alpha.0 thru 14.1.0-alpha.3 into this branch, and have started a new set of integration tests.

The new set of GCHP integration tests all passed:
```console
==============================================================================
GCHP: Execution Test Results

Number of execution tests: 3
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gchp_fullchem_benchmark_merra2_c48...............Execute Simulation.....PASS
gchp_fullchem_standard_merra2_c24................Execute Simulation.....PASS
gchp_TransportTracers_geosfp_c24.................Execute Simulation.....PASS
 
Summary of execution test results:
------------------------------------------------------------------------------
Execution tests passed:        3
Execution tests failed:        0
Execution tests not completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
The new set of GEOS-Chem Classic integration tests passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

Using 24 OpenMP threads
Number of execution tests: 48
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gc_025x03125_CH4_geosfp_47L_na...................Execute Simulation.....PASS
gc_025x03125_fullchem_geosfp_47L_na..............Execute Simulation.....PASS
gc_05x0625_CH4_merra2_47L_na.....................Execute Simulation.....PASS
gc_05x0625_fullchem_merra2_47L_na................Execute Simulation.....PASS
gc_2x25_aerosol_merra2...........................Execute Simulation.....PASS
gc_2x25_CH4_merra2...............................Execute Simulation.....PASS
gc_2x25_CO2_merra2...............................Execute Simulation.....PASS
gc_2x25_fullchem_merra2..........................Execute Simulation.....PASS
gc_2x25_Hg_merra2................................Execute Simulation.....PASS
gc_2x25_metals_merra2............................Execute Simulation.....PASS
gc_2x25_POPs_BaP_merra2..........................Execute Simulation.....PASS
gc_2x25_tagCH4_merra2............................Execute Simulation.....PASS
gc_2x25_tagCO_merra2.............................Execute Simulation.....PASS
gc_2x25_tagO3_merra2.............................Execute Simulation.....PASS
gc_2x25_TransportTracers_merra2..................Execute Simulation.....PASS
gc_2x25_TransportTracers_merra2_LuoWd............Execute Simulation.....PASS
gc_4x5_aerosol_geosfp............................Execute Simulation.....PASS
gc_4x5_aerosol_merra2............................Execute Simulation.....PASS
gc_4x5_CH4_geosfp................................Execute Simulation.....PASS
gc_4x5_CH4_merra2................................Execute Simulation.....PASS
gc_4x5_fullchem_aciduptake_merra2................Execute Simulation.....PASS
gc_4x5_fullchem_APM_merra2.......................Execute Simulation.....PASS
gc_4x5_fullchem_benchmark_merra2.................Execute Simulation.....PASS
gc_4x5_fullchem_complexSOA_merra2................Execute Simulation.....PASS
gc_4x5_fullchem_complexSOA_SVPOA_merra2..........Execute Simulation.....PASS
gc_4x5_fullchem_geosfp...........................Execute Simulation.....PASS
gc_4x5_fullchem_marinePOA_merra2.................Execute Simulation.....PASS
gc_4x5_fullchem_merra2...........................Execute Simulation.....PASS
gc_4x5_fullchem_merra2_47L.......................Execute Simulation.....PASS
gc_4x5_fullchem_merra2_LuoWd.....................Execute Simulation.....PASS
gc_4x5_fullchem_RRTMG_merra2.....................Execute Simulation.....PASS
gc_4x5_fullchem_TOMAS15_merra2_47L...............Execute Simulation.....PASS
gc_4x5_fullchem_TOMAS40_merra2_47L...............Execute Simulation.....PASS
gc_4x5_Hg_geosfp.................................Execute Simulation.....PASS
gc_4x5_Hg_merra2.................................Execute Simulation.....PASS
gc_4x5_metals_merra2.............................Execute Simulation.....PASS
gc_4x5_POPs_BaP_geosfp...........................Execute Simulation.....PASS
gc_4x5_POPs_BaP_merra2...........................Execute Simulation.....PASS
gc_4x5_tagCH4_geosfp.............................Execute Simulation.....PASS
gc_4x5_tagCH4_merra2.............................Execute Simulation.....PASS
gc_4x5_tagCO_geosfp..............................Execute Simulation.....PASS
gc_4x5_tagCO_merra2..............................Execute Simulation.....PASS
gc_4x5_tagO3_geosfp..............................Execute Simulation.....PASS
gc_4x5_tagO3_merra2..............................Execute Simulation.....PASS
gc_4x5_TransportTracers_geosfp...................Execute Simulation.....PASS
gc_4x5_TransportTracers_geosfp_LuoWd.............Execute Simulation.....PASS
gc_4x5_TransportTracers_merra2...................Execute Simulation.....PASS
gc_4x5_TransportTracers_merra2_LuoWd.............Execute Simulation.....PASS
 
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 48
Execution tests failed: 0
Execution tests not yet completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Pull request merged**
