### PR TITLE
Update NOAA GMD surface CH4 boundary conditions through 2022

### PR DESCRIPTION
**Pull request by msulprizio**
### Name and Institution (Required)

Name: Melissa Sulprizio
Institution: Harvard / GCST

### Describe the update

Lee Murray provided updated NOAA GMD surface CH4 boundary conditions for GEOS-Chem through December 2022. The file can be found in `ExtData/HEMCO/NOAA_GMD/v2023-10/`. 

### Expected changes

This update will cause changes to the full-chemistry benchmark due to the updated dataset.

### Related Github Issue(s)

- https://github.com/geoschem/geos-chem/issues/1626

### CODE REVIEW

**Comment by msulprizio** [comment]
Tagging @ltmurray @toddmooring

**Review by yantosca — APPROVED** [review]
This PR updates the date range in the HEMCO and ExtData config files.  Good to merge!

**Comment by toddmooring** [comment]
Maybe this is a tangent, but earlier in this thread @msulprizio wrote "This update simply extends the NOAA GMD surface CH4 boundary conditions from 2020 to 2022." @ltmurray is that actually true? I.e., did your updates leave values at all times prior to the end of the old file unchanged? I think the answer might be "no", given our discussion of removing dubious local highs near the Alberta tar sands.

**Comment by ltmurray** [comment]
@toddmooring, you are correct in that the pre-2020 will be slightly different because (a) NOAA occasionally updates its older flask data, (b) the locally-influenced flask data you noticed in the Tar Sands has been removed from the kriging, and (c) the last few years of the old file were extrapolated from the growth rate since methane began rising again in the atmosphere. Since linear extrapolation is clearly no longer appropriate given the recent record acceleration of the methane growth rate, I ended it when the observational record ended to allow users to decide what to do. Will try to update annually going forward after NOAA adds the new year's data to the public database (usually May or June of the subsequent year).

**Comment by toddmooring** [comment]
Thanks @ltmurray for the very quick response--seems like maybe these points should be part of the updated README @msulprizio has asked for.

**Comment by ltmurray** [comment]
Yes, GCST's request from two days ago is on my to-do list. I hold model documentation to a higher standard than an online comment. I've been very ill this past week, and need to prioritize my students.

**Comment by toddmooring** [comment]
No worries and sorry to pester you! Get well soon.

**Comment by ltmurray** [comment]
Thanks. Please pester me though if I am slow to follow up. The squeakiest wheel gets the oil...

**Comment by msulprizio** [comment]
Thanks for pointing that out @toddmooring. I've modified that comment above to avoid confusion.

**Comment by ltmurray** [comment]
Hi Melissa, sorry for the slow response. 

"This directory contains monthly mean surface methane mixing ratios spatially interpolated from NOAA GLOBALVIEW discrete monthly mean flask data using ordinary kriging for 1983-2021. Surface mixing ratios are extended back to 1979 and forward to 2022 via linear extrapolation of the local 1983-1990 and 2018-2021 trends, respectively."

**Comment by msulprizio** [comment]
Thanks @ltmurray! The text is now updated in the README file.

**Comment by toddmooring** [comment]
@ltmurray @msulprizio There appears to be a typo in the recently updated README file. Specifically, it claims that mixing ratios are "extended back to **1979**", but the filename implies the coverage is **1975**-2022. Indeed, the total number of months in the file is consistent with spanning this 48-year period, with the first and last timesteps being 1 January 1975 and 1 December 2022.

**Comment by ltmurray** [comment]
Thanks @toddmooring for catching that. You are correct, so the README should be updated. MERRA2 meteorology does not exist before 1980, but I extrapolated to earlier years in case someone (e.g., myself) wanted to do a spinup with earlier emissions and 1980 meteorology to get Jan 1, 1980 initial conditions.

**Comment by msulprizio** [comment]
Thanks @toddmooring @ltmurray. The README has now been corrected.

**Pull request merged**
