### PR TITLE
Adding in dry deposition updates to Hg0 from Feinberg22 ESPI publication + AMAP emissions

### PR DESCRIPTION
**Pull request by arifein**
This code includes the changes to the dry deposition of Hg0, based on the publication: A. Feinberg, T. Dlamini, M. Jiskra, V. Shah, N. E. Selin, 2022. Evaluating atmospheric mercury (Hg) uptake by vegetation in a chemistry-transport model. Environ. Sci. Process. Impacts. https://doi.org/10.1039/d2em00032f.

The main change is that Hg0 dry deposition reactivity (f0) is set to 3.0e-5 everywhere except for the Amazon rainforest, where it is increased to 0.2. These changes yield improved agreement with observations of Hg0 vegetation uptake, Hg0 seasonality in the Northern midlatitudes, and Hg0 levels in the Southern Hemisphere.

Note that in order to balance the dry deposition changes and maintain good agreement with levels of Hg0 in the Northern Hemisphere, the photo-reduction of Hg(II) in organic aerosol needed to be re-calibrated (HG2ORGP factor increased from 0.004 to 0.010). The altered `FJX_j2j.dat` file is attached here. 

I also attach a benchmark file showing the resulting differences for the Hg concentrations, fluxes, and budget. This compares a run for 2015 from the patch/14.0.1 with the new version including revised Hg0 dry deposition.
 
[FJX_j2j.dat.txt](https://github.com/geoschem/geos-chem/files/9473544/FJX_j2j.dat.txt)
[benchmark_0208_0209.pdf](https://github.com/geoschem/geos-chem/files/9473558/benchmark_0208_0209.pdf)

### CODE REVIEW

**Comment by yantosca** [comment]
Checklist of additional updates to be tacked on to this PR:

  - [x] Point to the `CHEM_INPUTS/FAST_JX/v2022-10-Hg/` folder in the `geoschem_config.yml.Hg` template file
  - [ ] Remove JBrO, Br_GC, and BrO_GC from `HEMCO_Config.rc.Hg` template file
  - [ ] Remove  AERO_ fields from the `HEMCO_Config.rc.Hg`
  - [ ] For now, make sure all oxidant fields point to the GCClassic_Output/13.0..0 version in `HEMCO_Config.rc.Hg`.

**Comment by yantosca** [comment]
@arifein @jennyfisher @hmhorow @msulprizio @Jourdan-He: I have updated the `HEMCO_Config.rc.Hg` template file accordingly.  Could you verify that these look OK?  If so we can proceed to benchmarking.

NOTE: The AMAP emissions will come in a separate PR.

**Comment by arifein** [comment]
@yantosca the changes look fine for me.

**Comment by yantosca** [comment]
Thanks @arifein.  I think we still may have to get the AMAP emissions into the HEMCO_Config.rc file but that should be easy.

**Comment by jennyfisher** [comment]
Sorry for my github ignorance, but I am not sure where to look to see these changes in HEMCO_Config.rc? In any case, if Ari has checked I trust him!

**Comment by arifein** [comment]
@jennyfisher I found the list of commits here: https://github.com/geoschem/geos-chem/compare/feature/Hg0drydep+updateconfig

With the HEMCO_Config.rc.Hg file changes here: https://github.com/geoschem/geos-chem/commit/7369c8927a07906baaa4b9b5788d96e6b7927615

**Comment by yantosca** [comment]
Also question for you @arifein @jennyfisher @hmhorow: We have the AMAP2015 emissions, but are these to be default, or an option?  We can add them in here, but we just need to know what your intent is.

**Comment by yantosca** [comment]
All GEOS-Chem Classic integration tests passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

Using 24 OpenMP threads
Number of execution tests: 48
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gc_025x03125_CH4_geosfp_47L_na...................Execute Simulation.....PASS
gc_025x03125_fullchem_geosfp_47L_na..............Execute Simulation.....PASS
gc_05x0625_CH4_merra2_47L_na.....................Execute Simulation.....PASS
gc_05x0625_fullchem_merra2_47L_na................Execute Simulation.....PASS
gc_2x25_aerosol_merra2...........................Execute Simulation.....PASS
gc_2x25_CH4_merra2...............................Execute Simulation.....PASS
gc_2x25_CO2_merra2...............................Execute Simulation.....PASS
gc_2x25_fullchem_merra2..........................Execute Simulation.....PASS
gc_2x25_Hg_merra2................................Execute Simulation.....PASS
gc_2x25_metals_merra2............................Execute Simulation.....PASS
gc_2x25_POPs_BaP_merra2..........................Execute Simulation.....PASS
gc_2x25_tagCH4_merra2............................Execute Simulation.....PASS
gc_2x25_tagCO_merra2.............................Execute Simulation.....PASS
gc_2x25_tagO3_merra2.............................Execute Simulation.....PASS
gc_2x25_TransportTracers_merra2..................Execute Simulation.....PASS
gc_2x25_TransportTracers_merra2_LuoWd............Execute Simulation.....PASS
gc_4x5_aerosol_geosfp............................Execute Simulation.....PASS
gc_4x5_aerosol_merra2............................Execute Simulation.....PASS
gc_4x5_CH4_geosfp................................Execute Simulation.....PASS
gc_4x5_CH4_merra2................................Execute Simulation.....PASS
gc_4x5_fullchem_aciduptake_merra2................Execute Simulation.....PASS
gc_4x5_fullchem_APM_merra2.......................Execute Simulation.....PASS
gc_4x5_fullchem_benchmark_merra2.................Execute Simulation.....PASS
gc_4x5_fullchem_complexSOA_merra2................Execute Simulation.....PASS
gc_4x5_fullchem_complexSOA_SVPOA_merra2..........Execute Simulation.....PASS
gc_4x5_fullchem_geosfp...........................Execute Simulation.....PASS
gc_4x5_fullchem_marinePOA_merra2.................Execute Simulation.....PASS
gc_4x5_fullchem_merra2...........................Execute Simulation.....PASS
gc_4x5_fullchem_merra2_47L.......................Execute Simulation.....PASS
gc_4x5_fullchem_merra2_LuoWd.....................Execute Simulation.....PASS
gc_4x5_fullchem_RRTMG_merra2.....................Execute Simulation.....PASS
gc_4x5_fullchem_TOMAS15_merra2_47L...............Execute Simulation.....PASS
gc_4x5_fullchem_TOMAS40_merra2_47L...............Execute Simulation.....PASS
gc_4x5_Hg_geosfp.................................Execute Simulation.....PASS
gc_4x5_Hg_merra2.................................Execute Simulation.....PASS
gc_4x5_metals_merra2.............................Execute Simulation.....PASS
gc_4x5_POPs_BaP_geosfp...........................Execute Simulation.....PASS
gc_4x5_POPs_BaP_merra2...........................Execute Simulation.....PASS
gc_4x5_tagCH4_geosfp.............................Execute Simulation.....PASS
gc_4x5_tagCH4_merra2.............................Execute Simulation.....PASS
gc_4x5_tagCO_geosfp..............................Execute Simulation.....PASS
gc_4x5_tagCO_merra2..............................Execute Simulation.....PASS
gc_4x5_tagO3_geosfp..............................Execute Simulation.....PASS
gc_4x5_tagO3_merra2..............................Execute Simulation.....PASS
gc_4x5_TransportTracers_geosfp...................Execute Simulation.....PASS
gc_4x5_TransportTracers_geosfp_LuoWd.............Execute Simulation.....PASS
gc_4x5_TransportTracers_merra2...................Execute Simulation.....PASS
gc_4x5_TransportTracers_merra2_LuoWd.............Execute Simulation.....PASS
 
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 48
Execution tests failed: 0
Execution tests not yet completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
Added entries for the AMAP/UNEP Global Mercury Assessment emissions to the `HEMCO_Config.rc.Hg` template file in commit: c7f17d58afa22681fd08f43acebd7c849d1cc695.  These emissions are stored in the `ExtData/HEMCO/MERCURY/v2022-10` data path.

NOTE: This PR will go into branch **dev/14.1.0** and not main.

**Comment by jennyfisher** [comment]
Thanks @yantosca!

@arifein - just following up on Bob's Q about whether to make the AMAP emissions default... what did you use for your benchmarking? My preference would be to make AMAP default, but I'm not sure if that would mess with the tuning you have done already...

**Comment by arifein** [comment]
Hi @jennyfisher @yantosca, I used the AMAP emissions for my study as well as benchmarking v12-v14 Hg GEOS-Chem versions, so I would also lean to having it as a default.

**Comment by jennyfisher** [comment]
Fantastic!

Just to confirm - this isn't yet in the dev/14.1.0 branch, right? We're currently running (testing) using the dev branch (for the other Hg fixes), so as soon as these updates are in dev/14.1.0 we will pull them in, too.

Cheers,
Jenny

**Comment by jennyfisher** [comment]
Great, thanks! Just to clarify, does that mean if we pull `feature/Hg0drydep+updateconfig` it will have these updates **and** the previous updates to the Hg simulation (that were in the `dev` branch before)?

**Comment by yantosca** [comment]
> Great, thanks! Just to clarify, does that mean if we pull `feature/Hg0drydep+updateconfig` it will have these updates **and** the previous updates to the Hg simulation (that were in the `dev` branch before)?

@jennyfisher: Yes, if you pull the `feature/Hg0drydep+updateconfig` branch, it will have all of the 13.4.1 Hg chemistry plus the drydep update and AMAP emissions.

**Review by msulprizio — APPROVED** [review]

**Comment by jennyfisher** [comment]
Hi @yantosca - I've just cloned dev/14.1.0 and am starting to test. I noticed a couple of switches that still exist in HEMCO_Config.rc, even though we removed the sections for these as they were no longer used:

1. `AERO_HG2_PARTITION`
2. `LRED_JNO2`

I think that these lines can be deleted now. @arifein @viral211 - can you confirm this is correct?

**Comment by yantosca** [comment]
Hi @jennyfisher, thanks for bringing this up.  I can create a PR for fixing this.

**Pull request merged**
