### PR TITLE
Don't allow user to create MERRA-2 0.25 x 0.3125 run directories for GCClassic

### LINKED ISSUE #1944: Need to add error trap to prevent users from creating a GCClassic run directory for MERRA-2 and 0.25x0.3125 resolution
### Name and Institution (Required)

Name: Melissa Sulprizio
Institution: Harvard / GCST

### Description of your issue or question

There is currently no error trap in GCClassic's createRunDir.sh preventing users from selecting Met=MERRA-2 and Resolution=0.25x0.3125.

```
./createRunDir.sh                                                                                                                                                   

===========================================================                                                                                                                                               
GEOS-CHEM RUN DIRECTORY CREATION                                                                                                                                                                          
===========================================================                                                                                                                                               

-----------------------------------------------------------                                                                                                                                               
Choose simulation type:                                                                                                                                                                 
-----------------------------------------------------------                                                                                                                                               
   1. Full chemistry                                                                                                                                                        
   2. Aerosols only                                                                                                                                                     
   3. CH4                                                                                                                       
   4. CO2                                                                                                                       
   5. Hg                                                                                                                    
   6. POPs                                                                                                                          
   7. Tagged CH4                                                                                                                                            
   8. Tagged CO                                                                                                                                         
   9. Tagged O3                                                                                                                                         
  10. TransportTracers                                                                                                                                                              
  11. Trace metals                                                                                                                                                  
  12. Carbon                                                                                                                                
>>> 3                                                                                                           

-----------------------------------------------------------                                                                                                                                               
Choose meteorology source:                                                                                                                                                                          
-----------------------------------------------------------                                                                                                                                               
  1. MERRA-2 (Recommended)                                                                                                                                                                          
  2. GEOS-FP                                                                                                                                    
  3. GISS ModelE2.1 (GCAP 2.0)                                                                                                                                                                            
>>> 1                                                                                                           

-----------------------------------------------------------                                                                                                                                               
Choose horizontal resolution:                                                                                                                                                                             
-----------------------------------------------------------                                                                                                                                               
  1. 4.0  x 5.0                                                                                                                                         
  2. 2.0  x 2.5                                                                                                                                         
  3. 0.5  x 0.625                                                                                                                                               
>>> 4    <--- Note wrong entry here

-----------------------------------------------------------                                                                                                                                               
Choose horizontal grid domain:                                                                                                                                                                            
-----------------------------------------------------------                                                                                                                                               
  1. Global                                                                                                                             
  2. Asia                                                                                                                       
  3. Europe                                                                                                                             
  4. North America                                                                                                                                                  
  5. Custom
>>> 1

-----------------------------------------------------------
Choose number of levels:
-----------------------------------------------------------
  1. 72 (native)
  2. 47 (reduced)
>>> 2
```

Creates a run directory `gc_025x03125_47L_merra2_CH4`. The 0.25 grid is not supported by MERRA-2, so we should not allow users to select that resolution when using MERRA-2.

### PR DESCRIPTION
**Pull request by yantosca**
### Name and Institution (Required)

Name: Bob Yantosca
Institution: Harvard + GCST

### Confirm you have reviewed the following documentation

- [x] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/reference/CONTRIBUTING.html)

### Describe the update
This is the companion PR to #1944,  We have updated the `run/GCClassic/createRunDir.sh` script to:
- Add error trap to prompt user to make another selection if a 0.25 x 0.3125 horizontal resolution is selected w/ MERRA-2 met
- Increase robustness of bash if tests to prevent undefined variables between the `if [[ ]]` brackets
- Trim trailing whitespace

### Expected changes
The loophole described by @msulprizio in #1944 is now closed:

```console
===========================================================
GEOS-CHEM RUN DIRECTORY CREATION
===========================================================

-----------------------------------------------------------
Choose simulation type:
-----------------------------------------------------------
   1. Full chemistry
   2. Aerosols only
   3. CH4
   4. CO2
   5. Hg
   6. POPs
   7. Tagged CH4
   8. Tagged CO
   9. Tagged O3
  10. TransportTracers
  11. Trace metals
  12. Carbon
>>> 1

-----------------------------------------------------------
Choose additional simulation option:
-----------------------------------------------------------
  1. Standard
  2. Benchmark
  3. Complex SOA
  4. Marine POA
  5. Acid uptake on dust
  6. TOMAS
  7. APM
  8. RRTMG
>>> 2

-----------------------------------------------------------
Choose meteorology source:
-----------------------------------------------------------
  1. MERRA-2 (Recommended)
  2. GEOS-FP 
  3. GISS ModelE2.1 (GCAP 2.0)
>>> 1

-----------------------------------------------------------
Choose horizontal resolution:
-----------------------------------------------------------
  1. 4.0  x 5.0
  2. 2.0  x 2.5
  3. 0.5  x 0.625
>>> 4
Cannot create a MERRA-2 rundir at 0.25 x 0.3125 resolution!
Please make another selection.
>>> 1
... etc ...
```

### Reference(s)
N/A

### Related Github Issue(s)
- Closes #1944

### CODE REVIEW

**Comment by yantosca** [comment]
Integration tests are now running.

**Review by msulprizio — APPROVED** [review]
Looks good. Thanks @yantosca!

**Comment by yantosca** [comment]
Integration tests are now running.

**Comment by yantosca** [comment]
All GEOS-Chem Classic integration tests passed (except for TOMAS, which is a known issue):
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

GCClassic #c6ba251 GEOS-Chem submod update: Merge PR #1951 and PR #1917
GEOS-Chem #34bbd82b8 Merge PR #1957 (Update integration tests for WashU cluster)
HEMCO     #daf54d0 Merge PR #235 (Bug fix for vertical regridding)

Using 24 OpenMP threads
Number of execution tests: 26

Submitted as SLURM job: 1852374
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gc_05x0625_NA_47L_merra2_CH4........................Execute Simulation....PASS
gc_05x0625_NA_47L_merra2_fullchem...................Execute Simulation....PASS
gc_4x5_47L_merra2_fullchem..........................Execute Simulation....PASS
gc_4x5_47L_merra2_fullchem_TOMAS15..................Execute Simulation....FAIL
gc_4x5_47L_merra2_fullchem_TOMAS40..................Execute Simulation....FAIL
gc_4x5_merra2_aerosol...............................Execute Simulation....PASS
gc_4x5_merra2_carbon................................Execute Simulation....PASS
gc_4x5_merra2_CH4...................................Execute Simulation....PASS
gc_4x5_merra2_CO2...................................Execute Simulation....PASS
gc_4x5_merra2_fullchem..............................Execute Simulation....PASS
gc_4x5_merra2_fullchem_aciduptake...................Execute Simulation....PASS
gc_4x5_merra2_fullchem_APM..........................Execute Simulation....PASS
gc_4x5_merra2_fullchem_benchmark....................Execute Simulation....PASS
gc_4x5_merra2_fullchem_complexSOA...................Execute Simulation....PASS
gc_4x5_merra2_fullchem_complexSOA_SVPOA.............Execute Simulation....PASS
gc_4x5_merra2_fullchem_LuoWd........................Execute Simulation....PASS
gc_4x5_merra2_fullchem_marinePOA....................Execute Simulation....PASS
gc_4x5_merra2_fullchem_RRTMG........................Execute Simulation....PASS
gc_4x5_merra2_Hg....................................Execute Simulation....PASS
gc_4x5_merra2_metals................................Execute Simulation....PASS
gc_4x5_merra2_POPs_BaP..............................Execute Simulation....PASS
gc_4x5_merra2_tagCH4................................Execute Simulation....PASS
gc_4x5_merra2_tagCO.................................Execute Simulation....PASS
gc_4x5_merra2_tagO3.................................Execute Simulation....PASS
gc_4x5_merra2_TransportTracers......................Execute Simulation....PASS
gc_4x5_merra2_TransportTracers_LuoWd................Execute Simulation....PASS
 
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 24
Execution tests failed: 2
Execution tests not yet completed: 0
```
Furthermore, all integration tests were zero-diff w/r/t the prior integration test (PR #1917 + PR #1951), except for the usual suspects (APM, TOMAS, RRTMG diagnostics):
```console
Checking gc_05x0625_NA_47L_merra2_CH4
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_05x0625_NA_47L_merra2_fullchem
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_47L_merra2_fullchem
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_47L_merra2_fullchem_TOMAS15
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_47L_merra2_fullchem_TOMAS40
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_merra2_aerosol
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_merra2_carbon
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_merra2_CH4
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_merra2_CO2
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_merra2_fullchem
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_merra2_fullchem_aciduptake
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_merra2_fullchem_APM
   -> 1 difference found in OutputDir
      * GCC_r23/rundirs/gc_4x5_merra2_fullchem_APM/OutputDir/GEOSChem.SpeciesConc.20190701_0000z.nc4 
        GCC_r24/rundirs/gc_4x5_merra2_fullchem_APM/OutputDir/GEOSChem.SpeciesConc.20190701_0000z.nc4 
   -> 1 difference found in Restarts
      * GCC_r23/rundirs/gc_4x5_merra2_fullchem_APM/Restarts/GEOSChem.Restart.20190701_0100z.nc4 
        GCC_r24/rundirs/gc_4x5_merra2_fullchem_APM/Restarts/GEOSChem.Restart.20190701_0100z.nc4 

Checking gc_4x5_merra2_fullchem_benchmark
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_merra2_fullchem_complexSOA
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_merra2_fullchem_complexSOA_SVPOA
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_merra2_fullchem_LuoWd
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_merra2_fullchem_marinePOA
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_merra2_fullchem_RRTMG
   -> 1 difference found in OutputDir
      * GCC_r23/rundirs/gc_4x5_merra2_fullchem_RRTMG/OutputDir/GEOSChem.RRTMG.20190701_0000z.nc4 
        GCC_r24/rundirs/gc_4x5_merra2_fullchem_RRTMG/OutputDir/GEOSChem.RRTMG.20190701_0000z.nc4 
   -> No differences in Restarts

Checking gc_4x5_merra2_Hg
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_merra2_metals
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_merra2_POPs_BaP
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_merra2_tagCH4
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_merra2_tagCO
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_merra2_tagO3
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_merra2_TransportTracers
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_merra2_TransportTracers_LuoWd
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_merra2_tagCO
   -> No differences in OutputDir
   -> No differences in Restarts
```

**Comment by yantosca** [comment]
All GCHP execution tests passed:
```console
==============================================================================
GCHP: Execution Test Results

GCClassic #632ebd6 GEOS-Chem submod update: Merge PR #1951 and PR #1917
GEOS-Chem #34bbd82b8 Merge PR #1957 (Update integration tests for WashU cluster)
HEMCO     #daf54d0 Merge PR #235 (Bug fix for vertical regridding)

Number of execution tests: 5

Submitted as SLURM job: 1865321
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gchp_merra2_fullchem................................Execute Simulation....PASS
gchp_merra2_fullchem_benchmark......................Execute Simulation....PASS
gchp_merra2_fullchem_RRTMG..........................Execute Simulation....PASS
gchp_merra2_tagO3...................................Execute Simulation....PASS
gchp_merra2_TransportTracers........................Execute Simulation....PASS
 
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 5
Execution tests failed: 0
Execution tests not yet completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
Furthermore, all GCHP integration tests were zero-diff w/r/t the prior integration test (PR #1917 and PR #1951):
```console
Checking gchp_merra2_fullchem
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gchp_merra2_fullchem_benchmark
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gchp_merra2_fullchem_RRTMG
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gchp_merra2_tagO3
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gchp_merra2_TransportTracers
   -> No differences in OutputDir
   -> No differences in Restarts
```

**Pull request merged**
