### PR TITLE
Use hard-coded dates for meteorological fields and boundary conditions

### PR DESCRIPTION
**Pull request by nicholasbalasus**
### Name and Institution (Required)

Name: Nick Balasus
Institution: Harvard University

### Describe the update

Add hard-coded dates back into `HEMCO_Config.rc` to stop met fields and boundary conditions from being read hourly.

### Expected changes

zero-diff on results, but the simulation will be much faster

### Reference(s)

n/a

### Related Github Issue

#2344

### CODE REVIEW

**Review by msulprizio — APPROVED** [review]

**Review by yantosca — APPROVED** [review]
Thanks @nicholasbalasus!  I will work on pulling this into 14.4.1.

**Comment by yantosca** [comment]
All GEOS-Chem Classic integration tests passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

GCClassic #358b614 Merge PR #2317 (Fix filename for CMIP6 aircraft emissions)
GEOS-Chem #a6485af31 Merge PR #2347 (Use hard-coded dates for met fields/BCs)
HEMCO     #55d27e2 Merge PR #280 (Now use comma-separated list in stale.yml )

Using 24 OpenMP threads
Number of execution tests: 28

Submitted as SLURM job: 37391440
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
Also, all integration tests were zero-diff w/r/t 14.4.0 except for:
- TOMAS15 (parallelization issue?)
- APM (parallelization issue?)

**Comment by yantosca** [comment]
All GCHP integration tests passed:
```console
==============================================================================
GCHP: Execution Test Results

GCHP      #574f2d6 GEOS-Chem submod update: Merge PR #2317 (Fix CMIP6 aircraft filenames)
GEOS-Chem #a6485af31 Merge PR #2347 (Use hard-coded dates for met fields/BCs)
HEMCO     #

Number of execution tests: 11

Submitted as SLURM job: 37392085
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
Also, all GCHP integration tests were zero-diff w/r/t 14.4.0

**Comment by yantosca** [comment]
We can now close this issue as it has been merged into dev/no-diff-to-benchmark.

**Pull request closed without merging**
