### PR TITLE
Bug fix:  Reorder photo rxns for PNs and ANs (from PR #2318)

### PR DESCRIPTION
**Pull request by yantosca**
### Name and Institution (Required)

Name: Bob Yantosca
Institution: Harvard + GCST

### Describe the update
This PR reorders the following photolysis reactions from the ordering that they were in PR #2318:

```console
APINP + hv = PINAL + OH + HO2 :              PHOTOL(167) ;  
PINAL + hv = CO + HO2 + C96O2 :              PHOTOL(168) ;
PINO3H + hv = OH + CO2 + C96O2 :             PHOTOL(169) ;
PINONIC + hv = OH + CO2 + C96O2 :            PHOTOL(170) ;
C96O2H + hv = OH + AROMRO2 + ACET +
 CH2O + RCO3 + 0.5MEK :                      PHOTOL(171) ;
BPINP + hv = OH + CH2O + HO2 + BPINO :       PHOTOL(172) ;
BPINOOH + hv = OH + HO2 + 0.27LIMO3 +
 0.6ACET + 0.6RCHO + 0.6R4O2 :               PHOTOL(173) ;
LIMO3H + hv = OH + CO2 + MCO3 + RCHO +
 0.4CH2O + 0.8R4O2 :                         PHOTOL(174) ;
LIMO2H + hv = OH + CO2 + MCO3 + RCHO +
 0.4CH2O + 0.8R4O2 :                         PHOTOL(175) ;
,,,
LIMAL + hv = CO + HO2 + 0.900LIMO3 :         PHOTOL(176) ;
```
to:
```console
APINP + hv = PINAL + OH + HO2 :              PHOTOL(168) ;  
PINAL + hv = CO + HO2 + C96O2 :              PHOTOL(169) ;
PINO3H + hv = OH + CO2 + C96O2 :             PHOTOL(170) ;
PINONIC + hv = OH + CO2 + C96O2 :            PHOTOL(171) ;
C96O2H + hv = OH + AROMRO2 + ACET +
 CH2O + RCO3 + 0.5MEK :                      PHOTOL(172) ;
BPINP + hv = OH + CH2O + HO2 + BPINO :       PHOTOL(173) ;
BPINOOH + hv = OH + HO2 + 0.27LIMO3 +
 0.6ACET + 0.6RCHO + 0.6R4O2 :               PHOTOL(174) ;
LIMO3H + hv = OH + CO2 + MCO3 + RCHO +
 0.4CH2O + 0.8R4O2 :                         PHOTOL(175) ;
LIMO2H + hv = OH + CO2 + MCO3 + RCHO +
 0.4CH2O + 0.8R4O2 :                         PHOTOL(176) ;
...
LIMAL + hv = CO + HO2 + 0.900LIMO3 :         PHOTOL(177) ;
```
This is necessary because `PHOTOL(167)` slot is now occupied by the PPN photolysis rxn from PR #2371.
 
### Expected changes
Before this PR, the relevant species had photolysis disabled, because their entries were disabled.
apinn

This PR will fix this issue.

### Related Github Issue
- See PR #2371

### CODE REVIEW

**Comment by yantosca** [comment]
Integration tests are running

**Comment by yantosca** [comment]
All GEOS-Chem Classic integration tests passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

CodeDir   : 49908a8 GEOS-Chem submod update: Merge PR #2424, PR #2426, Cloud-J PR #24
GEOS-Chem : 033204967 Bug fix: Properly order photo rxns for PPN, PNs, and ANs
HEMCO     : d0d5fca PR #285 post-merge fix: Update CHANGELOG.md
Cloud-J   : 6bf4a36 Merge pull request #26 from geoschem/feature/define_max_rather_than_exact_num_jvalues
HETP      : 2a99b24 Merge pull request #2 from geoschem/bugfix/initialize_local_variables

Using 24 OpenMP threads
Number of execution tests: 30

Submitted as SLURM job: 46070546
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
All GCHP integration tests passed:
```console
==============================================================================
GCHP: Execution Test Results

CodeDir       : 3fb63d5 GEOS-Chem submod update: Merge PR #2424, PR #2426, Cloud-J PR #24
MAPL          : 231d53c Merge pull request #36 from geoschem/feature/improve_hflux_regridding
GMAO_Shared   : 4ddb3ec Merge pull request #2 from geoschem/feature/mapl-upgrade
ESMA_cmake    : ad5deba Added ecbuild as a submodule of ESMA_cmake
gFTL-shared   : 4b82492 Merge branch 'upstream_v1.5.0' into feature/v1.5.0
FMS           : 259759d Merge pull request #3 from geoschem/feature/update_gmao_libs
FVdycoreCubed : af42462 Merge PR #8 (Add PLEadv diagnostic for offline advection in GCHP)
geos-chem     : 033204967 Bug fix: Properly order photo rxns for PPN, PNs, and ANs
HEMCO         : d0d5fca PR #285 post-merge fix: Update CHANGELOG.md
yaFyaml       : 19afe50 Merge branch 'upstream_v1.0.4' into feature/v1.0.4
pFlogger      : 2c4b724 Merge branch 'upstream_v1.9.1' into feature/v1.9.1
Cloud-J       : 6bf4a36 Merge pull request #26 from geoschem/feature/define_max_rather_than_exact_num_jvalues
HETP          : 2a99b24 Merge pull request #2 from geoschem/bugfix/initialize_local_variables

Number of execution tests: 12

Submitted as SLURM job: 46070842
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by lizziel** [comment]
Looks good except that I don't think this PR will fix the issue of J-value zero values. The issue of zero J-values is fixed by Cloud-J https://github.com/geoschem/Cloud-J/pull/26 and adding in the reactions to `FJX_j2j.dat`. This PR is to accomodate a different ordering of reactions in FJX_j2j.dat, where PPN is listed as 167.

**Review by lizziel — APPROVED** [review]

**Comment by yantosca** [comment]
@lizziel: Thanks for the clarification.  It will fix the zero J-values seen in these species inasmuch as we will use the updated `FJX_j2j.dat` file with the proper orderings with this PR.

**Pull request merged**
