### PR TITLE
Fix scale factors applied to AEIC VOC emissions - Closes #915

### LINKED ISSUE #915: [BUG/ISSUE] AEIC VOC scale factors might not be right (?)
### Description of the problem
The scale factors applied to aviation VOC emissions were changed on v13.2.0 (https://github.com/geoschem/geos-chem/pull/776), but I am a bit unsure if the added carbon correction was needed, could someone please check this issue again? I was under the impression that the HC variable in AEIC was in CH4-equivalent grams, as mentioned in the papers describing the inventory (https://doi.org/10.1016/j.trd.2013.07.001, https://doi.org/10.1016/j.atmosenv.2011.07.012). The speciation factors seem to be those adopted by the EPA (https://www.epa.gov/regulations-emissions-vehicles-and-engines/organic-gas-speciation-profile-aircraft), which are also implemented by the FAA's emissions model (https://aedt.faa.gov/Documents/AEDT3d_UserManual.pdf, item 5.1.1.8).

In GEOS-Chem, we have factor `114` (=1.16e-3) which does (g)->(kg) and the conversion of THC (total hydrocarbons, base CH4) to TOG (total organic gases, in overall mass). And then factors `101` ... `109` do the speciation on that as per the EPA profile. So, unless I am missing something, weren't the resulting numbers prior to the patch already in total kg of each species?

### GEOS-Chem version
v13.2.x

### PR DESCRIPTION
**Pull request by flavioquadros**
This is a PR for #915 removing the unnecessary application of factors 40-42, 45, 46, 49, 83, 84 to aviation VOC emissions, and doing the speciation into more GEOS-Chem tracers. I am not 100% sure how things were lumped before such that ALK4, PRPE, MACR, RCHO are a bit different here. I used the following mapping:

```
ALK4 = n-pentane, 2-methylpentane, n-heptane, n-octane, n-nonane, n-decane, n-undecane, n-dodecane, n-tridecane, C14-alkane, C15-alkane, n-tetradecane, C16-alkane, n-pentadecane, n-hexadecane, C18-alkane, n-heptadecane.
PRPE = propylene, isobutene/1-butene, cis-2-butene, 3-methyl-1-butene, 1-pentene, 2-methyl-1-butene, trans-2-pentene, cis-2-pentene, 2-methyl-2-butene, 4-methyl-1-pentene, 2-methyl-1-pentene, 1-hexene, trans-2-hexene, 1-heptene, 1-octene, 1-nonene, 1-decene.
MACR = methacrolein, C-10 paraffins.
RCHO = propionaldehyde, crotonaldehyde, butyraldehyde, benza;dehyde, isovaleraldehyde, valeraldehyde, o-tolualdehyde, p-tolualdehyde, acrolein, dodecenal.
XYLE = ehylbenzene, m-xylene/p-xylene, o-xylene
```

### CODE REVIEW

**Comment by yantosca** [comment]
Tagging @sdeastham and the Emissions Working Group (@eamarais), who can better answer about the speciation than I can.  It looks like a straightforward modification.

**Comment by flavioquadros** [comment]
Sorry, I was checking this again and realized I made a small mistake allocating dodecenal. There were also some mistakes when copying the names of the species into the list below, which is now correct:

```
ALK4 = n-pentane, 2-methylpentane, n-heptane, n-octane, n-nonane, n-decane, n-undecane, n-dodecane, n-tridecane, C14-alkane, C15-alkane, n-tetradecane, C16-alkane, n-pentadecane, n-hexadecane, C18-alkane, n-heptadecane, C-10 paraffins.
PRPE = propylene, isobutene/1-butene, cis-2-butene, 3-methyl-1-butene, 1-pentene, 2-methyl-1-butene, trans-2-pentene, cis-2-pentene, 2-methyl-2-butene, 4-methyl-1-pentene, 2-methyl-1-pentene, 1-hexene, trans-2-hexene, 1-heptene, 1-octene, 1-nonene, 1-decene, C-10 olefins.
RCHO = propionaldehyde, crotonaldehyde, butyraldehyde, benzaldehyde, isovaleraldehyde, valeraldehyde, o-tolualdehyde, p-tolualdehyde, acrolein, decanal, dodecenal.
XYLE = ethylbenzene, m-xylene/p-xylene, o-xylene
Single species mapped to tracer: ACET, ALD2, BENZ, C2H2, C2H4, C2H6, C3H8, CH2O, GLYX, MACR, MGLY, MOH, NAP, PHEN, TOLU
```

**Comment by yantosca** [comment]
GCHP integration tests all passed
```console
==============================================================================
GCHP: Execution Test Results

Number of execution tests: 3
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gchp_fullchem_benchmark_merra2_c48...............Execute Simulation.....PASS
gchp_fullchem_standard_merra2_c24................Execute Simulation.....PASS
gchp_TransportTracers_geosfp_c24.................Execute Simulation.....PASS
 
Summary of execution test results:
------------------------------------------------------------------------------
Execution tests passed:        3
Execution tests failed:        0
Execution tests not completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
All GCHP integration tests pass
```console
==============================================================================
GCHP: Execution Test Results

Number of execution tests: 3
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gchp_fullchem_benchmark_merra2_c48...............Execute Simulation.....PASS
gchp_fullchem_standard_merra2_c24................Execute Simulation.....PASS
gchp_TransportTracers_geosfp_c24.................Execute Simulation.....PASS
 
Summary of execution test results:
------------------------------------------------------------------------------
Execution tests passed:        3
Execution tests failed:        0
Execution tests not completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
All GEOS-Chem Classic integration tests passed:
```console
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 48
Execution tests failed: 0
Execution tests not yet completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
Emissions totals that are affected:

```console
                     alpha.12       alpha.13       diff        %diff
ALK4 Aircraft      : 0.005617       0.004274     -0.001343   -23.912
C2H6 Aircraft      : 0.000152       0.000122     -0.000031   -20.213
C3H8 Aircraft      : 0.000022       0.000018     -0.000004   -18.386
MACR Aircraft      : 0.001827       0.000100     -0.001727   -94.522
PRPE Aircraft      : 0.004855       0.003779     -0.001076   -22.168
RCHO Aircraft      : 0.001384       0.003358      0.001974   142.621
```
Benchmark results can be seen at:
https://ftp.as.harvard.edu/gcgrid/geos-chem/validation/InternalBenchmarks/13.4.0/GCC_13.4.0-alpha.13/

In general, the changes to oxidant and primary organics are negligible.   OH metrics change very slightly (Mean OH -0.005%, MCF lifetime +0.006%, CH4 lifetime +0.006%).

**Pull request merged**
