### PR TITLE
Read number of levels with clouds used in photolysis from config file

### PR DESCRIPTION
**Pull request by lizziel**
### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### Describe the update

This PR addresses the issue of hard-coding number of levels with cloud within Cloud-J photolysis. It fixes a bug where you can only use Cloud-J in GEOS-Chem at 72 levels. It goes with Cloud-J PR  https://github.com/geoschem/Cloud-J/pull/17 which now accepts this parameter from parent models.

Updates include:
- Add new `Input_Opt` setting `Nlevs_Phot_Cloud`
- Set `Input_Opt%Nlevs_Phot_Cloud` from new setting in `geoschem_config.yml` photolysis menu
- Move a few existing settings in `input_opt_mod.F90` to photolysis menu since that is now where they are stored in `geoschem_config.yml`
- Update all `geoschem_config.yml` templates to include the new parameter. 

### Expected changes

This is a zero diff update.

### Reference(s)

None

### Required companion PRs

https://github.com/geoschem/Cloud-J/pull/17

### Related Github issues

https://github.com/geoschem/Cloud-J/issues/16

### CODE REVIEW

**Comment by lizziel** [comment]
I need to do a bit more work on this to have the parameter set during run directory creation.

**Review by yantosca — APPROVED** [review]
Thanks @lizziel. This looks OK to merge.  One thing, we will need to add the `num_levs_with_cloud` YAML tag to the `geoschem_config.rst` documentation page.  We could do this in the `docs/dev` branch though.

**Comment by yantosca** [comment]
Integration tests are running

**Comment by yantosca** [comment]
All GEOS-Chem Classic integration tests passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

GCClassic #14397c6 GEOS-Chem submod update: Merge PR #2363 (Update setCommonRunSettings.sh)
GEOS-Chem #f78052f59 Merge PR #2342 (Read number of levels with clouds into Cloud-J)
HEMCO     #2192e0e HEMCO 3.9.1 release

Using 24 OpenMP threads
Number of execution tests: 28

Submitted as SLURM job: 39073394
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
All tests were zero-diff w/r/t PR #2363 except:
- TOMAS15 (parallelization error?)
- APM (parallelization error?)

**Comment by yantosca** [comment]
All GCHP integration tests passed:
```console
==============================================================================
GCHP: Execution Test Results

GCHP      #9c77f30 GEOS-Chem submod update: Merge PR #2363 (Update setCommonRunSettings.sh)
GEOS-Chem #f78052f59 Merge PR #2342 (Read number of levels with clouds into Cloud-J)
HEMCO     #

Number of execution tests: 11

Submitted as SLURM job: 39073425
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
Also, all tests were zero-diff w/r/t PR #2363.

**Pull request merged**
