### PR TITLE
Some fixes required to compile adjoint geos chem

### PR DESCRIPTION
**Pull request by kaysuselj**
### Name and Institution (Required)

Name: Kay Suselj
Institution: JPL

### Describe the update

Fixed a few bugs, so adjoint version to be compiled 

### Expected changes

Adjoint version (with flags `-DADJOINT=yes -DREVERSE_OPERATORS=yes`) compiled without errors. 

### Reference(s)

NA

### Related Github Issue

NA

### CODE REVIEW

**Comment by yantosca** [comment]
Thanks for the PR @kaysuselj.  Can we push merge conflicts back to this branch?  This would automatically update the PR but would also bring in updates from 14.5.0.  Just wanted to make sure that you won't be working in this branch.

**Comment by kaysuselj** [comment]
Hi [yantosca](https://github.com/yantosca), yes please bring the updates from 14.5.0 to this PR.

**Comment by yantosca** [comment]
Thanks @kaysuselj,  @lizziel can do that since she is the one in contact with you.

**Review by lizziel — APPROVED** [review]
I merged in the dev/no-diff-to-benchmark branch and added a line to the changelog to document the adjoint fixes. I reviewed the changes relative to dev/no-diff-to-benchmark and they preserve the original updates. This is now good to merge!

**Comment by yantosca** [comment]
All GEOS-Chem Classic integration tests passed, except for tagCO (known restart file issue)
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

CodeDir   : a8aeb02 GEOS-Chem update: Merge PR #2578 (Fixes for GCHP adjoint )
GEOS-Chem : 62f3db08b Merge PR #2578 (Fixes to compile GCHP adjoint)
HEMCO     : deaa192 HEMCO 3.10.0 release
Cloud-J   : f8a2b7f Update version number for 8.0.1 release
HETP      : 2a99b24 Merge pull request #2 from geoschem/bugfix/initialize_local_variables

Using 24 OpenMP threads
Number of execution tests: 30

Submitted as SLURM job: 59103476
==============================================================================

...
gc_4x5_merra2_tagCO.................................Execute Simulation....FAIL
...
 
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 29
Execution tests failed: 1
Execution tests not yet completed: 0
```
Also all tests were zero-diff w/r/t the previous integration test except for:
- TOMAS (parallelization issue?)
- APM (parallelization issue?)

**Comment by yantosca** [comment]
All GCHP integration tests passed:
```console
==============================================================================
GCHP: Execution Test Results

CodeDir       : 7c2d8e2 GEOS-Chem update: Merge PR #2578 (Fixes for GCHP adjoint )
MAPL          : 9ad63ae Merge PR #37 containing update to vertically flip imports with dimensionless pressure proxy lev coordinates
GMAO_Shared   : 4ddb3ec Merge pull request #2 from geoschem/feature/mapl-upgrade
ESMA_cmake    : ad5deba Added ecbuild as a submodule of ESMA_cmake
gFTL-shared   : 4b82492 Merge branch 'upstream_v1.5.0' into feature/v1.5.0
FMS           : 259759d Merge pull request #3 from geoschem/feature/update_gmao_libs
FVdycoreCubed : af42462 Merge PR #8 (Add PLEadv diagnostic for offline advection in GCHP)
geos-chem     : 62f3db08b Merge PR #2578 (Fixes to compile GCHP adjoint)
HEMCO         : deaa192 HEMCO 3.10.0 release
yaFyaml       : 19afe50 Merge branch 'upstream_v1.0.4' into feature/v1.0.4
pFlogger      : 2c4b724 Merge branch 'upstream_v1.9.1' into feature/v1.9.1
Cloud-J       : f8a2b7f Update version number for 8.0.1 release
HETP          : 2a99b24 Merge pull request #2 from geoschem/bugfix/initialize_local_variables

Number of execution tests: 12

Submitted as SLURM job: 59103750
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
Also, all tests were zero-diff w/r/t the previous set of integration tests.

**Pull request merged**
