### PR TITLE
Photolysis of NIT(s) (off by default)

### PR DESCRIPTION
**Pull request by tsherwen**
This update allows for optional photolysis of aerosol nitrate (NIT(s)) yielding HNO2+NO2. This set to off as default. The photolysis rate is scaled the photolysis rates of HNO3 (JHNO3) as described by Kasibhatla et al (2018). The photolysis rate and product split is set in the input.geos file with the lines as below:

"
Photolyse nitrate aer.? : F
 => NIT Jscale (JHNO3)  : 0.0
 => NITs Jscale (JHNO3) : 0.0
 => % channel A (HONO)  : 66.667
 => % channel B (NO2)   : 33.333
"

Note: this commit does not contain the updates to partitioning or heterogeneous uptake and hydrolysis of NO2 required to reproduce the results of Kasibhatla et al. (2018). These commits are being submitted separately.

All KPP mechanisms were rebuilt following the inclusion of photolysis of nitrate aerosol updates.

Kasibhatla, P., Sherwen, T., Evans, M. J., Carpenter, L. J., Alexander, B., Chen, Q., Sulprizio, M. P., Lee, J. D., Read, K. A., Bloss, W., Crilley, L. R., Keene, W. C., Pszenny, A. A. P., and Hodzic, A.: Global impact of nitrate photolysis in sea-salt aerosol on NOx, OH, and O4 in the marine boundary layer, Atmos. Chem. Phys., 18, 11185-11203, https://doi.org/10.5194/acp-18-11185-2018, 2018.

Signed-off-by: Tomas <tomas.sherwen@gmail.com>

### CODE REVIEW

**Comment by msulprizio** [comment]
Thanks, Tomas! This update will likely be considered for inclusion in 12.5.0.

**Comment by tsherwen** [comment]
Hello @msulprizio, Please could I confirm whether the plan is to merge this code into v12.5 still (e.g. v14.0.1)? I thought I would check considering discussions at IGC9 (Daniel's plenary + Aerosol/Chemistry working group sessions) and because it is set to off by default so won't result in real changes. When people are interested in this new feature, I'm keen to encourage people to just pull the latest code rather than to merge this pull request. Cheers, Tomas

**Comment by msulprizio** [comment]
We're still waiting on the GCSC to prioritize items to include in upcoming versions based on IGC9 discussions. I brought this update to Daniel's attention today and mentioned it can go in anytime and won't impact the benchmark. We will keep you posted.

**Comment by msulprizio** [comment]
The GCSC has decided this update will go into 12.6.0. See http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_model_development_priorities#12.6.0.

**Comment by tsherwen** [comment]
Great. Thanks for the confirmation, Melissa. It ended up with a "1" at the end of IGC9 even though it was ready to go, which I probably should have raised at the time. This all seems good and I'll wait for any emails if anything else is needed from me (I see now that is saying there are conflicts, which weren't there when I submitted the pull request). Cheers!

**Comment by msulprizio** [comment]
This is now in dev/12.6.0 and will be pushed to master when that version is benchmarked and approved. See:
* https://github.com/geoschem/geos-chem/tree/dev/12.6.0
* https://github.com/geoschem/geos-chem-unittest/tree/dev/12.6.0

**Pull request closed without merging**
