### PR TITLE
[PULL REQUEST] Remove requirement that data comes from "GIGCchem"

### PR DESCRIPTION
**Pull request by sdeastham**
DiagList only permits data to come from the "GIGCchem" component, but we can want data from other components (e.g. mass fluxes from the GIGCenv component). This requirement should be removed.

### CODE REVIEW

**Comment by lizziel** [comment]
Agreed. @yantosca, do you remember why this check is here?

**Comment by yantosca** [comment]
I don't remember.  Maybe we can go ahead and take that out then.

**Comment by lizziel** [comment]
Yeah, we already have this code that skips the variable if not in GIGCchem so that it is isn't added to diaglist. Exiting with an error would potentially be a problem since there can be other diagnostics we want to get out of history that are outside the chem child grid comp.

```
       ! Skip line if GIGCchem not present
       ! GEOS-Chem is names 'GEOSCHEMCHEM' on NCCS discover,
       ! scan accordingly (ckeller, 12/29/17)
#if defined( MODEL_GEOS )
       IF ( INDEX( Line, 'GEOSCHEMCHEM' ) .le. 0 ) CYCLE
#else
       IF ( INDEX( Line, 'GIGCchem' ) .le. 0 ) CYCLE
#endif
```

**Comment by yantosca** [comment]
Hmm.  Now I recall.  I think we put that there because "GIGCchem" indicates that the line contains a diagnostic field.  Maybe we need a better search algorithm for that then.

**Comment by lizziel** [comment]
Once we get start using CPP flags for Classic vs GCHP I think some of the HISTORY.rc parsing error handling can be switched to Classic only. Some of it may be more strict than MAPL rules for HISTORY.rc syntax.

**Comment by lizziel** [comment]
Unless there are objections I am going to merge this PR into 12.7.1 and then delete the commented out code.

**Comment by lizziel** [comment]
This is now merged in 12.7.1.

**Pull request closed without merging**
