### PR TITLE
[PULL REQUEST] FlexChem performance with OpenMP collapse

### PR DESCRIPTION
**Pull request by cdholmes**
Add OpenMP collapse ( 2 ) directive to flexchem.

Previously only the outer L loop was parallel, so there were nLev work blocks.
With collapse ( 2 ), both L and J loops execute in parallel, giving nLev * nLat work blocks.

The larger number of work blocks allow more even
distribution of the work across CPUs, improving runtime.
FlexChem performance improvement (median of 3 trials):
12% faster with 20 OpenMP threads
32% faster with 50 OpenMP threads

Collapse ( 3 ) (i.e. parallelizing over all I,J,L loops)
was 1% faster than collapse ( 2 ) in tests with 50 threads.
Since benefits will be smaller with fewer threads, collapse ( 2 )
currently seems to be a good balance between performance and overhead.

Other loops within GEOS-Chem may similarly benefit from collapse directives.

Signed-off-by: Christopher Holmes <cdholmes@fsu.edu>

### CODE REVIEW

**Comment by yantosca** [comment]
Also see the discussion in #598.  Rewriting the rate law functions to remove useless computations saves about 20 minutes wall time per month of GCC 4x5 benchmark simulation.  

I will also test the potential speedup of using `!$OMP COLLAPSE` on top of the speedup described in #598.   

Lastly, according to the OpenMP documention, the `!$OMP COLLAPSE` keyword has been available since at least OpenMP 4.5, which was introduced in 2015.  So most newer gfortran and ifort compiler versions will support this keyword.

**Comment by yantosca** [comment]
I was able to do a couple of test runs on our Harvard Cannon cluster, using 48 cores (24 physical cores + hyperthreading):

## Ref 
Branch:  `feature/bmy/StreamlineKPP`
Description: Uses optimized rate law functions (see discussion in #598)
```
  Timer name                       DD-hh:mm:ss.SSS     Total Seconds
-------------------------------------------------------------------------------
  GEOS-Chem                     :  00-00:46:43.984          2803.984
  Initialization                :  00-00:00:57.546            57.547
  HEMCO                         :  00-00:07:50.609           470.609
  All chemistry                 :  00-00:19:50.218          1190.219
  => FlexChem                   :  00-00:13:32.984           812.984
    -> FlexChem loop            :  00-00:13:14.312           794.312
    -> Init KPP                 :  00-00:00:06.422             6.423
    -> Het chem rates           :  00-00:00:47.619            47.619
    -> Photolysis rates         :  00-00:00:04.625             4.625
    -> KPP                      :  00-00:07:53.774           473.774
       RCONST                   :  00-00:00:38.384            38.384
       Integrate 1              :  00-00:06:58.773           418.773
    -> Prod/loss diags          :  00-00:00:03.724             3.725
  => FAST-JX photolysis         :  00-00:01:20.640            80.641
  => Aerosol chem               :  00-00:04:40.828           280.828
  => Linearized strat chem      :  00-00:00:04.578             4.578
  Transport                     :  00-00:04:26.906           266.906
  Convection                    :  00-00:02:38.328           158.328
  Boundary layer mixing         :  00-00:04:20.156           260.156
  Dry deposition                :  00-00:00:06.859             6.859
  Wet deposition                :  00-00:01:10.187            70.188
  All diagnostics               :  00-00:05:20.875           320.875
  => HEMCO diagnostics          :  00-00:00:00.031             0.031
  => History (netCDF diags)     :  00-00:05:20.828           320.828
  Unit conversions              :  00-00:01:40.031           100.031
  Input                         :  00-00:00:29.796            29.797
  Output                        :  00-00:05:20.593           320.594
  Finalization                  :  00-00:00:07.531             7.531

SLURM JobID #         : 19093866
Job Name              : geoschem.profile.run
Submit time           : 2021-03-01 10:52:25
Start  time           : 2021-03-01 10:52:43
End    time           : 2021-03-01 11:40:46
Partition             : huce_casc+
Node                  : holy7c20501
CPUs                  : 48
Memory                : 0.0365 GB
CPU  Time             : 1-09:37:05  (     121025 s)
Wall Time             : 00:48:03    (       2883 s)
CPU  Time / Wall Time : 41.9788     ( 87.46% ideal)
```
### Dev
Branch: `feature/bmy/OmpCollapse`
Adds `!$OMP COLLAPSE(2)` to the parallel loop in flexchem_mod.F90 (on top of the updates in `feature/bmy/StreamlineKPP`). 
```
  Timer name                       DD-hh:mm:ss.SSS     Total Seconds
-------------------------------------------------------------------------------
  GEOS-Chem                     :  00-00:41:59.281          2519.281
  Initialization                :  00-00:00:41.234            41.234
  HEMCO                         :  00-00:07:28.359           448.359
  All chemistry                 :  00-00:15:39.750           939.750
  => FlexChem                   :  00-00:09:21.031           561.031
    -> FlexChem loop            :  00-00:09:05.625           545.625
    -> Init KPP                 :  00-00:00:06.799             6.800
    -> Het chem rates           :  00-00:00:46.804            46.805
    -> Photolysis rates         :  00-00:00:05.151             5.151
    -> KPP                      :  00-00:07:39.726           459.727
       RCONST                   :  00-00:00:37.106            37.107
       Integrate 1              :  00-00:06:45.545           405.546
    -> Prod/loss diags          :  00-00:00:03.875             3.876
  => FAST-JX photolysis         :  00-00:01:20.687            80.688
  => Aerosol chem               :  00-00:04:43.625           283.625
  => Linearized strat chem      :  00-00:00:02.937             2.938
  Transport                     :  00-00:04:29.046           269.047
  Convection                    :  00-00:02:43.140           163.141
  Boundary layer mixing         :  00-00:04:15.718           255.719
  Dry deposition                :  00-00:00:06.437             6.438
  Wet deposition                :  00-00:01:07.046            67.047
  All diagnostics               :  00-00:05:11.281           311.281
  => History (netCDF diags)     :  00-00:05:11.281           311.281
  Unit conversions              :  00-00:01:39.828            99.828
  Input                         :  00-00:00:28.937            28.938
  Output                        :  00-00:05:11.109           311.109
  Finalization                  :  00-00:00:07.671             7.672

SLURM JobID #         : 19092639
Job Name              : geoschem.profile.run
Submit time           : 2021-03-01 10:29:43
Start  time           : 2021-03-01 10:30:43
End    time           : 2021-03-01 11:14:04
Partition             : huce_casc+
Node                  : holy7c20412
CPUs                  : 48
Memory                : 0.0344 GB
CPU  Time             : 1-07:48:48  (     114528 s)
Wall Time             : 00:43:21    (       2601 s)
CPU  Time / Wall Time : 44.0323     ( 91.73% ideal)
```
So on 48 cores we see a 7-day run finished 5 minutes faster.  This will translate into about ~20 minutes of savings for a benchmark simualation.

Using the optimized rate-law functions in the Ref code translates into a ~20 minute savings over the existing rate law code.  Therefore using the optimized rate-law functions PLUS `!$OMP COLLAPSE(2)` should yield ~40 minutes of savings for runs done on 48 cores.

I recommend that we add this to 13.1.0 once the 13.0.0 benchmark clears the approval process.

**Comment by cdholmes** [comment]
That's good news! It's also very similar to my result of 32% faster on 50 cores.

I recommend using `!$OMP COLLAPSE(3)` instead of `!$OMP COLLAPSE(2)`, that is collapsing the I,J,L blocks, not just I,J. In my testing (see #497), collapse(3) is no slower than collapse(2) on a node with 50 CPUs and collapse(3) is more future proof as core counts continue to increase.

**Comment by yantosca** [comment]
That's a good idea.  We can do COLLAPSE(3).

**Comment by yantosca** [comment]
These results were obtained with `!$OMP COLLAPSE(3)` and `!$OMP DYNAMIC(24)`.  Slightly better than with `!$OMP COLLAPSE(2)` on 48 cores.

``` 
 Timer name                       DD-hh:mm:ss.SSS     Total Seconds
-------------------------------------------------------------------------------
  GEOS-Chem                     :  00-00:42:40.610          2560.610
  Initialization                :  00-00:01:23.507            83.508
  HEMCO                         :  00-00:08:15.147           495.147
  All chemistry                 :  00-00:15:38.144           938.145
  => FlexChem                   :  00-00:09:22.968           562.969
    -> FlexChem loop            :  00-00:09:07.123           547.123
    -> Init KPP                 :  00-00:00:06.573             6.574
    -> Het chem rates           :  00-00:00:46.634            46.635
    -> Photolysis rates         :  00-00:00:04.959             4.960
    -> KPP                      :  00-00:07:43.241           463.242
       RCONST                   :  00-00:00:36.684            36.685
       Integrate 1              :  00-00:06:49.536           409.537
    -> Prod/loss diags          :  00-00:00:03.787             3.788
  => FAST-JX photolysis         :  00-00:01:21.102            81.103
  => Aerosol chem               :  00-00:04:39.871           279.871
  => Linearized strat chem      :  00-00:00:02.858             2.858
  Transport                     :  00-00:04:27.424           267.425
  Convection                    :  00-00:02:40.843           160.844
  Boundary layer mixing         :  00-00:04:10.943           250.943
  Dry deposition                :  00-00:00:06.427             6.428
  Wet deposition                :  00-00:01:07.603            67.604
  All diagnostics               :  00-00:05:12.085           312.086
  => HEMCO diagnostics          :  00-00:00:00.008             0.009
  => History (netCDF diags)     :  00-00:05:12.070           312.070
  Unit conversions              :  00-00:01:39.508            99.509
  Input                         :  00-00:00:33.975            33.976
  Output                        :  00-00:05:11.923           311.924
  Finalization                  :  00-00:00:07.548             7.549

SLURM JobID #         : 19163370
Job Name              : geoschem.profile.run
Submit time           : 2021-03-02 10:33:59
Start  time           : 2021-03-02 10:34:40
End    time           : 2021-03-02 11:18:46
Partition             : huce_casc+
Node                  : holy7c20503
CPUs                  : 48
Memory                : 0.0436 GB
CPU  Time             : 1-08:08:29  (     115709 s)
Wall Time             : 00:44:06    (       2646 s)
CPU  Time / Wall Time : 43.7298     ( 91.10% ideal)

```

**Comment by yantosca** [comment]
I am closing this PR because it is now superseded by #663.

**Pull request closed without merging**
