### PR TITLE
HETP aerosol thermodynamics

### PR DESCRIPTION
**Pull request by lizziel**
### Name and Institution (Required)

Lizzie Lundgren (Harvard) with contributor Seb Eastham (ICL)

### Describe the update

This PR replaces use of the ISOROPPIA II aerosol thermodynamics package with [HETPv1.0](https://github.com/geoschem/HETerogeneous-vectorized-or-Parallel). HETPv1.0 is a new git submodule within GC-Classic and GCHP code repositories. Updates in this PR interface with the new library. From the HETP README:

> HETP is an aerosol thermodynamic equilibrium solver written in modern Fortran based on ISORROPIA II (which is written in FORTRAN 77).  HETP solves only the 'forward' metastable state of the NH4+/Na+/Ca2+/K+/Mg2+/SO42–/NO3–/Cl–/H2O system.  The main publication for HETP is avaiable online at:  https://gmd.copernicus.org/preprints/gmd-2023-159/.

ISORROPIA may still be turned on in this update by changing `use_hetp` to from true to false in `geoschem_config.yml`. This will be removed in a future update.

### Expected changes

Preliminary 1-month full chemistry benchmarks comparing ISORROPIA with HETPv1.0 in GEOS-Chem are posted [here](https://ftp.as.harvard.edu/gcgrid/geos-chem/validation/isorropia_vs_hetp/1mon_fullchem/).

### Reference(s)

See https://gmd.copernicus.org/articles/17/2197/2024/gmd-17-2197-2024-discussion.html

### Related Github Issue(s)

- GEOS-Chem Issue: https://github.com/geoschem/geos-chem/issues/2235
- GC-Classic PR: https://github.com/geoschem/GCClassic/pull/55
- GCHP PR: https://github.com/geoschem/GCHP/pull/408

### CODE REVIEW

**Comment by yantosca** [comment]
@lizziel: Try this:

```F90
    !========================================================================
    ! Loop over grid boxes and call ISORROPIA (see comments in the
    ! ISORROPIA routine ISORROPIAIICODE.f which describes
    ! the input/output args)
    !========================================================================
    !$OMP PARALLEL DO                                                        &
    ...
    !$OMP SCHEDULE( DYNAMIC, 8                                             ) &
    !$OMP COLLAPSE( 3                                                      )
```
The schedule(dynamic, 8) will work on 8 grid boxes at a time per thread, and then whichever thread finishes will grab the next 8 in the sequence.  The collapse clause will vectorize the 3 loops so that more grid boxes will be worked on simultaneously.  Normally only the outer loop is parallelized.

**Comment by lizziel** [comment]
Thanks @yantosca! That does make a difference for GC-Classic runs. Performance for GCHP is comparable between ISORROPIA and HETP.

**Comment by lizziel** [comment]
This PR passes integrations tests but I have not yet deleted ISORROPIA II. I will change to Ready For Review once that is done.

**Comment by lizziel** [comment]
Integration tests are failing for the aerosol-only and the APM runs due to a seg fault within HETP. I am investigating if special handling is needed for these simulations.

**Comment by lizziel** [comment]
The fixes in HETP are simple and I will rerun integration tests once pushed. No updates are needed in GEOS-Chem, GC-Classic, or GCHP repos.

**Review by yantosca — CHANGES_REQUESTED** [review]
Hi @lizziel! Thanks for this.  It looks good to merge.  We just need the CHANGELOG.md update.

**Review by yantosca — APPROVED** [review]
Good to merge @lizziel!  I will start testing.

**Comment by yantosca** [comment]
After merging (locally) atop 14.4.0-alpha.14, all GEOS-Chem Classic integration tests passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

GCClassic #1bb3cba Merge PR #55 (HETP aerosol thermodynamics)
GEOS-Chem #90da22bed Merge PR #2244 (HETP aerosol thermodynamics)
HEMCO     #fddcae5 Update version to 3.8.1 for release

Using 24 OpenMP threads
Number of execution tests: 29

Submitted as SLURM job: 29752983
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
All GCHP integration tests also passed:
```console
==============================================================================
GCHP: Execution Test Results

GCHP      #9d35f08 Merge PR #408 (HETP aerosol thermodynamics)
GEOS-Chem #90da22bed Merge PR #2244 (HETP aerosol thermodynamics)
HEMCO     #9d35f08 Merge PR #408 (HETP aerosol thermodynamics)

Number of execution tests: 11

Submitted as SLURM job: 30031320
==============================================================================
 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Pull request merged**
