### PR TITLE
[PULL REQUEST] HEMCO intermediate processing grid feature (Batch 1)

### PR DESCRIPTION
**Pull request by jimmielin**
Hi GCST,

This update includes the HEMCO 3.0 planned feature, the "HEMCO Intermediate Grid", which allows HEMCO to operate on a different grid than the GC-Classic simulation, at runtime. The update is rather hefty and here goes a quick summary of what's happening under the hood:

## Changes summary
* The intermediate grid feature is controlled by three new input options, `Input_Opt%IMGRID_XSCALE`, `Input_Opt%IMGRID_YSCALE`, which defines the refinement scale for the HEMCO grid (setting them to 2, 2 means that HEMCO works on 1x1.25 on a 2x2.5 simulation). This number is **hardcoded** as 1, 1 (= do nothing) under `hco_interface_gc_mod.F90` right now because the feature requires testing and validation and its best kept hidden for now. If any of the scales are not equal to 1, then `Input_Opt%LIMGRID` is enabled, which enables the intermediate grid feature. In the future these should be switches in `input.geos` but they are not implemented yet as the feature has not passed scientific validation.

* The HEMCO grid is described in `State_Grid_HCO` stored in `hco_state_gc_mod.F90`. It reuses the `GrdState` nicely. Generation of a "refined"/scaled grid is using the new subroutine `gc_grid_mod.F90 : Compute_Scaled_Grid`.

* The main idea: Data is stored in HEMCO resolution in `HcoState` as usual, and only regridded on-demand. The regridded data lies in **a single buffer** (actually, two.) (`TMP_MDL` in `hco_utilities_gc_mod.F90`) which is updated when a new field is requested via the new `HCO_GC_*` subroutines below...

* **Everything** intermediate-grid related is wrapped in `MODEL_CLASSIC` and `IF ( Input_Opt%LIMGRID )` checks. There are minor changes to the code that affect all simulations, though:
  * All calls to `HCO_GetPtr` should now be `HCO_GC_GetPtr`, implemented in `hco_utilities_gc_mod.F90`.
  * All calls to `HCO_EvalFld` should now be `HCO_GC_EvalFld`.
  * All calls to `GetHcoDiagn` should now be `HCO_GC_GetDiagn`.
  * The above calls redirect to their in-HEMCO counterparts when intermediate grid is disabled. Nothing new happens.
  * `Compute_Sflx_For_Vdiff` has been moved to `hco_interface_gc_mod.F90` due to circular dependency.
  * Loop orders in `mixing_mod.F90 : DO_TEND` and `hco_interface_gc_mod.F90 : Compute_Sflx_For_Vdiff` have been switched slightly: the species loop must be outermost, as HEMCO intermediate grid only stores up to one species in the "regridded" memory buffer, so species must be read contiguously before moving on to the next.
  * **The changes above have been validated to minimal differences, attributed to switch of some precisions from f4 to fp, and optimization changes due to change of loop orders.** See attached log below.

* When intermediate grid is enabled, the above `HCO_GC_*` calls retrieves data from HEMCO, **compares it against the buffer**, and regrids as necessary, discarding old data in the buffer. Why a buffer? Because some calls to `HCO_GetPtr` expect a `POINTER` and do their own data copying. To maximize compatibility, they're given the temporary buffer to point to. **Care should be taken to "update" these pointers at every time step now, as they won't be pointing to the right things if the data wasn't copied from them before the next `HCO_GC_*` call.** I've checked **all** the places in G-C that do this and changed everywhere, **except** `strat_chem_mod.F90`, pending decision on tropchem.

* Detailed list of changes below. I've also fixed some debug messages as I went probing through the entire GC source.

### Structural changes (validated to "zero" diff, see below, when IMGrid is not enabled):
- Implements a new Input_Opt field LIMGRID to indicate intermediate grid functionality.
- Reads HEMCO extension met fields from HEMCO state when possible
- Remove `FRAC_OF_PBL` duplicate and read through `State_Met`.
- Add `IMGRID_XSCALE`, `IMGRID_YSCALE` HEMCO grid scaling (refinement) factors to `Input_Opt`.
- Move `SUMCOSZA` to `State_Met%SUNCOSsum`.
- Move `Calc_SUMCOSZA` to `Calc_Met_Mod`.
- Move Read_Met_Fields to HCO_Interface_GC_Mod to avoid circular dependencies.
- Add `State_Grid_HCO` to store HEMCO grid state in `HCO_State_GC_Mod`.
- Modified method signatures in a few subroutines to accept Input_Opt, State_Grid.
- Add `InquireHco` subroutine in `HCO_GC_Utilities_Mod` for checking if given species has Deposition/Emissions, instead of calling with I,J,L=1 to retrieve data for probing.
- Now use `EmisSpec`, `DepSpec` in `Compute_Sflx_For_Vdiff` which retrieves a species is emis/dep enabled or not from the `InquireHco` subroutine, to save CPU.
- Moved `Compute_Sflx_For_Vdiff` from `HCO_Utilities_GC_Mod` to `HCO_Interface_GC_Mod` to avoid a circular dependence issue (the subroutine depends on Global_CH4 and Global_Br)
- Now read `PNOXLOSS_O3` and `PNOXLOSS_HNO3` diagnostics in `MIXING_MOD` and `COMPUTE_SFLX_FOR_VDIFF` at every time step, in preparation of HEMCO changes.
- Add `HCO_GC_GetDiagn` interface in HCO_Utilities_GC_Mod. It is a shim for `GetHcoDiagn` in `HCO_Interface_Common`, performing on-demand regrid when IMGrid is enabled.
- Add a secondary R4 buffer for model regridded data.
- Fixed wrong output type and added extra out variables for N_/L2_L2-cutoff error in `FAST_JX_Mod`.
- Add a debug message for `Compute_Sflx_for_Vdiff` in `MAIN.F90`

### Functionality changes, all MODEL_CLASSIC:
- Add intermediate grid assignment in `HCOI_GC_Init`.
- Add intermediate grid variables and allocation in `HCO_Interface_GC_Mod`.
- Add `Compute_Scaled_Grid` to compute refined grid based on State_Grid in `GC_Grid_Mod`.
- Add on-demand regridding functionality for `GetHcoValDep`, `GetHcoValEmis` in `HCO_Utilities_GC_Mod`.
- Add on-demand regridding shim HCO_GC_GetPtr in HCO_Utilities_GC_Mod.
- Add on-demand regridding shim HCO_GC_EvalFld in HCO_Utilities_GC_Mod.
- Use on-demand regridding for reading met fields in FlexGrid and HCO modules.
- Use on-demand regridding in a variety of modules that used HCO_GetPtr.
- Use on-demand regridding for various modules (TOMS_MOD, TAGGED_O3, TAGGED_CO, Sulfate_Mod, SfcVmr_Mod)
- Use on-demand regridding for various modules (RPMARES_Mod, ISORROPIAII_Mod, Global_CH4_Mod, Global_Br_Mod)
- Use on-demand regridding for various modules (Aerosol_Mod, Carbon_Mod)
- Use `HCO_GC_EvalFld` for OLSON_LANDMAP_MOD and MODIS_LAI_MOD.
- Use on-demand regridding for Global_CH4_Mod::EmissCH4, Land_Mercury_Mod::BIOMASSHg, Mercury_Mod
- Use on-demand regridding for Sulfate_Mod HEMCO diagnostics

## Difference test output
Only nonzero species attached.
Comparison was made against **GEOS-Chem Classic "Wrapper"**, with GEOS-Chem Classic commit `28aa0358` in `dev/13.0.0`.

```
Variable               Ref=geosfp_2x25_standard Dev=dev_geosfp_2x25_standard Dev-Ref
SpeciesConc_Br2      : 1.3926416e-07          | 1.3926413e-07          | -2.842170943040401e-14
SpeciesConc_HI       : 5.0519042e-09          | 5.0519047e-09          | 4.440892098500626e-16
SpeciesConc_HNO3     : 0.0009782148           | 0.0009782154           | 5.820766091346741e-10
SpeciesConc_IHN4     : 1.115168e-09           | 1.1151681e-09          | 1.1102230246251565e-16
SpeciesConc_INPB     : 4.9958273e-09          | 4.995828e-09           | 8.881784197001252e-16
SpeciesConc_LVOC     : 2.276081e-10           | 2.2760828e-10          | 1.8041124150158794e-16
SpeciesConc_NH3      : 2.5541443e-05          | 2.5541423e-05          | -2.000888343900442e-11
SpeciesConc_NIT      : 9.795141e-06           | 9.7945585e-06          | -5.820766091346741e-10
```

Please feel free to squash the commits and let me know of any questions regarding this implementation... Apologies in advance for a 6,000 line commit in one PR. Hopefully there aren't *too many* merge conflicts. All changes are under the hood if the functionality isn't enabled at code level in `hco_interface_gc_mod.F90` to set the `XSCALE`/`YSCALE` to non-1 value, so afterwards GEOS-Chem should look and work like GEOS-Chem as usual. 

Have a nice day 😄
Haipeng

### CODE REVIEW

**Comment by lizziel** [comment]
Thanks @jimmielin . Since the intermediate grid feature is going into 13.1 we would like to bring this PR in after we release 13.0. There are several updates still in progress for 13.0 that might be tricky to merge in if there are extensive structural changes that go in first. Would it be okay for you to merge the official 13.0 release into your intermediate grid branch and then do the intermediate grid PR when it is ready?

**Comment by msulprizio** [comment]
Daniel Jacob expressed some concerns bringing these updates into GEOS-Chem 13.1.0 saying there may be a significant slowdown introduced with the HEMCO intermediate grid -- is this still the case @jimmielin ?

**Comment by jimmielin** [comment]
Hi Melissa @msulprizio yes, there are some performance concerns with these updates *if the intermediate grid feature is enabled* (`input_opt%imgrid_xscale .ne. 1 .and. Input_Opt%IMGrid_YScale .ne. 1`). Otherwise, these are structural changes for supporting the restructuring of the GEOS-Chem-HEMCO interface in HEMCO 3.0 and should give zero-diff and negligible performance change.

The concern is that doubling HEMCO resolution quadruples HEMCO wall time, a trivial conclusion, but a significant performance hit. Perhaps there could be somewhere we can better optimize in HEMCO, so it scales better. I'm not sure how to improve this however, I will have to look into this. 

Whether it is possible to merge into 13.1.0 or a later version depends on the approximate timeline of 13.1.0 and future releases. Could the GCST shine a light on an approximate time frame?

It's also notable that the changes are extensive and it would be a little hard to do some of these down the line if the main GC branch diverges too much from the base here. But if all else fails I can make a "toned down" version of this with just the subroutine call changes, but no intermediate grid, then add that feature in later. But it is equivalent to hiding the feature by setting `Input_Opt%IMGrid_XScale = 1.0`)

Thanks!

**Comment by msulprizio** [comment]
Thanks for the update @jimmielin. The GCST plans to start work on 13.1.0 in February, but we are still awaiting guidance from the Steering Committee on exactly which updates they would like in 13.1, 13.2, and 13.3 -- one version will likely be dedicated to chemistry updates, one to emission updates, etc.

**Comment by lizziel** [comment]
Hi @jimmielin, I'm starting to work on bring this into 13.1. Could you tell me what GEOS-Chem version you originally built this PR off of?

**Comment by jimmielin** [comment]
Hi Lizzie, thank you! This was based off GEOS-Chem repo commit https://github.com/geoschem/geos-chem/commit/fdb023aa (I think it was a development copy of 13.0.0).

It was built against HEMCO commit 3d405d5f (https://github.com/geoschem/HEMCO/tree/3d405d5f) and GC-Classic wrapper (https://github.com/geoschem/GCClassic/commit/8c875417)

**Comment by lizziel** [comment]
Thanks! Would you be able to rebase on the most recent main? I suspect a lot of the conflicts would be simple for you to resolve. Any remaining you can leave in the branch for me to look at.

**Comment by jimmielin** [comment]
Hi @lizziel yes of course - I'll work on this as soon as I can. I'll update this PR when this is done!

**Comment by lizziel** [comment]
Thanks @jimmielin! No need to spend a ton of time on it since I can help with conflict resolution as well. I would just like to proceed in the way that is most efficient. If you have merge conflicts you are unsure of please let me know.

**Comment by lizziel** [comment]
@jimmielin, do you have a time estimate for when you will get to this? If you don't have time in the next week let me know.

**Comment by jimmielin** [comment]
Hi @lizziel thanks for the follow-up! I'm working through the rebase conflicts right now and should get a preliminary version out by Wednesday/Thursday, then we might have to check that it generates zero differences when disabled and then check if it works when enabled. I'll keep you updated on the progress!

**Comment by lizziel** [comment]
Sounds good. Just let me know when the conflicts are resolved and I'll bring in to test.

**Comment by jimmielin** [comment]
Hi @lizziel I just finished resolving the conflicts but I will need a day or two to test it. To avoid any issues though I did the rebase in a new branch (https://github.com/jimmielin/geos-chem/tree/feature/13.0.0%2Bhgrid%2Brbs) like

```bash
git checkout -b feature/13.0.0+hgrid+rbs
git rebase upstream/main
```

I'm not sure if it is possible to switch GitHub pull requests to a different branch. Or maybe opening a new one is cleaner? If not possible, I can always open a new pull request from the new branch and update you when it compiles and tests mostly OK. Thanks!

Best,
Haipeng

**Comment by lizziel** [comment]
Great, thanks so much! Opening a new PR is simplest. Let me know what tests you end up doing. I will do additional testing but don't want to duplicate.

**Pull request closed without merging**
