### PR TITLE
[WIP] Implement Hg chemistry via KPP

### PR DESCRIPTION
**Pull request by yantosca**
This is a work in progress PR where we can document the progress of the Hg simulation via KPP in GEOS-Chem.

So far, I have been able to get GEOS-Chem to build either fullchem or Hg with KPP.  The KPP simulation will need some extra testing and some modifications.  Also, I am not sure the Hg emissions are correct for this simulation.

Taggjng @msl3v and @viral211  -- please feel free to comment further.

### CODE REVIEW

**Comment by yantosca** [comment]
A couple of notes: To build the Hg simulation:
 ```console
$ cd build
$ cmake ../CodeDir -DRUNDIR=.. -DMECH=Hg
$ make -j install
```
also to simplify the coding, the prefix `gckpp_` is used for both fullchem or Hg...this is so that routines can refer to e.g. `USE gckpp_Global` throughout the code.  The way I got around this was to create stub modules with empty routines that are not used.  This was needed to avoid compilation issues.

**Comment by yantosca** [comment]
@viral211: In the HEMCO_Config.rc file for Hg, we place emissions into Hg2 and HgP.  But in the new Hg code, we do not have these species.  Could you help me to edit the HEMCO_Config.rc file accordingly?

https://github.com/geoschem/geos-chem/blob/main/run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.Hg

**Comment by yantosca** [comment]
Also tagging @CharikleiaGRN, who is interested in the Hg simulation with KPP.

**Comment by yantosca** [comment]
> in the new mechanism Hg2 and HgP are emitted as HgCl2 and Hg2ClP. There is a difference in the MWs of these species and to prevent HEMCO from automatically scaling the emissions by the ratio of the MW, I had to replace `kg/m2/s` with `*`.

Thanks @viral211.  This seems to work with HEMCO:

https://github.com/geoschem/geos-chem/blob/feature/Hg-with-kpp/run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.Hg

Just that I think we need to disable the manual diagnostics as we have them from the old code.

**Comment by yantosca** [comment]
Also tagging @jennyfisher @cdholmes @yanxuz @djxjacob @noelleselin @cpthackray on this thread.

I have the Hg with KPP simulation implemented into KPP in the `feature/Hg-with-kpp` branch.  It seems to work OK for a few days but then it dies with a wet deposition error (maybe we have a reaction rate or other numerical computation blowing up somewhere, we'll have to see).  If you would like to test this simulation, then here are the download instructions:

Download GEOS-Chem
```console
$ git clone -b feature/Hg-with-kpp https://geoschem/geos-chem/GCClassic.git
$ git submodule update --init --recursive
```
Create a run directory for Hg
```console
$ cd GCClassic/run
$ ./createRunDir.sh
5                # Picks Hg simulation
1                # Picks MERRA2
1                # Picks 4x5
1                # Picks 72 levels
/path/to/rundir  # Specify path to run directory
rundir-name      # Specify rundir name
y                # Use Git to save rundir files
```
Configure & build
```console
$ cd /path/to/rundir/rundir-name
$ cd build
$ cmake ../CodeDir -DRUNDIR=.. -DMECH=Hg   # This picks the KPP Hg mechanism!
$ make -j
$ make -j install
$ cd ..
```
Then you can proceed to run GEOS-Chem. 

Please feel free to add more comments, bug reports, etc. to this Github thread.  Thanks so much!

**Comment by yantosca** [comment]
FYI, there might be a parallelization error in this implementation.  If TPCORE transport is turned on I get different results with different numbers of cores (8 vs. 2):

8 cores, Hg0 mass after 1st TPCORE call
```$console
N=1   2.5955673032980585E-010
```
2 cores, Hg0 mass after 1st TPCORE call
```console
N=1   2.3334845032950285E-010
```
and other species snow similar differences.  They should be identical as both codes are on the same commit.

I can look into this after I get back from the Winter Recess.

**Comment by yanxuz** [comment]
Thanks Bob for looking into this. What do you mean by “other species”? Other Hg species or species in standard full chemistry?

Best,
Yanxu

**Comment by yantosca** [comment]
> Thanks Bob for looking into this. What do you mean by “other species”? Other Hg species or species in standard full chemistry? Best, Yanxu

The other Hg species in the simulation.

**Comment by Jampo26** [comment]
I have checked out the feature/Hg-with-kpp branch and running 1 year (2019) for testing. But there seems to be something wrong with the model's results：
1) The variables in **GEOSChem.MercuryEmis.*z.nc4** are all zeros.
2) The surface and vertical distribution of Hg0 concentration looks normal, but HgII species are abnormal. This also causes the total wet deposition of HgII species only occurs in land and rarely in the ocean, which is inconsistent with the current situation.
Is it that the current branch is not yet debugged for the Hg simulation? Tagging @yantosca @jennyfisher @cdholmes @yanxuz @noelleselin @cpthackray.
Thanks!

**Comment by yantosca** [comment]
Further discussion has been moved to https://github.com/geoschem/geos-chem/discussions/1084

**Pull request merged**
