### PR TITLE
Updated the KPP/custom mechanism files so that it builds out-of-the-box -- Closes #1332

### LINKED ISSUE #1332: [BUG/ISSUE]Errors when compiling custom mechanism in the GEOS-Chem version 13.4.1
Hi there,

This is Lixu from The university of Montana. I was trying to customize chemistry mechanism by adding Furans in GEOS-Chem version 13.4.1. When I was tring to compile the custom mech by using make -j in the build directory, I got the error information below:
```
/home/lj152920/GEOS-CHEM/rundirs/GC13.4.1/FUR_custom/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90(2441): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [ACIDUPTAKE_DUSTCHEMFUNCS]
    USE aciduptake_DustChemFuncs, ONLY : aciduptake_InitDustChem
--------^
/home/lj152920/GEOS-CHEM/rundirs/GC13.4.1/FUR_custom/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90(2441): error #6580: Name in only-list does not exist or is not accessible.   [ACIDUPTAKE_INITDUSTCHEM]
    USE aciduptake_DustChemFuncs, ONLY : aciduptake_InitDustChem
-----------------------------------------^
compilation aborted for /home/lj152920/GEOS-CHEM/rundirs/GC13.4.1/FUR_custom/CodeDir/src/GEOS-Chem/GeosCore/fullchem_mod.F90 (code 1)
make[2]: *** [src/GEOS-Chem/GeosCore/CMakeFiles/GeosCore.dir/fullchem_mod.F90.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/lj152920/GEOS-CHEM/rundirs/GC13.4.1/FUR_custom/CodeDir/src/GEOS-Chem/GeosCore/mercury_mod.F90(3708): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [HG_HETSTATEFUNCS]
    USE Hg_HetStateFuncs, ONLY : Hg_SetStateHet
--------^
/home/lj152920/GEOS-CHEM/rundirs/GC13.4.1/FUR_custom/CodeDir/src/GEOS-Chem/GeosCore/mercury_mod.F90(3786): error #6632: Keyword arguments are invalid without an explicit interface.   [I]
         I          = I,                                                     &
---------^
/home/lj152920/GEOS-CHEM/rundirs/GC13.4.1/FUR_custom/CodeDir/src/GEOS-Chem/GeosCore/mercury_mod.F90(3787): error #6632: Keyword arguments are invalid without an explicit interface.   [J]
         J          = J,                                                     &
---------^
/home/lj152920/GEOS-CHEM/rundirs/GC13.4.1/FUR_custom/CodeDir/src/GEOS-Chem/GeosCore/mercury_mod.F90(3788): error #6632: Keyword arguments are invalid without an explicit interface.   [L]
         L          = L,                                                     &
---------^
/home/lj152920/GEOS-CHEM/rundirs/GC13.4.1/FUR_custom/CodeDir/src/GEOS-Chem/GeosCore/mercury_mod.F90(3789): error #6632: Keyword arguments are invalid without an explicit interface.   [INPUT_OPT]
         Input_Opt  = Input_Opt,                                             &
---------^
/home/lj152920/GEOS-CHEM/rundirs/GC13.4.1/FUR_custom/CodeDir/src/GEOS-Chem/GeosCore/mercury_mod.F90(3790): error #6632: Keyword arguments are invalid without an explicit interface.   [STATE_CHM]
         State_Chm  = State_Chm,                                             &
---------^
/home/lj152920/GEOS-CHEM/rundirs/GC13.4.1/FUR_custom/CodeDir/src/GEOS-Chem/GeosCore/mercury_mod.F90(3791): error #6632: Keyword arguments are invalid without an explicit interface.   [STATE_MET]
         State_Met  = State_Met,                                             &
---------^
/home/lj152920/GEOS-CHEM/rundirs/GC13.4.1/FUR_custom/CodeDir/src/GEOS-Chem/GeosCore/mercury_mod.F90(3792): error #6632: Keyword arguments are invalid without an explicit interface.   [H]
         H          = State_Het,                                             &
---------^
/home/lj152920/GEOS-CHEM/rundirs/GC13.4.1/FUR_custom/CodeDir/src/GEOS-Chem/GeosCore/mercury_mod.F90(3793): error #6632: Keyword arguments are invalid without an explicit interface.   [FRACORGAER]
         fracOrgAer = GLOB_FOA(I,J,L),                                       &
---------^
/home/lj152920/GEOS-CHEM/rundirs/GC13.4.1/FUR_custom/CodeDir/src/GEOS-Chem/GeosCore/mercury_mod.F90(3794): error #6632: Keyword arguments are invalid without an explicit interface.   [RC]
         RC         = RC                                                     )
---------^
/home/lj152920/GEOS-CHEM/rundirs/GC13.4.1/FUR_custom/CodeDir/src/GEOS-Chem/GeosCore/mercury_mod.F90(3708): error #6580: Name in only-list does not exist or is not accessible.   [HG_SETSTATEHET]
    USE Hg_HetStateFuncs, ONLY : Hg_SetStateHet
---------------------------------^
compilation aborted for /home/lj152920/GEOS-CHEM/rundirs/GC13.4.1/FUR_custom/CodeDir/src/GEOS-Chem/GeosCore/mercury_mod.F90 (code 1)
make[2]: *** [src/GEOS-Chem/GeosCore/CMakeFiles/GeosCore.dir/mercury_mod.F90.o] Error 1
make[1]: *** [src/GEOS-Chem/GeosCore/CMakeFiles/GeosCore.dir/all] Error 2
make: *** [all] Error 2
```
The only two things I modified are the eqn and kpp file in the .../src/GEOS-Chem/KPP/custom directory. I tried to find simlilar error in github but with no luck. To reproduce the error information, you may need to use custom.eqn and custom.kpp I used, which are attached.
[custom.kpp.txt](https://github.com/geoschem/geos-chem/files/9253500/custom.kpp.txt)
[custom.eqn.txt](https://github.com/geoschem/geos-chem/files/9253502/custom.eqn.txt)

Any inputs or insights will be appreciated
-Lixu

### PR DESCRIPTION
**Pull request by yantosca**
This will fix the issue reported in #1332.  Some of the new modifications in KPP/fullchem were not applied to KPP/custom, and this PR should now address this.

  - Added stub files so that the custom mechanism will build
  - Added symbolic links to ../fullchem/fullchem_*.F90 files
  - Added the commonIncludeVars.H file
  - Copied custom.kpp from fullchem.kpp (and changed name to custom.kpp)
  - Copied custom.eqn from fullchem.eqn (and changed name to custom.eqn)
  - Rebuilt KPP/custom mechanism with KPP 2.5.0

With this update, one can run the custom mechanism out-of-the-box.  This can be a starting point for further mechanism development.

### CODE REVIEW

**Review by msulprizio — COMMENTED** [review]
In the past, we've placed files needed to build a custom mechanism in the custom directory without actually building the mechanism (i.e. creating all of the .F90 files). Is there a reason to build the custom mechanism here or would it be simpler/cleaner to just included files needed and allow users to build it on their own?

**Comment by yantosca** [comment]
@msulprizio:  That's a good point.  We did need the updated .kpp and .eqn file, as well as the symbolic links for it to compile.  I can remove the gckpp*.F90 files.

**Review by msulprizio — APPROVED** [review]
Great. This looks ready to merge now.

**Comment by yantosca** [comment]
Also updated the README.md files accordingly.

**Comment by yantosca** [comment]
GEOS-Chem Classic integration tests all passed except for the CO2 simulation:

```console
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 47
Execution tests failed: 1
Execution tests not yet completed: 0
```
The error in the CO2 simulation was tracked down to an incorrect entry in `HEMCO_Config.rc` for `CEDS_CO2_SHP`, and has now been fixed in #1356.

**Pull request merged**
