### PR TITLE
[PULL REQUEST] Fix parallelization issue in sulfate chemistry (plus other fixes for numerical stability)

### PR DESCRIPTION
**Pull request by yantosca**
## Overview
This PR should fix the remaining parallelization issues in GEOS-Chem.  This is now fixed by commit a4bad12074a61765324c63fc2bbbbf4edae4e9fe.

Long story short: In the OpenMP parallel loop in `fullchem_mod.F90`, we were storing the value of the variable `size_res` (which was declared `!$OMP PRIVATE`) into `State_Chm%size_res` (which was not `!$OMP PRIVATE`) in `fullchem_SulfurChemFuncs.F90`. Then the value of `State_Chm%size_res` was passed back to `fullchem_mod.F90`, and was used to determine whether or not the `fullchem_HetDropChem` routine needed to be called.  Thus, the value of `State_Chm%size_res` was thus being overwritten simultaneously by competing threads in an unpredictable manner, showing up as very small numerical differences when comparing simulations using different numbers of threads,

## Solution
We now avoid storing the value of `size_res` in `State_Chm`.  We pass `size_res` explicitly as an output argument from `fullchem_SulfurChemFuncs.F90` back to `fullchem_mod.F90` so that it can preserve the `!$OMP PRIVATE` status. 

We have obtained identical results on short GEOS-Chem simulations using 1, 5, and 8 cores.

## Other modifications included with this pull request:

  1. Added updates for numerical stability to `seasalt_mod.F90`
  2. Added updates for readability into `chemistry_mod.F90`
  3. Added updates for numerical stability into `pjc_pfix_mod.F90`

### CODE REVIEW

**Comment by yantosca** [comment]
Integration tests pending

**Comment by yantosca** [comment]
Now also included in this PR are the modifications from #1189.  This will allow us to test them all together.

**Comment by yantosca** [comment]
All GCHP integration tests passed.  Waiting on GCClassic results
```console
==============================================================================
GCHP: Execution Test Results

Number of execution tests: 3
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gchp_fullchem_benchmark_merra2_c48...............Execute Simulation.....PASS
gchp_fullchem_standard_merra2_c24................Execute Simulation.....PASS
gchp_TransportTracers_geosfp_c24.................Execute Simulation.....PASS
 
Summary of execution test results:
------------------------------------------------------------------------------
Execution tests passed:        3
Execution tests failed:        0
Execution tests not completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
The GEOS-Chem Classic Hg simulation failed.  Investigating:
```console
gc_2x25_Hg_merra2................................Execute Simulation.....FAIL
```

**Comment by yantosca** [comment]
The HEMCO_Config.rc for the Hg simulation is now missing several global oxidant fields.  Investigating.

**Review by msulprizio — APPROVED** [review]
This PR looks fine to merge

**Comment by yantosca** [comment]
GEOS-Chem Classic integration tests (except Hg simlations) all passed:

```console
gc_2x25_Hg_merra2................................Execute Simulation.....FAIL
gc_4x5_Hg_geosfp.................................Execute Simulation.....FAIL
gc_4x5_Hg_merra2.................................Execute Simulation.....FAIL

Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 45
Execution tests failed: 3
Execution tests not yet completed: 0
```
This is expected due to the issues discovered and documented in #1192.

**Pull request merged**
