### PR TITLE
Updates associated with wet scavenging in Luo et al. (GMD-12-3439-2019).

### PR DESCRIPTION
**Pull request by ganluoasrc**
All changes associated with this updates are marked with GanLuo.

### CODE REVIEW

**Comment by yantosca** [comment]
This PR has failed in [the TravisCI build](https://travis-ci.org/geoschem/geos-chem/builds/598689000?utm_source=slack&utm_medium=notification)

I think the issue is that gfortran chokes if you try to do e.g. A**-1d0.  You need to put parentheses around the exponent in that case, e.g. A**(-1d0).  Or maybe even more efficiently, 1d0/A will avoid a costly exponentiation.

**Comment by ganluoasrc** [comment]
> 
> 
> This PR has failed in [the TravisCI build](https://travis-ci.org/geoschem/geos-chem/builds/598689000?utm_source=slack&utm_medium=notification)
> 
> I think the issue is that gfortran chokes if you try to do e.g. A**-1d0. You need to put parentheses around the exponent in that case, e.g. A**(-1d0). Or maybe even more efficiently, 1d0/A will avoid a costly exponentiation.

**Comment by yantosca** [comment]
Hi Gan,  I noticed you closed the pull request.  Is it ready to merge, or are there still some open issues?

**Comment by ganluoasrc** [comment]
Hi Bob,

I thought I have sent the pull request which fixed the compiling error massage for gfortran. I will check it.

Best

Gan
________________________________

**Comment by yantosca** [comment]
The pull request is here but for some reason it's closed.  I can try to grab it into a branch of  my code.

**Comment by ganluoasrc** [comment]
The code is ready to be merged. Last time, we stopped at the errors at line 2284-2287 in wetscav_mod.F.

Best

Gan
________________________________

**Comment by yantosca** [comment]
This update has been pushed to feature/GanLuoWetdep on github.  I made several changes to the base pull request and will be running diff tests.

**Comment by yantosca** [comment]
I have brought this code into GEOS-Chem (branch: feature/GanLuoWetdep), so that the Luo et al wetdep scheme will be activated when compiling with GNU Make:
```
make LUO_WETDEP=y 
```
or CMake:
```
cmake ../CodeDir -DLUO_WETDEP=y
make install
```
I'm currently performing unit tests and difference tests to further scan for errors and also make sure that using the default wetdep scheme gives identical results to the prior code.

**Comment by yantosca** [comment]
Difference tests w/r/t the parent commit show identical results.  This means that the existing default wetdep scheme was not affected by the addition of the Luo et al wetdep scheme. 

I am also running a unit test with LUO_WETDEP=y to check if there are any further errors when activating the Luo et al wetdep.

**Comment by yantosca** [comment]
Unit tests with LUO_WETSCAV=y pass, except for the geosfp_025x025_tropchem_na simulation.  The problem is that the default boundary condition files that come with the unit tester do not have the extra species included in the small alkyl nitrate mechanism.  I will interpret this as the unit tests passing, so we can merge this into dev/12.7.0.

NOTE: There are probably going to be some more updates to this scheme in the near future (as discussed at the [GCSC Nov 4th telecon](http://acmg.seas.harvard.edu/geos/word_pdf_docs/steering_cmte/gc_sc_minutes_04Nov2019.pdf).  So 12.7.0 will be a transition version... the Luo et al wetdep scheme is available for research purposes but considered to be incomplete until further updates are made.

**Comment by yantosca** [comment]
This has now been merged into dev/12.7.0.

**Comment by ganluoasrc** [comment]
Hi Bob,

Thanks for your effort.

Best

Gan
________________________________

**Comment by yantosca** [comment]
Thanks Gan.  Let us know about further updates.

**Pull request closed without merging**
