### PR TITLE
Update standard emissions in CESM to match standard model

### PR DESCRIPTION
**Pull request by lizziel**
### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### Describe the update

This PR updates CESM version of `HEMCO_Config.rc` to match what is used in GC-Classic and GCHP 14.4.0. Previously it was consistent with standard emissions in 14.1. Updates, along with their PRs for inclusion in the standard model, include:

- https://github.com/geoschem/geos-chem/pull/1712
- https://github.com/geoschem/geos-chem/pull/2246
- https://github.com/geoschem/geos-chem/pull/1828
- https://github.com/geoschem/geos-chem/pull/2145
- https://github.com/geoschem/geos-chem/pull/2275

In addition, the `NOAA_GMD_CH4` inventory is now turned off in CESM. CESM uses CH4 prescribed in CAM instead.

### Expected changes

This is a zero-diff update for the standard offline model.

### Reference(s)

None

### Related Github Issue

None

### CODE REVIEW

**Comment by lizziel** [comment]
@jimmielin will review this later today.

**Comment by jimmielin** [comment]
The aerosol number emissions in CEDS2 should be updated to:

```
#-----------------------------------------------------
# AEROSOL NUMBER EMISSIONS FOR CEDS in CESM - hplin 8/11/22
# note shp emiss in ship section
#-----------------------------------------------------

0 CEDS_SO4n_AGR   $ROOT/CEDS/v2021-06/$YYYY/SO2-em-anthro_CMIP_CEDS_$YYYY.nc           SO2_agr           1750-2019/1-12/1/0 C xy   kg/m2/s num_a1  8902/2401/8014    1 5
0 CEDS_SO4n_ENE   $ROOT/CEDS/v2021-06/$YYYY/SO2-em-anthro_CMIP_CEDS_$YYYY.nc           SO2_ene           1750-2019/1-12/1/0 C xyL* kg/m2/s num_a1 8907/2406/706/315/8011 1 5
0 CEDS_SO4n_IND   $ROOT/CEDS/v2021-06/$YYYY/SO2-em-anthro_CMIP_CEDS_$YYYY.nc           SO2_ind           1750-2019/1-12/1/0 C xyL* kg/m2/s num_a1 8908/2407/707/316/8011 1 5
0 CEDS_SO4n_TRA   $ROOT/CEDS/v2021-06/$YYYY/SO2-em-anthro_CMIP_CEDS_$YYYY.nc           SO2_tra           1750-2019/1-12/1/0 C xy   kg/m2/s num_a2  8906/2411/711/8022    1 5
0 CEDS_SO4n_RCO   $ROOT/CEDS/v2021-06/$YYYY/SO2-em-anthro_CMIP_CEDS_$YYYY.nc           SO2_rco           1750-2019/1-12/1/0 C xy   kg/m2/s num_a2  8905/2407/709/8022    1 5
0 CEDS_SO4n_SLV   $ROOT/CEDS/v2021-06/$YYYY/SO2-em-anthro_CMIP_CEDS_$YYYY.nc           SO2_slv           1750-2019/1-12/1/0 C xy   kg/m2/s num_a1  8904/2407/707/8014    1 5
0 CEDS_SO4n_WST   $ROOT/CEDS/v2021-06/$YYYY/SO2-em-anthro_CMIP_CEDS_$YYYY.nc           SO2_wst           1750-2019/1-12/1/0 C xy   kg/m2/s num_a1  8903/8014    1 5

# BC emiss are classified as a4 for all anthro
0 CEDS_BCn_AGR    $ROOT/CEDS/v2021-06/$YYYY/BC-em-anthro_CMIP_CEDS_$YYYY.nc            BC_agr            1750-2019/1-12/1/0 C xy   kg/m2/s num_a4  8920/2401/8041    1 5
0 CEDS_BCn_ENE    $ROOT/CEDS/v2021-06/$YYYY/BC-em-anthro_CMIP_CEDS_$YYYY.nc            BC_ene            1750-2019/1-12/1/0 C xy   kg/m2/s num_a4  8920/2406/706/315/8041    1 5
0 CEDS_BCn_IND    $ROOT/CEDS/v2021-06/$YYYY/BC-em-anthro_CMIP_CEDS_$YYYY.nc            BC_ind            1750-2019/1-12/1/0 C xy   kg/m2/s num_a4  8920/2407/707/316/8041    1 5
0 CEDS_BCn_TRA    $ROOT/CEDS/v2021-06/$YYYY/BC-em-anthro_CMIP_CEDS_$YYYY.nc            BC_tra            1750-2019/1-12/1/0 C xy   kg/m2/s num_a4  8920/2411/711/8041    1 5
0 CEDS_BCn_RCO    $ROOT/CEDS/v2021-06/$YYYY/BC-em-anthro_CMIP_CEDS_$YYYY.nc            BC_rco            1750-2019/1-12/1/0 C xy   kg/m2/s num_a4  8920/2409/709/8041    1 5
0 CEDS_BCn_SLV    $ROOT/CEDS/v2021-06/$YYYY/BC-em-anthro_CMIP_CEDS_$YYYY.nc            BC_slv            1750-2019/1-12/1/0 C xy   kg/m2/s num_a4  8920/2407/707/8041    1 5
0 CEDS_BCn_WST    $ROOT/CEDS/v2021-06/$YYYY/BC-em-anthro_CMIP_CEDS_$YYYY.nc            BC_wst            1750-2019/1-12/1/0 C xy   kg/m2/s num_a4  8920/8041    1 5

# OC emiss are classified as a4 for all anthro
0 CEDS_OCn_AGR    $ROOT/CEDS/v2021-06/$YYYY/OC-em-anthro_CMIP_CEDS_$YYYY.nc            OC_agr            1750-2019/1-12/1/0 C xy   kg/m2/s num_a4  8930/2401/8042    1 5
0 CEDS_OCn_ENE    $ROOT/CEDS/v2021-06/$YYYY/OC-em-anthro_CMIP_CEDS_$YYYY.nc            OC_ene            1750-2019/1-12/1/0 C xy   kg/m2/s num_a4  8930/2406/706/315/8042    1 5
0 CEDS_OCn_IND    $ROOT/CEDS/v2021-06/$YYYY/OC-em-anthro_CMIP_CEDS_$YYYY.nc            OC_ind            1750-2019/1-12/1/0 C xy   kg/m2/s num_a4  8930/2407/707/316/8042    1 5
0 CEDS_OCn_TRA    $ROOT/CEDS/v2021-06/$YYYY/OC-em-anthro_CMIP_CEDS_$YYYY.nc            OC_tra            1750-2019/1-12/1/0 C xy   kg/m2/s num_a4  8930/2411/711/8042    1 5
0 CEDS_OCn_RCO    $ROOT/CEDS/v2021-06/$YYYY/OC-em-anthro_CMIP_CEDS_$YYYY.nc            OC_rco            1750-2019/1-12/1/0 C xy   kg/m2/s num_a4  8930/2409/709/8042    1 5
0 CEDS_OCn_SLV    $ROOT/CEDS/v2021-06/$YYYY/OC-em-anthro_CMIP_CEDS_$YYYY.nc            OC_slv            1750-2019/1-12/1/0 C xy   kg/m2/s num_a4  8930/2407/707/8042    1 5
0 CEDS_OCn_WST    $ROOT/CEDS/v2021-06/$YYYY/OC-em-anthro_CMIP_CEDS_$YYYY.nc            OC_wst            1750-2019/1-12/1/0 C xy   kg/m2/s num_a4  8930/8042    1 5

#-----------------------------------------------------
# // end AEROSOL NUMBER EMISSIONS FOR CEDS in CESM
#-----------------------------------------------------
```

> It appears that an extra factor, e.g. 8011 should be applied on top of the factor that makes so4_a1. for example, so the 89xx factors convert CEDS SO4 to so4_aX and then the 80xx factors convert so4_aX to num_aX

Everything else looks good. Thanks!

**Comment by lizziel** [comment]
Thanks @jimmielin, I added in that update.

**Comment by lizziel** [comment]
I am testing this with CESM again now to make sure there are no introduced bugs.

**Comment by lizziel** [comment]
This passes CESM tests, with the exception of known issues (ERP for nudged fails restart comparison, ERP for climo runs does not produce cpl.r file). This is ready to merge.

**Review by yantosca — APPROVED** [review]
These updates look good to merge!   Thanks @lizziel.

**Pull request merged**
