### PR TITLE
Bug fixes: GCHP transport tracers and carbon simulation ExtData.rc

### PR DESCRIPTION
**Pull request by lizziel**
### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### Describe the update

This PR includes 2 fixes:

1.  Move GCHP import `OCEAN_MASK` used in transport tracers simulation out of the `ExtData.rc.TransportTracers` template and into the meteorology input template files. This update fixes a bug where `OCEAN_MASK` was incorrectly defined when using native GEOS-FP input data. The template in `ExtData.rc.TransportTracers` assumed processed input data which is an over-generalization. Defining the ocean mask input is now moved to where all other met-field inputs are defined for GCHP, in the met-specific files in `run/shared/settings/`.
2. Update GCHP `ExtData.rc.CO2` template to get met-fields from external files. This update brings the `ExtData.rc.CO2` template in line with how met-fields are included for other GCHP simulations. It also fixes a bug where the GCHP carbon simulation would not work with native GEOS-FP files due to an incorrect met-field file template in `ExtData.rc`.

### Expected changes

No changes.

### Related Github Issue(s)

closes https://github.com/geoschem/geos-chem/issues/1886

### CODE REVIEW

**Review by yantosca — APPROVED** [review]
@lizziel: These changes look OK to merge.  We need a changelog but I can add that.

**Comment by yantosca** [comment]
I have merged this branch locally atop of PR #1971.  Integration tests are running.

**Comment by lizziel** [comment]
Thanks @yantosca!

**Comment by yantosca** [comment]
All GEOS-Chem Classic integration tests passed (except for TOMAS, which will be fixed in 14.3.0):
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

GCClassic #eba52e6 GEOS-Chem submod update: Merge PR #1971 (Set halfpolar for global hi-res grids)
GEOS-Chem #7dbf97d9d Merge PR #1974 (Bug fixes in GCHP specialty sim ExtData.rc templates )
HEMCO     #daf54d0 Merge PR #235 (Bug fix for vertical regridding)

Using 24 OpenMP threads
Number of execution tests: 27

Submitted as SLURM job: 3480208
==============================================================================

Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 25
Execution tests failed: 2
Execution tests not yet completed: 0
```
Furthermore, all integration tests (except APM and RRTMG, which have known parallelization issues) were identical to the prior integration test (PR #1971):
```console
Checking gc_4x5_merra2_fullchem_APM
   -> 1 difference found in OutputDir
      * GCC_r27/rundirs/gc_4x5_merra2_fullchem_APM/OutputDir/GEOSChem.SpeciesConc.20190701_0000z.nc4 
        GCC_r28/rundirs/gc_4x5_merra2_fullchem_APM/OutputDir/GEOSChem.SpeciesConc.20190701_0000z.nc4 
   -> 1 difference found in Restarts
      * GCC_r27/rundirs/gc_4x5_merra2_fullchem_APM/Restarts/GEOSChem.Restart.20190701_0100z.nc4 
        GCC_r28/rundirs/gc_4x5_merra2_fullchem_APM/Restarts/GEOSChem.Restart.20190701_0100z.nc4 

Checking gc_4x5_merra2_fullchem_RRTMG
   -> 1 difference found in OutputDir
      * GCC_r27/rundirs/gc_4x5_merra2_fullchem_RRTMG/OutputDir/GEOSChem.RRTMG.20190701_0000z.nc4 
        GCC_r28/rundirs/gc_4x5_merra2_fullchem_RRTMG/OutputDir/GEOSChem.RRTMG.20190701_0000z.nc4 
   -> No differences in Restarts
```

**Comment by yantosca** [comment]
All GCHP integration tests passed:
```console
==============================================================================
GCHP: Execution Test Results

GCClassic #4021faa GEOS-Chem submod update: Merge PR #1971 (Set halfpolar for global hi-res grids)
GEOS-Chem #7dbf97d9d Merge PR #1974 (Bug fixes in GCHP specialty sim ExtData.rc templates )
HEMCO     #daf54d0 Merge PR #235 (Bug fix for vertical regridding)

Number of execution tests: 5

Submitted as SLURM job: 3480407
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
Furthermore, all GCHP integration tests were zero-diff w/r/t the prior integration test (PR #1971).

**Pull request merged**
