### PR TITLE
Add S(IV) + HOBr and S(IV) + HOCl to the fullchem mechanism (Closes #1627)

### LINKED ISSUE #1627: [FEATURE REQUEST] Add S(IV) + HOBr/HOCl to enhanced in-cloud sulfate production rates in large cloud droplets
### Request a new GEOS-Chem feature:
Chen et al., GRL, (2017) added S(IV) + HOBr to GEOS-Chem v9-02. In v9-02. This reaction was included in the enhanced in-cloud sulfate production rate for larger, higher-pH cloud droplets in addition to the "bulk" cloud chemistry. Previously, this enhancement in the sulfate production rate was applied only to S(IV) + O3 (Alexander et al., JGR, 2012). When S(IV)+HOBr was implemented into the standard version of GEOS-Chem, it was mistakenly not included in the enhanced sulfate production (termed "SR" in the code, where SR = size-resolved cloud droplets). This mistake occurred because the original implementation (and resulting publication) was in SMVGEAR and the transfer to KPP was incomplete. I did not realize this until recently.

This does not change the enhanced sulfate production rate (SR) because SR is the same but is now split up between O3, HOBr, and HOCl instead of all being attributed to O3. I suggest fixing this so that the chemistry in the model is as it is described in Chen et al., (2017).

I added this to the code (13.4.1) and have included a patch file here. The changes to SO2, SO4, HOBr, HBr, HOCl, HCl, O3, and BrO for January 2019 are small to negligible. 

[SR_HOX-patch-file.txt](https://github.com/geoschem/geos-chem/files/10522321/SR_HOX-patch-file.txt)

[SRHOX_ssdebromBrClIhet_HOBrHBr.pdf](https://github.com/geoschem/geos-chem/files/10522326/SRHOX_ssdebromBrClIhet_HOBrHBr.pdf)
[SRHOX_ssdebromBrClIhet_HOClHCl.pdf](https://github.com/geoschem/geos-chem/files/10522328/SRHOX_ssdebromBrClIhet_HOClHCl.pdf)
[SRHOX_ssdebromBrClIhet_O3BrO.pdf](https://github.com/geoschem/geos-chem/files/10522329/SRHOX_ssdebromBrClIhet_O3BrO.pdf)
[SRHOX_ssdebromBrClIhet_SO2SO4.pdf](https://github.com/geoschem/geos-chem/files/10522330/SRHOX_ssdebromBrClIhet_SO2SO4.pdf)

### PR DESCRIPTION
**Pull request by yantosca**
This is the companion PR to #1627, which was opened by @beckyalexander.  She wrote:

> Chen et al., GRL, (2017) added S(IV) + HOBr to GEOS-Chem v9-02. In v9-02. This reaction was included in the enhanced in-cloud sulfate production rate for larger, higher-pH cloud droplets in addition to the "bulk" cloud chemistry. Previously, this enhancement in the sulfate production rate was applied only to S(IV) + O3 (Alexander et al., JGR, 2012). When S(IV)+HOBr was implemented into the standard version of GEOS-Chem, it was mistakenly not included in the enhanced sulfate production (termed "SR" in the code, where SR = size-resolved cloud droplets). This mistake occurred because the original implementation (and resulting publication) was in SMVGEAR and the transfer to KPP was incomplete. I did not realize this until recently.
> 
> This does not change the enhanced sulfate production rate (SR) because SR is the same but is now split up between O3, HOBr, and HOCl instead of all being attributed to O3.

I was able to manually apply the changes from @beckyalexander's patch file.  NOTE: I have made a couple of corrections: the `SRO3`, `SRHOBr` and `SRHOCl` are not variables of the `State_Het` object but are now included in `commonIncludeVars.H`, which gets referenced by `gckpp_Global.F90`.  

Integration tests to follow.  This can be included along with other science updates in 14.2.0.

Closes #1627

### CODE REVIEW

**Comment by yantosca** [comment]
@beckyalexander, would you be also able to take a quick look at the files changed tab and let me know if you have any comments.  Thanks.

**Review by beckyalexander — COMMENTED** [review]
I think this looks good. I had set SR* = 0 if fullchem_HetDropChem is not called from fullchem_mod. I don't see that here. Instead, it looks like you set SRO3, SRHOBr, and SRHOCl = 0 before fullchem_HetDropChem is called, which I think also works (and perhaps is better).

**Comment by yantosca** [comment]
All GCHP integration tests passed:
```console
==============================================================================
GCHP: Execution Test Results

Number of execution tests: 3
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gchp_fullchem_benchmark_merra2_c48..................Execute Simulation....PASS
gchp_fullchem_standard_merra2_c24...................Execute Simulation....PASS
gchp_TransportTracers_geosfp_c24....................Execute Simulation....PASS
 
Summary of execution test results:
------------------------------------------------------------------------------
Execution tests passed:        3
Execution tests failed:        0
Execution tests not completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
> I think this looks good. I had set SR* = 0 if fullchem_HetDropChem is not called from fullchem_mod. I don't see that here. Instead, it looks like you set SRO3, SRHOBr, and SRHOCl = 0 before fullchem_HetDropChem is called, which I think also works (and perhaps is better).

Yes, that avoids an ELSE statement, which can be a computationaly bottleneck (since the code has to basically guess which branch is going to happen).

**Comment by yantosca** [comment]
GEOS-Chem Classic integration tests all passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

Using 24 OpenMP threads
Number of execution tests: 51
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gc_025x03125_CH4_geosfp_47L_na......................Execute Simulation....PASS
gc_025x03125_fullchem_geosfp_47L_na.................Execute Simulation....PASS
gc_05x0625_CH4_merra2_47L_na........................Execute Simulation....PASS
gc_05x0625_fullchem_merra2_47L_na...................Execute Simulation....PASS
gc_2x25_aerosol_merra2..............................Execute Simulation....PASS
gc_2x25_carbon_merra2...............................Execute Simulation....PASS
gc_2x25_CH4_merra2..................................Execute Simulation....PASS
gc_2x25_CO2_merra2..................................Execute Simulation....PASS
gc_2x25_fullchem_merra2.............................Execute Simulation....PASS
gc_2x25_Hg_merra2...................................Execute Simulation....PASS
gc_2x25_metals_merra2...............................Execute Simulation....PASS
gc_2x25_POPs_BaP_merra2.............................Execute Simulation....PASS
gc_2x25_tagCH4_merra2...............................Execute Simulation....PASS
gc_2x25_tagCO_merra2................................Execute Simulation....PASS
gc_2x25_tagO3_merra2................................Execute Simulation....PASS
gc_2x25_TransportTracers_merra2.....................Execute Simulation....PASS
gc_2x25_TransportTracers_merra2_LuoWd...............Execute Simulation....PASS
gc_4x5_aerosol_geosfp...............................Execute Simulation....PASS
gc_4x5_aerosol_merra2...............................Execute Simulation....PASS
gc_4x5_carbon_geosfp................................Execute Simulation....PASS
gc_4x5_carbon_merra2................................Execute Simulation....PASS
gc_4x5_CH4_geosfp...................................Execute Simulation....PASS
gc_4x5_CH4_merra2...................................Execute Simulation....PASS
gc_4x5_fullchem_aciduptake_merra2...................Execute Simulation....PASS
gc_4x5_fullchem_APM_merra2..........................Execute Simulation....PASS
gc_4x5_fullchem_benchmark_merra2....................Execute Simulation....PASS
gc_4x5_fullchem_complexSOA_merra2...................Execute Simulation....PASS
gc_4x5_fullchem_complexSOA_SVPOA_merra2.............Execute Simulation....PASS
gc_4x5_fullchem_geosfp..............................Execute Simulation....PASS
gc_4x5_fullchem_marinePOA_merra2....................Execute Simulation....PASS
gc_4x5_fullchem_merra2..............................Execute Simulation....PASS
gc_4x5_fullchem_merra2_47L..........................Execute Simulation....PASS
gc_4x5_fullchem_merra2_LuoWd........................Execute Simulation....PASS
gc_4x5_fullchem_RRTMG_merra2........................Execute Simulation....PASS
gc_4x5_fullchem_TOMAS15_merra2_47L..................Execute Simulation....PASS
gc_4x5_fullchem_TOMAS40_merra2_47L..................Execute Simulation....PASS
gc_4x5_Hg_geosfp....................................Execute Simulation....PASS
gc_4x5_Hg_merra2....................................Execute Simulation....PASS
gc_4x5_metals_merra2................................Execute Simulation....PASS
gc_4x5_POPs_BaP_geosfp..............................Execute Simulation....PASS
gc_4x5_POPs_BaP_merra2..............................Execute Simulation....PASS
gc_4x5_tagCH4_geosfp................................Execute Simulation....PASS
gc_4x5_tagCH4_merra2................................Execute Simulation....PASS
gc_4x5_tagCO_geosfp.................................Execute Simulation....PASS
gc_4x5_tagCO_merra2.................................Execute Simulation....PASS
gc_4x5_tagO3_geosfp.................................Execute Simulation....PASS
gc_4x5_tagO3_merra2.................................Execute Simulation....PASS
gc_4x5_TransportTracers_geosfp......................Execute Simulation....PASS
gc_4x5_TransportTracers_geosfp_LuoWd................Execute Simulation....PASS
gc_4x5_TransportTracers_merra2......................Execute Simulation....PASS
gc_4x5_TransportTracers_merra2_LuoWd................Execute Simulation....PASS
 
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 51
Execution tests failed: 0
Execution tests not yet completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Review by msulprizio — APPROVED** [review]
@yantosca These changes look good to merge. Could you update the `CHANGELOG.md` in this branch before I do that?

**Pull request merged**
