### PR TITLE
Fix indentation issue in geoschem_config.yml templates

### PR DESCRIPTION
**Pull request by laestrada**
There is an indentation issue with the geoschem_config.yml templates that prevents some yaml parsers from being able to parse the files correctly (eg. yq).

### CODE REVIEW

**Review by yantosca — APPROVED** [review]
This PR remove extraneous characters in the `legacy_bpch` section of the geoschem_config.yml files, so that the indentation level is always the same number of spaces.  Good to merge.

NOTE: The bpch diagnostics will probably be completely removed as soon as the TOMAS PR is merged.

**Comment by yantosca** [comment]
This is also a zero-diff update w/r/t the benchmark simulations because the `legacy_bpch` section is only read when `-DBPCH_DIAG=y`, which is not used by default.

**Comment by yantosca** [comment]
Integration tests are now running

**Comment by yantosca** [comment]
GCHP execution tests passed:
```console
==============================================================================
GCHP: Execution Test Results

Number of execution tests: 3
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gchp_fullchem_benchmark_merra2_c48...............Execute Simulation.....PASS
gchp_fullchem_standard_merra2_c24................Execute Simulation.....PASS
gchp_TransportTracers_geosfp_c24.................Execute Simulation.....PASS
 
Summary of execution test results:
------------------------------------------------------------------------------
Execution tests passed:        3
Execution tests failed:        0
Execution tests not completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
The integration test failures seem to be due to the fact that the `bugfix/fix_invalid_yaml` branch was significantly behind the `dev/14.0.2` branch.  We have merged `dev/14.0.2` into `bugfix/fix_invalid_yaml` and have restarted the integration tests.

**Review by msulprizio — APPROVED** [review]

**Pull request merged**
