### PR TITLE
[PULL REQUEST] Oceanic ozone dry deposition update

### PR DESCRIPTION
**Pull request by r-pound**
Model updates described in accompanying paper (https://www.atmos-chem-phys-discuss.net/acp-2019-1043/ - currently under discussion). Only the changes in drydep_mod.f are required for this update.

### CODE REVIEW

**Comment by msulprizio** [comment]
Hi @r-pound! I am in the process of merging in this pull request for inclusion in GC 12.8.0. I notice in drydep_mod.F has the following lines:

```
      CALL HCO_GetPtr( am_I_Root, HcoState, 'surf_iodide', 
     &                 HCO_Iodide, RC )
      CALL HCO_GetPtr( am_I_Root, HcoState,'surf_salinity', 
     &                 HCO_Salinity, RC)
```

Can you provide the necessary updates for those fields in HEMCO_Config.rc and also send us the data files?

**Comment by msulprizio** [comment]
Data files needed for this update are now in http://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/OCEAN_O3_DRYDEP/v2020-02/. These files still need to be synced to Compute Canada.

@r-pound is currently investigating unexpected differences from the internal 1-month benchmark.

**Comment by r-pound** [comment]
I've done some testing and found out what the issue was, after some testing locally the results are now comparable to those in the paper

**Comment by msulprizio** [comment]
This PR with the latest fix is now merged into dev/12.8.0

**Pull request closed without merging**
