### PR TITLE
Store aerosol-specific optics files in new Aerosol_Optics data directory

### PR DESCRIPTION
**Pull request by lizziel**
### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### Describe the update

This PR moves the aerosol-specific optics data files (`so4.dat`, `dust.dat`, etc) into a new data directory with path specified in the `Aerosols` menu in `geoschem_config.yml`. Previously these files were stored in the same data directory as photolysis input files. However, since we now have both FAST-JX (for Hg simulation) and Cloud-J (for fullchem and aerosol sims) we would need to store identical files in two different places. This is not ideal. In addition it  may cause confusion since these files are no longer used for photolysis in Cloud-J. Aerosol optical properties used in Cloud-J come from input file `FJX_scat-aer.dat`.

There are a few additional changes in this PR related to this data:

1.  Move the calls to `RD_AOD `and `CALC_AOD` from `Init_Photolysis` to both `Init_Aerosol` and `Init_FastJX`. The former is for use in full chemistry and aerosol-only simulations. The latter is for use in the Hg simulation since it still uses Fast-JX and Fast-JX uses arrays computed by `CALC_AOD`.
2. Change the criteria to call `Init_Aerosol` to be based on simulation type rather than `Input_Opt` logicals for different aerosols. `Init_Aerosol` is now always called if using the full chemistry or aerosol-only simulation.

### Expected changes

This is a no diff update for all simulations.

### Reference(s)

None

### Related Github Issue

Closes https://github.com/geoschem/geos-chem/issues/2403

### CODE REVIEW

**Comment by lizziel** [comment]
This update is ready for review but please do not merge yet. Integration tests are in progress.

**Review by yantosca — APPROVED** [review]
Thanks @lizziel.  This is good to merge.  I'll start bringing this in.

**Comment by yantosca** [comment]
The GEOS-Chem Classic Hg test now passes due to the fix in commit ef88bd7.  The "alldiags" test fails but this will be corrected once merged the 14.5.0 development stream.
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

CodeDir   : 8da455b GEOS-Chem submod update: PR #2425 post-merge fix (CHANGELOG.md update_
GEOS-Chem : ef88bd76d Add aerosol optics input dir to geoschem_config.yml.Hg template
HEMCO     : 41605bd HEMCO 3.9.3 release
Cloud-J   : d20050f Update version to 7.7.3
HETP      : 2a99b24 Merge pull request #2 from geoschem/bugfix/initialize_local_variables

Using 24 OpenMP threads
Number of execution tests: 30

Submitted as SLURM job: 44365826
==============================================================================

gc_4x5_merra2_Hg....................................Execute Simulation....PASS
gc_4x5_merra2_fullchem_alldiags.....................Execute Simulation....FAIL

Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 29
Execution tests failed: 1
Execution tests not yet completed: 0
```

**Comment by yantosca** [comment]
The updates in this PR were used to create the 1-month benchmark outputs listed on PR #2318.  See https://github.com/geoschem/geos-chem/pull/2318#issuecomment-2296732940.

**Comment by lizziel** [comment]
@yantosca, sorry about that. I fixed the Hg simulation issue locally but forgot to push.

**Comment by lizziel** [comment]
I see there are a bunch of commits due to recent merged in dev/14.5.0. I will update the branch to resolve conflicts.

**Comment by yantosca** [comment]
After merging locally atop PR #2144, all GCClassic integration tests passed, except ModelE2.1:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

CodeDir   : edaa239 GEOS-Chem & HEMCO updates: Merge PR #2318, PR #284, PR #285
GEOS-Chem : 3073aff2e Merge PR #2428 (Fix mass non-conservation in VDIFF)
HEMCO     : d0d5fca PR #285 post-merge fix: Update CHANGELOG.md
Cloud-J   : d20050f Update version to 7.7.3
HETP      : 2a99b24 Merge pull request #2 from geoschem/bugfix/initialize_local_variables

Using 24 OpenMP threads
Number of execution tests: 30

Submitted as SLURM job: 44765607
==============================================================================

gc_2x25_ModelE2.1_fullchem..........................Execute Simulation....FAIL

Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 29
Execution tests failed: 1
Execution tests not yet completed: 0
```
The failure of the ModelE2.1 is described in #2427.

**Comment by yantosca** [comment]
After merging atop PR #2144 (locally), all GCHP integration tests also passed.
```console
==============================================================================
GCHP: Execution Test Results

CodeDir       : 548c753 GEOS-Chem submod update: PR #2352 post-merge fix (rebuild KPP files)
MAPL          : 231d53c Merge pull request #36 from geoschem/feature/improve_hflux_regridding
GMAO_Shared   : 4ddb3ec Merge pull request #2 from geoschem/feature/mapl-upgrade
ESMA_cmake    : ad5deba Added ecbuild as a submodule of ESMA_cmake
gFTL-shared   : 4b82492 Merge branch 'upstream_v1.5.0' into feature/v1.5.0
FMS           : 259759d Merge pull request #3 from geoschem/feature/update_gmao_libs
FVdycoreCubed : af42462 Merge PR #8 (Add PLEadv diagnostic for offline advection in GCHP)
geos-chem     : 3073aff2e Merge PR #2428 (Fix mass non-conservation in VDIFF)
HEMCO         : d0d5fca PR #285 post-merge fix: Update CHANGELOG.md
yaFyaml       : 19afe50 Merge branch 'upstream_v1.0.4' into feature/v1.0.4
pFlogger      : 2c4b724 Merge branch 'upstream_v1.9.1' into feature/v1.9.1
Cloud-J       : 37a4ece Update release version number and date
HETP          : 2a99b24 Merge pull request #2 from geoschem/bugfix/initialize_local_variables

Number of execution tests: 12

Submitted as SLURM job: 44765782
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by lizziel** [comment]
I removed the ALK4P update in this branch since it is unnecessary after rebase on latest dev/14.5.0. Conflicts are now resolved and I am running integration tests.

**Comment by lizziel** [comment]
All integration tests pass except for `gc_2x25_ModelE2.1_fullchem` due to a known unrelated issue.

**Comment by yantosca** [comment]
> All integration tests pass except for `gc_2x25_ModelE2.1_fullchem` due to a known unrelated issue.

This should now be fixed going forward.  I have recreated the missing file described in #2427.

**Comment by yantosca** [comment]
We have added a hotfix to set `Is_Photolysis:true` to the `species_database.yml`, and have rerun integration tests.  All GEOS-Chem Classic integration tests passed.  This set of tests also includes PR #2424 and https://github.com/geoschem/Cloud-J/pull/24.
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

CodeDir   : 930deb9 GEOS-Chem submod update: Merge PR #2436, #2439, #2371 (PPN Phot etc.)
GEOS-Chem : 1951ea96e Hotfix: Declare PPN as photolyzing in the species database
HEMCO     : d0d5fca PR #285 post-merge fix: Update CHANGELOG.md
Cloud-J   : 291a161 Update Cloud-J standalone settings to use UV absorption by H2O by default
HETP      : 2a99b24 Merge pull request #2 from geoschem/bugfix/initialize_local_variables

Using 24 OpenMP threads
Number of execution tests: 30

Submitted as SLURM job: 45864046
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
We have added a hotfix to set `Is_Photolysis:true` to the `species_database.yml`, and have rerun integration tests.  All GCHP integration tests passed.  This set of tests also includes PR #2424 and https://github.com/geoschem/Cloud-J/pull/24.
```console
==============================================================================
GCHP: Execution Test Results

CodeDir       : 6d817f8 GEOS-Chem submod update: Merge PR #2436, #2439, #2371 (PPN Phot etc.)
MAPL          : 231d53c Merge pull request #36 from geoschem/feature/improve_hflux_regridding
GMAO_Shared   : 4ddb3ec Merge pull request #2 from geoschem/feature/mapl-upgrade
ESMA_cmake    : ad5deba Added ecbuild as a submodule of ESMA_cmake
gFTL-shared   : 4b82492 Merge branch 'upstream_v1.5.0' into feature/v1.5.0
FMS           : 259759d Merge pull request #3 from geoschem/feature/update_gmao_libs
FVdycoreCubed : af42462 Merge PR #8 (Add PLEadv diagnostic for offline advection in GCHP)
geos-chem     : 1951ea96e Hotfix: Declare PPN as photolyzing in the species database
HEMCO         : d0d5fca PR #285 post-merge fix: Update CHANGELOG.md
yaFyaml       : 19afe50 Merge branch 'upstream_v1.0.4' into feature/v1.0.4
pFlogger      : 2c4b724 Merge branch 'upstream_v1.9.1' into feature/v1.9.1
Cloud-J       : 291a161 Update Cloud-J standalone settings to use UV absorption by H2O by default
HETP          : 2a99b24 Merge pull request #2 from geoschem/bugfix/initialize_local_variables

Number of execution tests: 12

Submitted as SLURM job: 45866935
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Pull request merged**
