### PR TITLE
Enable GCHP to be compiled with RRTMG

### PR DESCRIPTION
**Pull request by sdeastham**
Currently, GCHP cannot be compiled with RRTMG. This fixes that. With this set of commits, GCHP can be compiled by supplying `-DRRTMG` to the `cmake` build call, with no other compile modifications. The resulting executable can be run either WITH or WITHOUT RRTMG. This commit also adds the necessary files to ExtData.rc, an appropriate HISTORY.rc collection (disabled by default), and fixes a bug in RRTMG described in issue #346 (although this is also resolved independently by PR #347). Currently, this code will result in RRTMG being run on every chemistry timestep, which is very expensive (a timer has been added to check this behavior). Further work will be needed to have RRTMG called less frequently, if selected.

### CODE REVIEW

**Comment by lizziel** [comment]
Thanks @sdeastham. I manually did a merge locally to resolve conflicts but am running into build problems. I don't think these are specific to your updates but pre-date them with the RRTMG simulation. Did you test within the [GEOS-Chem Classic wrapper](https://github.com/geoschem/geos-chem-classic) in addition to GCHPctm?

**Comment by sdeastham** [comment]
I did not test with GC Classic - can you post the issues?

**Comment by lizziel** [comment]
Yes, I will post them, but after I get the version prior to the merge building with RRTMG. I am certain there are issues unrelated to your updates and will deal with those first in case they end up resolving everything.

**Comment by lizziel** [comment]
This PR is now merged. There were a couple build issues. The first issue was pre-existing before this PR. The -override-limits flag worked for GCC but not Intel compilers. This PR fixed it for Intel, but inadvertently caused it to no longer build with GCC. The second was introduced with this PR. The dependency on GEOSChemBuildProperties was removed for GCHP but is required for GC-Classic. I fixed both of these issues directly following the merge.

**Pull request merged**
