### PR TITLE
Add fixes for ALK4 and R4N2 chemistry from Brewer et al. (2023, JGR)

### PR DESCRIPTION
**Pull request by msulprizio**
### Name and Institution (Required)

Name: Melissa Sulprizio 
Institution: Harvard

### Describe the update

I am opening this pull request on behalf of @JFBrewer.

R4N2 was a common product of alkane, isoprene, and monoterpene oxidation and produced organonitrate SOA but we don’t want ALK4 to produce organonitrate SOA as discusses in https://github.com/geoschem/geos-chem/issues/1625. A fix from Jared Brewer is included here.

NOTE: These updates are made off of 14.1.0. The KPP fullchem mechanism has not been rebuilt with these fixes to facilitate merging these updates up to the latest GEOS-Chem release. These updates will also need to be added to the custom.eqn file.

### Expected changes

We expect decreases in R4O2 and increases in ACET, MEK, HO2, ALD2, RCHO, MEK, CH2O, NO2 and other species due to the changing chemical mechanism.

### Reference(s)

- Brewer, J.F., D.J. Jacob, S.H. Jathar, Y. He, A. Akherati, S. Zhai, D.S. Jo, A. Hodzic, B.A. Nault, P. Campuzano-Jost, J.L. Jimenez, R.J. Park, Y.J. Oak, and H. Liao, [A scheme for representing aromatic secondary organic aerosols in chemical transport models: application to source attribution of organic aerosols over South Korea during the KORUS-AQ campaign,](https://doi.org/10.1029/2022JD037257) J. Geophys. Res., e2022JD037257, https://doi.org/10.1029/2022JD037257, 2023.

### Related Github Issue

- https://github.com/geoschem/geos-chem/issues/1625

### CODE REVIEW

**Review by yantosca — APPROVED** [review]
Thanks @msulprizio.  I think this is OK to merge.  I can add the updates to custom.eqn as a post-merge update.  We'd also need to update `KPP/fullchem/CHANGELOG_fullchem.md`.

**Comment by msulprizio** [comment]
Hi @JFBrewer and @kelvinhb. I am merging these updates (based off of 14.1.0) with the latest version (branch `dev/14.5.0`) and am finding many conflicts in fullchem.eqn. It seems that these updates touch many of the lines that were updated by the [JPL/IUPAC updates](https://github.com/geoschem/geos-chem/pull/1765) added in GEOS-Chem 14.3.0. I list all of the conflicts below.

Could you help me figure out if the fixes from Brewer2023 are still needed on top of the Bates2023 updates? If so, could you provide guidance on how to resolve the conflicts below?

Also tagging Chemistry Working Group Chairs @barrohh and @luhu0 for awareness.

```
Conflicts in fullchem.eqn from HEAD:bugfix/alk4-chem-brewer2023 and dev/14.5.0:

<<<<<<< HEAD
ALK4 + OH = ALK4O2 :                         GCARR_ac(9.10d-12, -405.0d0);						       {2023/05/14; Brewer2023; JFB}
ALK4O2 + NO = NO2 + 0.320ACET + 0.190MEK +
 0.190MO2 + 0.270HO2 + 0.320ALD2 +
 0.140RCHO + 0.050A3O2 + 0.180B3O2 +
 0.320OTHRO2 :                               GC_RO2NO_B2_aca(2.70d-12, 350.0d0, 4.5d0);                                        {2023/05/14; Brewer2023; JFB}
ALK4O2 + NO = ALK4N2 :                       GC_RO2NO_A2_aca(2.70d-12, 350.0d0, 4.5d0);					       {2023/05/14; Brewer2023; JFB}
ALK4N1 + NO = 2.000NO2 + 0.570RCHO +
 0.860ALD2 + 0.570CH2O :                     GCARR_ac(2.70d-12, 350.0d0);						       {2023/05/14; Brewer2023; JFB}
R4O2 + NO = NO2 + 0.320ACET + 0.190MEK +
 0.190MO2 + 0.270HO2 + 0.320ALD2 +
 0.140RCHO + 0.050A3O2 + 0.180B3O2 +
 0.320OTHRO2 :                               GC_RO2NO_B2_aca(2.70d-12, 350.0d0, 4.5d0);                                        {2017/02/23; ALK4 lumping fix; BHH}
R4O2 + NO = R4N2 :                           GC_RO2NO_A2_aca(2.70d-12, 350.0d0, 4.5d0);
R4N1 + NO = 2.000NO2 + 0.570RCHO +
 0.860ALD2+ 0.570CH2O :                     GCARR_ac(2.70d-12, 350.0d0);                                                      {2017/07/27; Fix C creation; SAS,BHH,MJE}
ATO2 + NO = NO2 + CH2O + MCO3 :              GCARR_ac(2.80d-12, 300.0d0);                                                      {2017/07/27; Fix C creation; SAS,BHH,MJE}
KO2 + NO = 0.930NO2 + 0.930ALD2 +
 0.930MCO3 + 0.070ALK4N2 :                   GCARR_ac(2.70d-12, 350.0d0);                                                      {2023/05/14; Brewer2023; JFB}
=======
ALK4 + OH = R4O2 :                           GCARR_ac(9.10d-12, -405.0d0);
R4O2 + NO = NO2 + 0.340ACET + 0.190MEK +
 0.190MO2 + 0.270HO2 + 0.340ALD2 +
 0.150RCHO + 0.050A3O2 + 0.190B3O2 +
 0.340OTHRO2 :                               GC_RO2NO_B2_aca(2.70d-12, 350.0d0, 4.5d0);                                        {2023/04/18; Bates2023; KHB}
R4O2 + NO = R4N2 :                           GC_RO2NO_A2_aca(2.70d-12, 350.0d0, 4.5d0);
R4N1 + NO = 2.000NO2 + 0.640RCHO +
 0.970ALD2 + 0.640CH2O :                     GCARR_ac(2.70d-12, 350.0d0);                                                      {2023/04/18; Bates2023; KHB}
ATO2 + NO = NO2 + CH2O + MCO3 :              GCARR_ac(2.90d-12, 300.0d0);                                                      {2023/04/18; JPL 19-5; KHB}
KO2 + NO = 0.928NO2 + 0.919ALD2 +
 0.919MCO3 + 0.072R4N2 :                     GCARR_ac(2.70d-12, 350.0d0);                                                      {2023/04/18; Bates2023; KHB}
>>>>>>> origin/dev/14.5.0

<<<<<<< HEAD
 0.250MOH + 0.250ROH + 0.500HO2 :            8.37d-14;
R4N1 + MO2 = NO2 + 0.200CH2O + 0.380ALD2 +
 0.290RCHO + 0.150R4O2 + 0.250RCHO +
 0.750CH2O + 0.250MOH + 0.250ROH +
 0.500HO2 :                                  8.37d-14;
ALK4O2 + MO2 = 0.160ACET + 0.100MEK +
 0.090MO2 + 0.140HO2 + 0.160ALD2 +
 0.070RCHO + 0.030A3O2 + 0.090B3O2 +
 0.160OTHRO2 + 0.250MEK + 0.750CH2O +
 0.250MOH + 0.250ROH + 0.500HO2 :            8.37d-14;                                                                         {2023/05/14; Brewer2023; JFB}
ALK4N1 + MO2 = NO2 + 0.200CH2O + 0.380ALD2 +
 0.290RCHO + 0.150R4O2 + 0.250RCHO +
 0.750CH2O + 0.250MOH + 0.250ROH +
 0.500HO2 :                                  8.37d-14;                                                                         {2023/05/14; Brewer2023; JFB}
ATO2 + MO2 = 0.300HO2 + 0.300CH2O +
 0.300MCO3 + 0.200HAC + 0.200CH2O +
 0.500MGLY + 0.500MOH :                      GCARR_ac(7.50d-13, 500.0d0);
=======
 0.250MOH + 0.380ROH + 0.500HO2 :            8.37d-14;                                                                         {2023/04/18; Bates2023; KHB}
R4N1 + MO2 = NO2 + 0.950CH2O + 0.380ALD2 +
 0.580RCHO + 0.150R4O2 + 0.500HO2 +
 0.250MOH + 0.375ROH :                       8.37d-14;                                                                         {2023/04/18; Bates2023; KHB}
ATO2 + MO2 = 0.300HO2 + 0.500CH2O +
 0.300MCO3 + 0.200HAC + 0.500MGLY +
 0.500MOH + 0.300CO2 :                       GCARR_ac(7.50d-13, 500.0d0);                                                      {2023/04/18; Bates2023; KHB}
>>>>>>> origin/dev/14.5.0

<<<<<<< HEAD
R4P + OH = 0.791OH + 0.209R4O2 + 0.791RCHO : GCARR_ac(8.78d-12, 200.0d0);                                                      {2013/03/22; Paulot2009; FP,EAM,JMAO,MJE}
ALK4P + OH = 0.791OH + 0.209ALK4O2 + 
 0.791RCHO :                                 GCARR_ac(8.78d-12, 200.0d0);                                                      {2023/05/14; Brewer2023; JFB}
=======
R4P + OH = 0.790OH + 0.210R4O2 + 1.185RCHO : GCARR_ac(8.78d-12, 200.0d0);                                                      {2013/03/22; Paulot2009; FP,EAM,JMAO,MJE; 2023/04/18; Bates2023; KHB}
>>>>>>> origin/dev/14.5.0

<<<<<<< HEAD
MCO3 + MCO3 = 2.000MO2 :                     GCARR_ac(2.50d-12, 500.0d0);
MCO3 + MO2 = CH2O + MO2 + HO2 :              GCARR_ac(1.80d-12, 500.0d0);
MCO3 + MO2 = ACTA + CH2O :                   GCARR_ac(2.00d-13, 500.0d0);
R4O2 + MCO3 = MO2 + 0.320ACET + 0.190MEK +
 0.270HO2 + 0.320ALD2 + 0.130RCHO +
 0.050A3O2 + 0.180B3O2 + 0.320OTHRO2 :       GCARR_ac(1.68d-12, 500.0d0);                                                      {2013/03/22; Paulot2009; FP,EAM,JMAO,MJE}
ALK4O2 + MCO3 = MO2 + 0.320ACET + 0.190MEK +
 0.270HO2 + 0.320ALD2 + 0.130RCHO +
 0.050A3O2 + 0.180B3O2 + 0.320OTHRO2 :       GCARR_ac(1.68d-12, 500.0d0);                                                      {2023/05/14; Brewer2023; JFB}
ATO2 + MCO3 = MO2 + MCO3 + CH2O :            GCARR_ac(1.68d-12, 500.0d0);                                                      {2013/03/22; Paulot2009; FP,EAM,JMAO,MJE}
KO2 + MCO3 = MO2 + ALD2 + MCO3 :             GCARR_ac(1.68d-12, 500.0d0);
B3O2 + MCO3 = MO2 + HO2 + ACET :             GCARR_ac(1.68d-12, 500.0d0);
R4N1 + MCO3 = MO2 + NO2 + 0.390CH2O +
 0.750ALD2 + 0.570RCHO + 0.300R4O2 :         GCARR_ac(1.68d-12, 500.0d0);
ALK4N1 + MCO3 = MO2 + NO2 + 0.390CH2O +
 0.750ALD2 + 0.570RCHO + 0.300ALK4O2 :       GCARR_ac(1.68d-12, 500.0d0);                                                      {2023/05/14; Brewer2023; JFB}
PRN1 + MCO3 = MO2 + NO2 + CH2O + ALD2 :      GCARR_ac(1.68d-12, 500.0d0);
R4O2 + MCO3 = MEK + ACTA :                   GCARR_ac(1.87d-13, 500.0d0);
ALK4O2 + MCO3 = MEK + ACTA :                 GCARR_ac(1.87d-13, 500.0d0);                                                      {2023/05/14; Brewer2023; JFB}
ATO2 + MCO3 = MGLY + ACTA :                  GCARR_ac(1.87d-13, 500.0d0);                                                      {2017/07/27; Fix C creation; SAS,BHH,MJE}
KO2 + MCO3 = MEK + ACTA :                    GCARR_ac(1.87d-13, 500.0d0);
R4N1 + MCO3 = RCHO + ACTA + NO2 :            GCARR_ac(1.87d-13, 500.0d0);
ALK4N1 + MCO3 = RCHO + ACTA + NO2 :          GCARR_ac(1.87d-13, 500.0d0);                                                      {2023/05/14; Brewer2023; JFB}
PRN1 + MCO3 = RCHO + ACTA + NO2 :            GCARR_ac(1.87d-13, 500.0d0);
B3O2 + MCO3 = ACET + ACTA :                  GCARR_ac(1.87d-13, 500.0d0);
MCO3 + ETO2 = MO2 + ALD2 + HO2 :             GCARR_ac(1.68d-12, 500.0d0);
MCO3 + OTHRO2 = MO2 + ALD2 + HO2 :           GCARR_ac(1.68d-12, 500.0d0);                                                      {2019/05/10; Fisher2018; JAF}
MCO3 + ETO2 = ACTA + ALD2 :                  GCARR_ac(1.87d-13, 500.0d0);
MCO3 + OTHRO2 = ACTA + ALD2 :                GCARR_ac(1.87d-13, 500.0d0);                                                      {2019/05/10; Fisher2018; JAF}
RCO3 + MCO3 = MO2 + 0.500OTHRO2 +
 0.070A3O2 + 0.270B3O2 :                     GCARR_ac(2.50d-12, 500.0d0);                                                      {2019/05/10; Fisher2018; JAF}
=======
MCO3 + MCO3 = 2.000MO2 + 2.000CO2 :          GCARR_ac(2.90d-12, 500.0d0);                                                      {2023/04/18; JPL 19-5, Bates2023; KHB}
MCO3 + MO2 = 0.1ACTA + CH2O +
 0.9MO2 + 0.9HO2 + 0.9CO2:                   GCARR_ac(2.00d-12, 500.0d0);                                                      {2023/04/18; Bates2023; KHB}
R4O2 + MCO3 = 0.271MEK + 0.100ACTA +
 0.900MO2 + 0.290ACET + 0.243HO2 +
 0.290ALD2 + 0.290OTHRO2 + 0.255RCHO
 + 0.045A3O2 + 0.162B3O2 + 0.900CO2:         GCARR_ac(1.87d-12, 500.0d0);                                                      {2023/04/18; Bates2023; KHB}
ATO2 + MCO3 = 0.900MO2 + 0.900MCO3 +
 0.900CH2O + 0.100MGLY + 0.100ACTA +
 0.900CO2 :                                  GCARR_ac(1.87d-12, 500.0d0);                                                      {2023/04/18; Bates2023; KHB}
KO2 + MCO3 = 0.900MO2 + 0.900MCO3 +
 0.900ALD2 + 0.100MEK + 0.100ACTA +
 0.900CO2 :                                  GCARR_ac(1.87d-12, 500.0d0);                                                      {2023/04/18; Bates2023; KHB}
B3O2 + MCO3 = 0.900MO2 + 0.900HO2 +
 ACET + 0.100ACTA + 0.900CO2 :               GCARR_ac(1.87d-12, 500.0d0);                                                      {2023/04/18; Bates2023; KHB}
R4N1 + MCO3 = 0.900MO2 + 0.100ACTA +
 0.613RCHO + 0.351CH2O + 0.675ALD2 +
 0.270R4O2 + 0.645CO2 + NO2 :                GCARR_ac(1.87d-12, 500.0d0);                                                      {2023/04/18; Bates2023; KHB}
PRN1 + MCO3 = 0.900MO2 + 0.900CH2O +
 0.900CO2 + 0.900ALD2 + 0.100RCHO +
 0.100ACTA + NO2 :                           GCARR_ac(1.87d-12, 500.0d0);                                                      {2023/04/18; Bates2023; KHB}
ETO2 + MCO3 = 0.900MO2 + ALD2 +
 0.900HO2 + 0.100ACTA + 0.900CO2 :           GCARR_ac(1.87d-12, 500.0d0);                                                      {2023/04/18; Bates2023; KHB}
OTHRO2 + MCO3 = 0.900MO2 + ALD2 +
 0.900HO2 + 0.100ACTA + 0.900CO2 :           GCARR_ac(1.87d-12, 500.0d0);                                                      {2019/05/10; Fisher2018; JAF; 2023/04/18; Bates2023; KHB}
PO2 + MCO3 = 0.900MO2 + 0.900HO2 +
 0.900ALD2 + 0.900CH2O + 0.065HAC +
 0.035RCHO + 0.100ACTA + 0.900CO2 :          GCARR_ac(1.87d-12, 500.0d0);                                                      {2023/04/18; Bates2023; KHB}
A3O2 + MCO3 = 0.900MO2 + 0.900HO2 +
 RCHO + 0.100ACTA + 0.900CO2 :               GCARR_ac(1.87d-12, 500.0d0);                                                      {2023/04/18; Bates2023; KHB}
RCO3 + MCO3 = MO2 + 0.490OTHRO2 +
 0.070A3O2 + 0.270B3O2 + 2.000CO2 :          GCARR_ac(2.50d-12, 500.0d0);                                                      {2019/05/10; Fisher2018; JAF; 2023/04/18; Bates2023; KHB}
RCO3 + MO2 = CH2O + CO2 + HO2 +
 0.490OTHRO2 + 0.070A3O2 + 0.270B3O2 :       GCARR_ac(1.87d-12, 500.0d0);                                                      {2019/05/10; Fisher2018; JAF; 2023/04/18; Bates2023; KHB}
>>>>>>> origin/dev/14.5.0

<<<<<<< HEAD
AROMP5 = 0.2HO2 + 0.2ALK4O2 +
 0.2MGLY + 1.2RCHO :                         1.5d-3;                                                                           {2021/09/29; Bates2021b; KHB,MSL}{2023/05/14; Brewer2023; JFB}
=======
AROMP5 = 0.2HO2 + 0.2R4O2 +
 0.2MGLY + 1.15RCHO + 0.05CO :               1.5d-3;                                                                           {2021/09/29; Bates2021b; KHB,MSL; 2023/04/18; Bates2023; KHB}
>>>>>>> origin/dev/14.5.0

<<<<<<< HEAD
R4P + hv = OH + HO2 + RCHO :                 PHOTOL(83);
ALK4P + hv = OH + HO2 + RCHO :               PHOTOL(83);     {2023/05/14; Brewer2023; JFB}
PP + hv = OH + HO2 + ALD2 + CH2O :           PHOTOL(84);
RP + hv = OH + HO2 + ALD2 :                  PHOTOL(85);
R4N2 + hv = NO2 + 0.320ACET + 0.190MEK +
 0.180MO2 + 0.270HO2 + 0.320ALD2 +
 0.130RCHO + 0.050A3O2 + 0.180B3O2 +
 0.320OTHRO2 :                               PHOTOL(98);
ALK4N2 + hv = NO2 + 0.320ACET + 0.190MEK +
 0.180MO2 + 0.270HO2 + 0.320ALD2 +
 0.130RCHO + 0.050A3O2 + 0.180B3O2 +
 0.320OTHRO2 :                               PHOTOL(98);     {2023/05/14; Brewer2023; JFB}
MAP + hv = OH + MO2 :                        PHOTOL(99);
=======
R4P + hv = OH + HO2 + 1.500RCHO :            PHOTOL(83);     {2023/04/18; Bates2023; KHB}
PP + hv = OH + HO2 + ALD2 + CH2O :           PHOTOL(84);
RP + hv = OH + HO2 + ALD2 + MO2 :            PHOTOL(85);     {2023/04/18; Bates2023; KHB}
R4N2 + hv = NO2 + 0.340ACET + 0.190MEK +
 0.190MO2 + 0.270HO2 + 0.340ALD2 +
 0.150RCHO + 0.050A3O2 + 0.190B3O2 +
 0.340OTHRO2 :                               PHOTOL(98);     {2023/04/18; Bates2023; KHB}
MAP + hv = OH + MO2 + CO2 :                  PHOTOL(99);     {2023/04/18; Bates2023; KHB}
>>>>>>> origin/dev/14.5.0

```

**Comment by kelvinhb** [comment]
Hi team,

My understanding of Jared's update is that it creates a new duplicate set of some ALK4-type species that are functionally identical to what's already in there (as in, all the same reactions are duplicated) but they allow us to keep separate some of the products that were previously made both from biogenic and anthropogenic sources. The problem arises in that, in the JPL/IUPAC updates, we've modified product yields in a lot of those reactions that Jared duplicates to better conserve carbon -- most of them were out of whack because of rounding errors or misinterpretations in how much carbon is contained in the generic "R" species (RCHO, R4P, etc). I think the goal here should be to have the duplicated reactions match the JPL/IUPAC updated ones. If that sounds alright to everyone, I can go through and pick out which reactions have changed and modify those branching ratios in Jared's updates -- unless anyone thinks we should do this some other way?

Also, it looks like these updates use the same photolysis reference numbers -- e.g. the photolysis reactions for R4P + hv and  ALK4P + hv both have the rate "PHOTOL(83)". Does the code to calculate photolysis rates interpret that correctly? If so it seems like there's a lot of simplification we can do in the photolysis section, since tons of those reactions have effectively the same rate coefficients....

-Kelvin

**Comment by msulprizio** [comment]
Thanks for the feedback @kelvinhb. Based on your comments, I can make a first pass at combining Jared's updates with the latest JPL/IUPAC rates already used in the latest version. I will also have a look at the photolysis reference numbers and get back to you all.

**Comment by msulprizio** [comment]
@kelvinhb @JFBrewer I have merged the ALK4 and R4N2 chemistry updates up to the latest `dev/14.5.0` branch. I resolved the conflicts as advised by Kelvin above (adding new reactions from Jared's original updates while retaining the updated JPL/IUPAC rates from Kelvin's updates in 14.3). Please feel free to review the changes [here](https://github.com/geoschem/geos-chem/pull/2352/files#diff-8e35e71e59f10e272304d589426c0f3d5f9547b326d4d7528381121828f26759) and let me know if you see any errors. 

Note that the following reactions in Jared's original updates have been removed:

```
ALK4O2 + MCO3 = MEK + ACTA :                 GCARR_ac(1.87d-13, 500.0d0);                                                      {2023/05/14; Brewer2023; JFB}
ALK4N1 + MCO3 = RCHO + ACTA + NO2 :          GCARR_ac(1.87d-13, 500.0d0);                                                      {2023/05/14; Brewer2023; JFB}
```

This is because the following reactions were removed from https://github.com/geoschem/geos-chem/pull/1765:

```
R4O2 + MCO3 = MEK + ACTA :                   GCARR_ac(1.87d-13, 500.0d0);
R4N1 + MCO3 = RCHO + ACTA + NO2 :            GCARR_ac(1.87d-13, 500.0d0);
```

I am now running a 1-month benchmark locally to test these updates and will post a summary here before merging into 14.5.0.

**Comment by JFBrewer** [comment]
Yes, this makes sense to me. I agree with Kevin's statements above. The goal of my changes was to not change much about the underlying chemistry but to make certain that anthropogenic emissions weren't leading to the creation of primarily biogenic tracers in a non-physical way. In most places this didn't make a major difference but it did matter over regions like Korea with low biogenic and high anthropogenic emissions.

**Comment by msulprizio** [comment]
Thanks for confirming @JFBrewer!

**Comment by yantosca** [comment]
Thanks @msulprizio and @JFBrewer!  I'll start testing and merging this into 14.5.0.

**Comment by yantosca** [comment]
After merging (locally) into dev/14.5.0, all GEOS-Chem Classic integration tests pass:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

GCClassic #6f22240 GEOS-Chem submod update: Merge PR #2398 (Uncomment cations for HETP)
GEOS-Chem #0a392d465 Merge PR #2352 (Fixes for ALK4 and R4N2 chemistry from J. Brewer)
HEMCO     #e68ebae HEMCO 3.9.2 release

Using 24 OpenMP threads
Number of execution tests: 28

Submitted as SLURM job: 42182865
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
After merging locally into dev/14.5.0, all GCHP integration tests passed:
```console
==============================================================================
GCHP: Execution Test Results

GCHP      #136fa70 GEOS-Chem submod update: Merge PR #2398 (Uncomment cations for HETP)
GEOS-Chem #0a392d465 Merge PR #2352 (Fixes for ALK4 and R4N2 chemistry from J. Brewer)
HEMCO     #

Number of execution tests: 11

Submitted as SLURM job: 42182917
==============================================================================
 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Pull request merged**
