### PR TITLE
Bug fix: restore consideration of sea salt alkalinity to heterogenerous acid-catalyzed reactions of halogens on sea salt aerosols

### LINKED ISSUE #1547: [BUG/ISSUE] sea salt alkalinity and heterogeneous acid-catalyzed halogen chemistry
### What institution are you from?
University of Washington

### Description of the problem
Sea-salt alkalinity was not appropriately considered in the calculation of heterogeneous acid-catalyzed reactions of halogens on sea salt aerosols. The computations were being performed assuming that 100% of sea salt aerosol alkalinity had been titrated. In other words, aerosol pH calculations in ISORROPIA were being applied to total fine-mode sea salt aerosol, and all coarse-mode sea salt aerosol was assumed to have a pH of 5, no matter how much of the alkalinity was being titrated.

### Description of troubleshooting performed
This fix will mainly affect simulations where sea salt debromination is turned on. It is currently turned off by default. The attached difference plots show the comparison with sea salt debromination turned on in both the dev and ref simulations.

### GEOS-Chem version
13.4.1

### Description of modifications
I have fixed this by calculating two new variables in fullchem_HetStateFuncs, f_Alk_SSA and f_Alk_SSC, in KPP that compute the fraction of fine and coarse mode sea salt aerosol that is alkaline. This fraction is then used in fullchem_RateLawFuncs when calculating the first-order uptake of gas onto acidic sea salt aerosol. I multiply (1 - f_Alk_SSA) by the sea salt surface area so that only the acid fraction of the sea salt surface area is used in the rate calculations. I consider this a bug fix because this is how the calculation was performed before the sulfur and sea salt alkalinity calculations were moved into KPP.
[BrClI_hetchem.txt](https://github.com/geoschem/geos-chem/files/10142992/BrClI_hetchem.txt)

### Figures
I'm showing difference plots for BrO and O3 for July 2019. I can provide more species upon request. The figure below shows that this fix causes BrO to decrease everywhere as expected. O3 is more complicated, showing increases in the SH and decreases in the NH.
[ssdebromBrClI_SROSO4s_O3BrO.pdf](https://github.com/geoschem/geos-chem/files/10143045/ssdebromBrClI_SROSO4s_O3BrO.pdf)

I expected increases in O3 everywhere. The reason for the increase in O3 in the NH is entirely due to heterogeneous iodine chemistry. The figure below shows the same difference plots except that the dev simulation only fixed the Br and Cl chemistry (not the I chemistry). So it is the fix to the iodine chemistry that is causing the decrease in NH ozone. The iodine chemistry needs more looking into and may be related to some heterogeneous iodine chemistry that was removed in the more recent versions of GEOS-Chem. I think this is more of a science issue than a bug fix so I'll consider that separately.
[alkssdebromBrCl_alkssdebrom_BrOO3.pdf](https://github.com/geoschem/geos-chem/files/10143090/alkssdebromBrCl_alkssdebrom_BrOO3.pdf)

### PR DESCRIPTION
**Pull request by yantosca**
This is the corresponding PR to #1547.  The code (which was based off 13.4.1) has now been merged up to 14.1.0-alpha.6. 
This PR fixes a bug in heterogeneous chemistry by restoring sea salt alkalinity to certain reactions of halogen chemistry.   It should follow PR #1506. 

Please see #1547 for a complete description of this issue by @beckyalexander, with plots

Closes #1547.

Tagging @beckyalexander @mje1398 @hazel008

### CODE REVIEW

**Comment by yantosca** [comment]
Integration tests pending

**Comment by yantosca** [comment]
All GEOS-Chem integration tests passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

Using 24 OpenMP threads
Number of execution tests: 48
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gc_025x03125_CH4_geosfp_47L_na...................Execute Simulation.....PASS
gc_025x03125_fullchem_geosfp_47L_na..............Execute Simulation.....PASS
gc_05x0625_CH4_merra2_47L_na.....................Execute Simulation.....PASS
gc_05x0625_fullchem_merra2_47L_na................Execute Simulation.....PASS
gc_2x25_aerosol_merra2...........................Execute Simulation.....PASS
gc_2x25_CH4_merra2...............................Execute Simulation.....PASS
gc_2x25_CO2_merra2...............................Execute Simulation.....PASS
gc_2x25_fullchem_merra2..........................Execute Simulation.....PASS
gc_2x25_Hg_merra2................................Execute Simulation.....PASS
gc_2x25_metals_merra2............................Execute Simulation.....PASS
gc_2x25_POPs_BaP_merra2..........................Execute Simulation.....PASS
gc_2x25_tagCH4_merra2............................Execute Simulation.....PASS
gc_2x25_tagCO_merra2.............................Execute Simulation.....PASS
gc_2x25_tagO3_merra2.............................Execute Simulation.....PASS
gc_2x25_TransportTracers_merra2..................Execute Simulation.....PASS
gc_2x25_TransportTracers_merra2_LuoWd............Execute Simulation.....PASS
gc_4x5_aerosol_geosfp............................Execute Simulation.....PASS
gc_4x5_aerosol_merra2............................Execute Simulation.....PASS
gc_4x5_CH4_geosfp................................Execute Simulation.....PASS
gc_4x5_CH4_merra2................................Execute Simulation.....PASS
gc_4x5_fullchem_aciduptake_merra2................Execute Simulation.....PASS
gc_4x5_fullchem_APM_merra2.......................Execute Simulation.....PASS
gc_4x5_fullchem_benchmark_merra2.................Execute Simulation.....PASS
gc_4x5_fullchem_complexSOA_merra2................Execute Simulation.....PASS
gc_4x5_fullchem_complexSOA_SVPOA_merra2..........Execute Simulation.....PASS
gc_4x5_fullchem_geosfp...........................Execute Simulation.....PASS
gc_4x5_fullchem_marinePOA_merra2.................Execute Simulation.....PASS
gc_4x5_fullchem_merra2...........................Execute Simulation.....PASS
gc_4x5_fullchem_merra2_47L.......................Execute Simulation.....PASS
gc_4x5_fullchem_merra2_LuoWd.....................Execute Simulation.....PASS
gc_4x5_fullchem_RRTMG_merra2.....................Execute Simulation.....PASS
gc_4x5_fullchem_TOMAS15_merra2_47L...............Execute Simulation.....PASS
gc_4x5_fullchem_TOMAS40_merra2_47L...............Execute Simulation.....PASS
gc_4x5_Hg_geosfp.................................Execute Simulation.....PASS
gc_4x5_Hg_merra2.................................Execute Simulation.....PASS
gc_4x5_metals_merra2.............................Execute Simulation.....PASS
gc_4x5_POPs_BaP_geosfp...........................Execute Simulation.....PASS
gc_4x5_POPs_BaP_merra2...........................Execute Simulation.....PASS
gc_4x5_tagCH4_geosfp.............................Execute Simulation.....PASS
gc_4x5_tagCH4_merra2.............................Execute Simulation.....PASS
gc_4x5_tagCO_geosfp..............................Execute Simulation.....PASS
gc_4x5_tagCO_merra2..............................Execute Simulation.....PASS
gc_4x5_tagO3_geosfp..............................Execute Simulation.....PASS
gc_4x5_tagO3_merra2..............................Execute Simulation.....PASS
gc_4x5_TransportTracers_geosfp...................Execute Simulation.....PASS
gc_4x5_TransportTracers_geosfp_LuoWd.............Execute Simulation.....PASS
gc_4x5_TransportTracers_merra2...................Execute Simulation.....PASS
gc_4x5_TransportTracers_merra2_LuoWd.............Execute Simulation.....PASS
 
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 48
Execution tests failed: 0
Execution tests not yet completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
All GCHP integration tests passed:
```console
==============================================================================
GCHP: Execution Test Results

Number of execution tests: 3
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gchp_fullchem_benchmark_merra2_c48...............Execute Simulation.....PASS
gchp_fullchem_standard_merra2_c24................Execute Simulation.....PASS
gchp_TransportTracers_geosfp_c24.................Execute Simulation.....PASS
 
Summary of execution test results:
------------------------------------------------------------------------------
Execution tests passed:        3
Execution tests failed:        0
Execution tests not completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Review by msulprizio — APPROVED** [review]

**Comment by msulprizio** [comment]
This pull request was shown to cause convergence errors in a GCClassic 4x5 benchmark simulation (see errors below). @yantosca is looking into a fix in the `bugfix/salal-salcal-rate-law` branch. We will restore 14.1.0 to the previous tag (14.1.0-alpha.13) and resubmit a PR for this fix when all issues have been resolved.

```
---> DATE: 2019/07/02  UTC: 06:00  X-HRS:     30.000000
HEMCO: Opening /ExtData/HEMCO/OFFLINE_LIGHTNING/v2020-03/MERRA2/2019/FLASH_CTH_MERRA2_0.5x0.625_2019_07.nc4
HEMCO WARNING: Data is treated as unitless, but file attribute suggests it is not: km-2 s-1. File: /ExtData/HEMCO/OFFLINE_LIGHTNING/v2020-03/MERRA2/2019/FLASH_CTH_MERRA2_0.5x0.625_2019_07.nc4
--> LOCATION: HCOIO_READ (HCOIO_READ_STD_MOD.F90)
     - Found all A1     met fields for 2019/07/02 06:30
     - Found all A3cld  met fields for 2019/07/02 07:30
     - Found all A3dyn  met fields for 2019/07/02 07:30
     - Found all A3mstC met fields for 2019/07/02 07:30
     - Found all A3mstE met fields for 2019/07/02 07:30
     - Found all I3     met fields for 2019/07/02 09:00
 Forced exit from Rosenbrock due to the following error:
 --> Step size too small: T + 10*H = T or H < Roundoff
 T=   0.0000000000000000      and H=   0.0000000000000000     
 ### INTEGRATE RETURNED ERROR AT:           14          13           1
 Forced exit from Rosenbrock due to the following error:
 --> Step size too small: T + 10*H = T or H < Roundoff
 T=   0.0000000000000000      and H=   0.0000000000000000     
## INTEGRATE FAILED TWICE !!! 
 #############################################################################################################################################################################################################################################
 ### KPP DEBUG OUTPUT!
 ### Species concentrations at problem box           14          13           1
 #############################################################################################################################################################################################################################################
 ###                        NaN CH2I2
 ###                        NaN CH2IBr
...etc...
 #############################################################################################################################################################################################################################################
 ### KPP DEBUG OUTPUT!
 ### Reaction rates at problem box           14          13           1
 #############################################################################################################################################################################################################################################
                  Infinity SALAAL + O3 + SO2 --> LOx + PSO4 + SO4 - SALAAL
   6.8799391718909510E-009 SALAAL + HCl --> SALACL
   2.3078344094468533E-008 SALAAL + HNO3 --> LOx + NIT
                  Infinity SALCAL + O3 + SO2 --> SO4s + LOx - SALCAL
   5.9665973977075313E-012 SALCAL + HCl --> SALCCL
   9.0869745784508394E-012 SALCAL + HNO3 --> LOx + NITs
   1.2896042944368770E-016 H2O2 + SO2 --> PSO4 + SO4
...etc...

 Forced exit from Rosenbrock due to the following error:
 --> Step size too small: T + 10*H = T or H < Roundoff
 T=   11.964464782736020      and H=   8.4522004874768389E-015
 ### INTEGRATE RETURNED ERROR AT:           24          28           5
===============================================================================
GEOS-Chem ERROR: KPP failed to converge after 2 iterations!
 -> at Do_FullChem (in module GeosCore/FullChem_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Incorrect species units after Do_FullChem!
 -> at Do_Chemistry  (in module GeosCore/chemistry_mod.F90)
===============================================================================

===============================================================================
GEOS-CHEM ERROR: Error encountered in "Do_Chemistry"!
STOP at  -> at GEOS-Chem (in GeosCore/main.F90)
===============================================================================
```

**Comment by msulprizio** [comment]
This PR is superseded by https://github.com/geoschem/geos-chem/pull/1702 which will go into 14.2.0.

**Pull request merged**
