### PR TITLE
[WIP] Remove non-zero diffs caused by splitting up simulations in time -- Supersedes #1198

### PR DESCRIPTION
**Pull request by yantosca**
## Overview
This bug fix takes @lizziel's PR #1198 and merges it up to the state of 13.4.0-rc.3, in order to take advantage of subsequent bug fixes and updates.

## References:
  - [Documentation of this issue](https://docs.google.com/document/d/1UWXLrSkvc1GW9ZI3Cov06w5uzBDvIwpZWzu-mprpexA/edit?usp=sharing) by @lizziel

### CODE REVIEW

**Comment by msulprizio** [comment]
This branch should be merged up to `13.4.0-alpha.27` to ensure we include the fix to chemistry_mod.F90.

**Comment by yantosca** [comment]
> This branch should be merged up to `13.4.0-alpha.27` to ensure we include the fix to chemistry_mod.F90.

Now done with commit f0b71c6bf333a66aaea7d2b434d38a472dbc8d34

**Comment by yantosca** [comment]
Added updates to read restart fields:
  - AeroH2O_SNA (points to variable Chem_AeroH2OSNA in restart file)
  - JOH (points to variable Chem_JOH in restart file)
  - JNO2 (points to variable Chem_JNO2 in restart file)

Also streamlined the code in `GeosCore/hco_utilities_gc_mod.F90` to reduce clutter and improve readability of the log file output.  Integration tests are running.

**Comment by lizziel** [comment]
fyi, I am still working on this as well.

**Comment by lizziel** [comment]
This PR is superseded by https://github.com/geoschem/geos-chem/pull/1229.

**Pull request closed without merging**
