### PR TITLE
Add fixes to HEMCO_Config.rc for CH4 and carbon simulations

### LINKED ISSUE #2036: GHGI_v2_Express_Ext inventory not properly read in CH4 simulations
### Name and Institution (Required)

Name: Melissa Sulprizio
Institution: Harvard / GCST

### Description of your issue or question

@djvaron found the GHGI emissions (express extension option) were not properly read in GEOS-Chem CH4 simulations for 14.2.0 through 14.2.2. The issue was the use of logicals in HEMCO_Config.rc. Currently the GHGI express extension option is bracketed with:

```
(((GHGI_v2_Express_Ext.and..not.GHGI_v2
```

This is to make sure that if users have both GHGI_v2 and GHGI_v2_Express_Ext set to true that only the official GHGI_v2 product will be used to avoid double counting. However, it turns out HEMCO can only handle use of `.or.` and `.not.` within the logical statements -- `.and.` is not supported. To get around this, we can separate the statement into two lines:

```
(((GHGI_v2_Express_Ext
(((.not.GHGI_v2
```

A fix for this will be included in 14.2.3.

### PR DESCRIPTION
**Pull request by msulprizio**
### Name and Institution (Required)

Name: Melissa Sulprizio
Institution: Harvard / GCST

### Describe the update

This pull request includes the following fixes:

1. Remove the use of `.and.` from HEMCO_Config.rc files because it is not actually supported by HEMCO. This addresses [issue #2036](https://github.com/geoschem/geos-chem/issues/2036).
2. Move `OH_pert_factor` entry outside of `EMISSIONS` logical in HEMCO_Config.rc to ensure it is always defined and applied to the OH fields.
3. Remove definition of `METDIR` from HEMCO_Config.rc files for simulations types and solely use definition from the HEMCO_Config.rc.*metfields file.

### Expected changes

Fixes 1 and 2 above will will only impact the carbon and CH4 simulations, while fix 3 is a zero-diff change.

### Reference(s)

If this is a science update, please provide a literature citation.

### Related Github Issue(s)

Closes #2036

### CODE REVIEW

**Review by yantosca — APPROVED** [review]
This PR looks good to merge.  Thanks @msulprizio!

**Comment by yantosca** [comment]
@msulprizio:  GEOS-Chem Classic CH4 and carbon Integration tests are failing with:
```console
HEMCO ERROR: Cannot find field GHGI_OIL_EXP_SF. Please check variable name in the config. file
 
HEMCO ERROR: Error encountered in routine HCOIO_Read!
 
HEMCO ERROR: Error in HCOIO_DATAREAD called from HEMCO ReadList_Fill: GHGI_OIL_EXP_SF
 --> LOCATION: ReadList_Fill (HCO_ReadList_Mod.F90)
```
Maybe still some config file issues.  I can take a look.

**Comment by msulprizio** [comment]
> @msulprizio: GEOS-Chem Classic CH4 and carbon Integration tests are failing with:

That's strange. My integration tests on this branch all passed, except for TOMAS14 and TOMAS40 (known issue). I can help look into it.

**Comment by msulprizio** [comment]
I know what the issue is. I forgot to mention you need to incorporate [HEMCO PR #248](https://github.com/geoschem/HEMCO/pull/248) prior to merging this fix. The error you are receiving above is because the variable name in the netCDF file is too long for HEMCO to handle, but the HEMCO PR fixes that.

**Comment by yantosca** [comment]
Oops!  I forgot to check out the dev/no-diff-to-benchmark branch in HEMCO.  That'll fix it.  Stay tuned for a rerun, thanks @msulprizio.

**Comment by yantosca** [comment]
All GCHP integration tests passed:
```console
==============================================================================
GCHP: Execution Test Results

GCHP      #074494e GEOS-Chem submodule update: Merge PR #2009 fixing links to RTD
GEOS-Chem #78c1b7dc3 Merge PR #2042 (Fix HEMCO_Config.rc for CH4 and carbon simulations)
HEMCO     #6ab11ea Merge PR #245 (Rename HEMCO_Config.rc.sample to HEMCO_Config.rc)

Number of execution tests: 5

Submitted as SLURM job: 10401258
==============================================================================
```
All GCHP integration tests were identical w/r/t 14.2.2.

**Comment by yantosca** [comment]
All GEOS-Chem Classic integration tests passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

GCClassic #f5b5694 Merge branch 'docs/dev' into dev/14.2.2
GEOS-Chem #78c1b7dc3 Merge PR #2042 (Fix HEMCO_Config.rc for CH4 and carbon simulations)
HEMCO     #6ab11ea Merge PR #245 (Rename HEMCO_Config.rc.sample to HEMCO_Config.rc)

Using 24 OpenMP threads
Number of execution tests: 27

Submitted as SLURM job: 10362106
==============================================================================
 ```
All tests except the following were identical to 14.2.2:
- CH4, carbon (due to config file updates in this PR)
- APM (parallelization issue)
- RRTMG (parallelization issue in diagnostics)

**Pull request merged**
