### PR TITLE
Removing unused carbon simulation options

### PR DESCRIPTION
**Pull request by hannahnesser**
### Name and Institution (Required)

Name: Hannah Nesser
Institution: JPL

### Confirm you have reviewed the following documentation

- [X] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/CONTRIBUTING.html)

### Describe the update

I have removed the following options from the CO2 simulation (including from the carbon single tracer simulation) because they were unused: LFOSSIL, LBIODIURNAL, LBIONETCLIM, LOCEAN, LSHIP, LPLANE, LFFBKGRD, LSHIPTAG,  LPLANETAG

I also added a default value for tag_land_fossil_fuel_CO2: false, which was previously missing.

### Expected changes

This should not change any model operations since all removed options were unused.

### Reference(s)

None

### Related Github Issue(s)

None

### CODE REVIEW

**Review by yantosca — CHANGES_REQUESTED** [review]
Thanks @hannahnesser, we can get this into 14.4.0 soon.  One request though, would you be able to add a note in the CHANGELOG.md file that the unused options have been removed?   Thanks!

**Review by yantosca — CHANGES_REQUESTED** [review]
Also we would need to remove the corresponding entries from ExtData.rc.

**Comment by hannahnesser** [comment]
> Thanks @hannahnesser, we can get this into 14.4.0 soon. One request though, would you be able to add a note in the CHANGELOG.md file that the unused options have been removed? Thanks!

I think this is now resolved with [196ebed](https://github.com/geoschem/geos-chem/pull/2266/commits/196ebed02f51de66ba420c7f3357e16074110f4d)!

**Review by yantosca — APPROVED** [review]
Approved!  Thanks @hannahnesser.  I will start testing this.

**Comment by yantosca** [comment]
All GEOS-Chem Classic integration tests passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

GCClassic #db77d09 GEOS-Chem submod update: Merge PR #2261 (Add GHGI postmeter emissions)
GEOS-Chem #c2b5130ed Merge PR #2266 (Removing unused carbon simulation options)
HEMCO     #fddcae5 Update version to 3.8.1 for release

Using 24 OpenMP threads
Number of execution tests: 29

Submitted as SLURM job: 29619287
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
All GCHP integration tests passed:
```console
==============================================================================
GCHP: Execution Test Results

GCHP      #abc24bb MAPL update: Merge PR #34 (Bug fix for stretched-grid restart attr check)
GEOS-Chem #c2b5130ed Merge PR #2266 (Removing unused carbon simulation options)
HEMCO     #fddcae5 Update version to 3.8.1 for release

Number of execution tests: 11

Submitted as SLURM job: 29621321
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
All tests were zero-diff w/r/t PR #2249.

**Pull request merged**
