### PR TITLE
Rename "native" to "raw" in GCHP run directory creation scripts & templates

### LINKED ISSUE #2140: [FEATURE REQUEST] Change GCHP run directory terminology to use raw rather than native
### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### New GEOS-Chem feature or discussion

The GCHP run directory creation script prompts users to choose between "native" or "processed" meteorology files. This is confusing since in some cases native and processed are the same grid resolution. It would be better to use "raw" instead of native.

### PR DESCRIPTION
**Pull request by yantosca**
### Name and Institution (Required)

Name: Bob Yantosca
Institution: Harvard + GCST

### Confirm you have reviewed the following documentation

- [x] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/CONTRIBUTING.html)

### Describe the update
This PR implements the feature request by @lizziel in #2140, namely:
1. Rename instances of "native" to "raw" in `run/GCHP/createRunDir.sh`;
2. Rename template files, e.g. 'geosit.native*.txt` -> `geosit.raw*.txt`

This will help avoid confusion in terminology.  Henceforth,  **raw** refers to data files obtained directly from GMAO.  It could be possible that a processed data file and a raw data file could both be at the native resolution of the meteorology, so using raw is more accurate.

### Expected changes

This should be a zero-diff update (pending verification by integration tests).

### Related Github Issue(s)

- Closes #2140

### CODE REVIEW

**Comment by msulprizio** [comment]
In files like `run/shared/settings/geosit/geosit.raw_cs.txt`, should we also change the line

https://github.com/geoschem/geos-chem/blob/39aced92ad66159e8abfdff6114230c6da30ba80/run/shared/settings/geosit/geosit.raw_ll.txt#L4

to

```
RUNDIR_MET_DIR_RAW="${RUNDIR_DATA_ROOT}/GEOS_0.5x0.625/GEOS_IT_Raw"
```

We should also check uses of `RUNDIR_MET_DIR_NATIVE` in the config files and rename that to `RUNDIR_MET_DIR_RAW`.

This change would also require changing the directory name in ExtData. As discussed, we should rename `GEOS_IT_Native` to `GEOS_IT_Raw` and then create a symbolic link for `GEOS_IT_Native` pointing to `GEOS_IT_Raw`. This needs to be done at WashU as well and we can coordinate with @yidant.

**Comment by yantosca** [comment]
Ugh, the GCHP integration test failure was caused by this issue on Cannon:
```consol
Done sourcing gchp.env
srun: fatal: cpus_per_task set by two different environment variables SLURM_CPUS_PER_TASK=1 != SLURM_TRES_PER_TASK=cpu:10
```

**Comment by yantosca** [comment]
@msulprizio, @lizziel: Here is a list of environment variables with `NATIVE` in the name.

### MERRA-2
```console
settings/merra2.txt:4:RUNDIR_MET_DIR_NATIVE="${RUNDIR_DATA_ROOT}/GEOS_0.5x0.625/MERRA2"
settings/merra2.txt:10:RUNDIR_MET_NATIVE_RES='0.5x0.625'
settings/merra2.txt:20:RUNDIR_METLIGHTNING_DIR_NATIVE="${RUNDIR_DATA_ROOT}/GEOS_0.5x0.625/MERRA2"
settings/merra2.txt:21:RUNDIR_METLIGHTNING_NATIVE_RES='0.5x0.625'
settings/modele2.1.txt:6:RUNDIR_MET_NATIVE_RES='2x2.5'
```

### GEOS-FP
```console
settings/geosfp/geosfp.derived_1hr_wind_cs.txt:6:PS1       Pa            N Y  0        none  0.01 PS              ./MetDir/../../GEOS_C720/GEOS_FP_Native/Y%y4/M%m2/D%d2/GEOS.fp.asm.inst_1hr_ctm_c0720_v72.%y4%m2%d2_%h2%n2.V01.nc4 2014-02-20T00:00:00P01:00
settings/geosfp/geosfp.derived_1hr_wind_cs.txt:7:PS2       Pa            N Y  0;001000 none  0.01 PS              ./MetDir/../../GEOS_C720/GEOS_FP_Native/Y%y4/M%m2/D%d2/GEOS.fp.asm.inst_1hr_ctm_c0720_v72.%y4%m2%d2_%h2%n2.V01.nc4 2014-02-20T00:00:00P01:00
settings/geosfp/geosfp.derived_1hr_wind_cs.txt:8:SPHU1     kg_kg-1       N Y  0        none  none QV              ./MetDir/../../GEOS_C720/GEOS_FP_Native/Y%y4/M%m2/D%d2/GEOS.fp.asm.inst_1hr_ctm_c0720_v72.%y4%m2%d2_%h2%n2.V01.nc4 2014-02-20T00:00:00P01:00
settings/geosfp/geosfp.derived_1hr_wind_cs.txt:9:SPHU2     kg_kg-1       N Y  0;001000 none  none QV              ./MetDir/../../GEOS_C720/GEOS_FP_Native/Y%y4/M%m2/D%d2/GEOS.fp.asm.inst_1hr_ctm_c0720_v72.%y4%m2%d2_%h2%n2.V01.nc4 2014-02-20T00:00:00P01:00
settings/geosfp/geosfp.preprocessed_ll.txt:4:RUNDIR_MET_DIR_NATIVE="${RUNDIR_DATA_ROOT}/GEOS_0.25x0.3125/GEOS_FP"
settings/geosfp/geosfp.preprocessed_ll.txt:21:RUNDIR_METLIGHTNING_NATIVE_RES='0.25x0.3125'
settings/geosfp/geosfp.raw_1hr_mass_flux_cs.txt:5:MFXC;MFYC Pa_m+2_s-1    N H F0;003000 none  0.6666666 MFXC;MFYC  ./MetDir/../../GEOS_C720/GEOS_FP_Native/Y%y4/M%m2/D%d2/GEOS.fp.asm.tavg_1hr_ctm_c0720_v72.%y4%m2%d2_%h2%n2.V01.nc4 2021-03-11T00:30:00P01:00
settings/geosfp/geosfp.raw_1hr_mass_flux_cs.txt:6:CXC;CYC   1             N H F0;003000 none  none CX;CY           ./MetDir/../../GEOS_C720/GEOS_FP_Native/Y%y4/M%m2/D%d2/GEOS.fp.asm.tavg_1hr_ctm_c0720_v72.%y4%m2%d2_%h2%n2.V01.nc4 2021-03-11T00:30:00P01:00
settings/geosfp/geosfp.raw_1hr_mass_flux_cs.txt:7:PS1       Pa            N Y  0        none  0.01 PS              ./MetDir/../../GEOS_C720/GEOS_FP_Native/Y%y4/M%m2/D%d2/GEOS.fp.asm.inst_1hr_ctm_c0720_v72.%y4%m2%d2_%h2%n2.V01.nc4 2021-03-11T00:00:00P01:00
settings/geosfp/geosfp.raw_1hr_mass_flux_cs.txt:8:PS2       Pa            N Y  0;001000 none  0.01 PS              ./MetDir/../../GEOS_C720/GEOS_FP_Native/Y%y4/M%m2/D%d2/GEOS.fp.asm.inst_1hr_ctm_c0720_v72.%y4%m2%d2_%h2%n2.V01.nc4 2021-03-11T00:00:00P01:00
settings/geosfp/geosfp.raw_1hr_mass_flux_cs.txt:9:SPHU1     kg_kg-1       N Y  0        none  none QV              ./MetDir/../../GEOS_C720/GEOS_FP_Native/Y%y4/M%m2/D%d2/GEOS.fp.asm.inst_1hr_ctm_c0720_v72.%y4%m2%d2_%h2%n2.V01.nc4 2021-03-11T00:00:00P01:00
settings/geosfp/geosfp.raw_1hr_mass_flux_cs.txt:10:SPHU2     kg_kg-1       N Y  0;001000 none  none QV              ./MetDir/../../GEOS_C720/GEOS_FP_Native/Y%y4/M%m2/D%d2/GEOS.fp.asm.inst_1hr_ctm_c0720_v72.%y4%m2%d2_%h2%n2.V01.nc4 2021-03-11T00:00:00P01:00
settings/geosfp/geosfp.raw_ll.txt:4:RUNDIR_MET_DIR_NATIVE="${RUNDIR_DATA_ROOT}/GEOS_0.25x0.3125/GEOS_FP_Native"
settings/geosfp/geosfp.raw_ll.txt:18:RUNDIR_METLIGHTNING_DIR_NATIVE="${RUNDIR_DATA_ROOT}/GEOS_0.25x0.3125/GEOS_FP_Native"
settings/geosfp/geosfp.raw_ll.txt:19:RUNDIR_METLIGHTNING_NATIVE_RES='0.25x0.3125'
```

### GEOS-IT
```console
settings/geosit/geosit.preprocessed_ll.txt:4:RUNDIR_MET_DIR_NATIVE="${RUNDIR_DATA_ROOT}/GEOS_0.5x0.625/GEOS_IT"
settings/geosit/geosit.preprocessed_ll.txt:18:RUNDIR_METLIGHTNING_DIR_NATIVE="${RUNDIR_DATA_ROOT}/GEOS_0.5x0.625/MERRA2"
settings/geosit/geosit.preprocessed_ll.txt:19:RUNDIR_METLIGHTNING_NATIVE_RES='0.5x0.625'
settings/geosit/geosit.raw_cs.txt:4:RUNDIR_MET_DIR_NATIVE="${RUNDIR_DATA_ROOT}/GEOS_C180/GEOS_IT_Nativ"
settings/geosit/geosit.raw_cs.txt:19:RUNDIR_METLIGHTNING_DIR_NATIVE="${RUNDIR_DATA_ROOT}/0.5x0.625/MERRA2"
settings/geosit/geosit.raw_cs.txt:20:RUNDIR_METLIGHTNING_NATIVE_RES='0.5x0.625'
settings/geosit/geosit.raw_ll.txt:4:RUNDIR_MET_DIR_NATIVE="${RUNDIR_DATA_ROOT}/GEOS_0.5x0.625/GEOS_IT_Native"
settings/geosit/geosit.raw_ll.txt:19:RUNDIR_METLIGHTNING_DIR_NATIVE="${RUNDIR_DATA_ROOT}/0.5x0.625/MERRA2"
settings/geosit/geosit.raw_ll.txt:20:RUNDIR_METLIGHTNING_NATIVE_RES='0.5x0.625'
```
We should change e.g. `GEOS_FP_Native` to `GEOS_FP_Raw` and `GEOS_IT_Native` to `GEOS_IT_Raw` in directory paths.  However, should we also change e.g. `RUNDIR_MET_NATIVE_RES` and similar?  In this case Native is the native horizontal resolution but not necesarily the resolution of the raw data, right?

**Comment by lizziel** [comment]
Yes, I think we should get rid of `NATIVE` in the `RUNDIR_` variables, but maybe not necessarily replace with `RAW`. I think it is safe to replace `RUNDIR_METLIGHTNING_NATIVE_RES` with simply `RUNDIR_METLIGHTNING_RES`, and `RUNDIR_METLIGHTNING_DIR_NATIVE` with `RUNDIR_METLIGHTNING_DIR`. 

As for `RUNDIR_MET_DIR` and `RUNDIR_MET_DIR_NATIVE`, I wonder if we need both for GCHP. Maybe we can just simply use `RUNDIR_MET_DIR`.

**Review by lizziel — APPROVED** [review]
Looks good. I left a comment about the `RUNDIR_` variables. Updates to that could go in a later PR.

**Comment by yantosca** [comment]
> As for `RUNDIR_MET_DIR` and `RUNDIR_MET_DIR_NATIVE`, I wonder if we need both for GCHP. Maybe we can just simply use `RUNDIR_MET_DIR`.

@lizziel: We might need both for now as the "Raw" points to C180.  I won't touch that except to rename native to raw.
```bash
RUNDIR_MET_DIR="${RUNDIR_DATA_ROOT}/GEOS_${RUNDIR_GRID_DIR}/GEOS_IT"
RUNDIR_MET_DIR_NATIVE="${RUNDIR_DATA_ROOT}/GEOS_C180/GEOS_IT_Native"
```

**Comment by yantosca** [comment]
@lizziel, @msulprizio: I rebased this atop of the PR #2182 so as to take advantage of the `#SBATCH -c  1` in GCHP integration tests.  I've also updated the various snippet files to remove `NATIVE` from the `RUNDIR_METLIGHTNING` etc. files.  Could you take another look when you get a chance?  In the meantime I will run integration tests.  Thanks!

**Review by msulprizio — APPROVED** [review]
Thanks, Bob. Good to merge.

I went ahead and renamed the GEOS_IT_Native and GEOS_FP_Native directories to Raw in the C720 and C180 directories at Harvard. I see you already did it in the 0.25x0.3125 directory. We should do the same at WashU asap.

**Comment by yantosca** [comment]
All GEOS-Chem Classic integration tests passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

GCClassic #7121661 GEOS-Chem submod update: Merge PR #2153 (Rundir updates for GEOS-IT)
GEOS-Chem #476488df9 Rename RUNDIR_METLIGHTNING environment variables to remove "NATIVE"
HEMCO     #f807e1a Update HEMCO version number to 3.8.0 in preparation for release

Using 24 OpenMP threads
Number of execution tests: 26

Submitted as SLURM job: 22767285
==============================================================================
 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
Furthermore, all GEOS-Chem Classic integration tests were zero-diff w/r/t 14.3.0, except:
- APM (known parallelization issue)
- RRTMG (numerical noise in RRTMG collection file)

**Review by lizziel — APPROVED** [review]
I approved this PR but think we should revisit RUNDIR_MET_DIR variables later still. I left a comment in the code on one example where the current usage does not make sense.

**Comment by yantosca** [comment]
All GCHP integration tests failed, as the `MetDir` symbolic link was not created properly.  Rerunning GCHP integration tests now.

**Comment by yantosca** [comment]
After fixing several outstanding issues in commits 810a189 and 9880090, all GCHP integration tests now pass:
```console
==============================================================================
GCHP: Execution Test Results

GCHP      #2b21fe7 GEOS-Chem submod update: Merge PR #2182 (Add #SBATCH -c 1)
GEOS-Chem #9880090b5 Renamed further instances of "native" -> "raw"
HEMCO     #f807e1a Update HEMCO version number to 3.8.0 in preparation for release

Number of execution tests: 6

Submitted as SLURM job: 22841895
==============================================================================
 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
Furthermore, all GCHP integration tests are zero-diff w/r/t 14.3.0.

**Pull request merged**
