### PR TITLE
[WIP] Run directory creation using init_rd.sh and .txt files

### PR DESCRIPTION
**Pull request by Jourdan-He**
I added in a few .txt files with rundir variables corresponding to simulation types 1-3 and full chemistry simulation options 1-8, the default.txt is for simulation type 1 option 1 (full chemistry, standard). The files are under this directory: run/shared/settings

### CODE REVIEW

**Comment by lizziel** [comment]
Hi @Jourdan-He and @LiamBindle, what is the target version for this update? Is it okay if I review when I get back from vacation in late August?

**Comment by lizziel** [comment]
I also suggest adding @msulprizio as a reviewer.

**Comment by Jourdan-He** [comment]
Hi @lizziel , of course! I'm not sure about the target version, currently I'm comparing it to dev.

**Comment by lizziel** [comment]
Hi @Jourdan-He, I am going to review this PR soon. Could you update your original comment to include a full description of the new features in this PR? Things to include are a list of the changes, why they are needed (or how they improve the old way of doing things), and if they fix any existing problems.

**Comment by Jourdan-He** [comment]
Hi @lizziel ,thanks for reminding me! I haven't quite finished writing this PR and just converted it to draft. I will work on it next week, and run some tests before making it ready for review.

**Comment by Jourdan-He** [comment]
@lizziel I'm closing this PR draft as I have commited changes to another branch... The new draft PR is here: https://github.com/geoschem/geos-chem/pull/1504 Sorry about the change

**Pull request closed without merging**
