### PR TITLE
Fix uptake coefficients on stratospheric aerosol

### PR DESCRIPTION
**Pull request by cdholmes**
### Name and Institution

Name: Christopher Holmes
Institution: FSU

### Describe the update

This PR addresses the bug identified in issue #2204

Corrected the formula for 1st order heterogeneous chemical loss on stratospheric aerosol for a few species. The affected species are NO2, NO3, and VOC that experience heterogeneous loss on aerosol. 

### Expected changes

The fix should increase heterogeneous losses of NO2, NO3 and VOC species in the stratosphere. The overall impact on VOC should be small as there is little VOC in the stratosphere. The additional loss of NO2 and NO3 should also increase stratospheric HNO3. I have not benchmarked the impact of this bugfix.

### Related Github Issue(s)

See issue #2204.

### CODE REVIEW

**Comment by cdholmes** [comment]
I will notify the Stratosphere WG chairs of this bug fix in case they have any comments before merging.

**Comment by yantosca** [comment]
Thanks @cdholmes, I will hold off merging until we get the all-clear.

**Review by yantosca — APPROVED** [review]
This looks good to merge.  I'll add a changelog update.  Will run integration tests in the meantime.

**Comment by yantosca** [comment]
All GEOS-Chem Classic integration tests passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

GCClassic #ac68980 GEOS-Chem submodule update: Merge PR #2198 (updated volcano emissions)
GEOS-Chem #ced31f725 PR #2205 post-merge fix: Fixed typo in fullchem_RateLawFuncs.F90
HEMCO     #f807e1a Update HEMCO version number to 3.8.0 in preparation for release

Using 24 OpenMP threads
Number of execution tests: 26

Submitted as SLURM job: 24034739
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 ```

**Comment by yantosca** [comment]
All GCHP integration tests passed
```console
==============================================================================
GCHP: Execution Test Results

GCHP      #53363f1 GEOS-Chem submodule update: Merge PR #2198 (updated volcano emissions)
GEOS-Chem #ced31f725 PR #2205 post-merge fix: Fixed typo in fullchem_RateLawFuncs.F90
HEMCO     #f807e1a Update HEMCO version number to 3.8.0 in preparation for release

Number of execution tests: 6

Submitted as SLURM job: 24066221
==============================================================================
 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Pull request merged**
