### PR TITLE
Bug fixes for Prod/Loss diagnostics for Hg simulation -- Closes #1284, #1285

### LINKED ISSUE #1284: [FEATURE REQUEST] Mercury chemistry (reduction and oxidation) diagnostics through ProdLoss for v13.4
With the new updates to the Hg simulation and Hg chemistry being added to KPP, we lost the diagnostics for net and gross Hg0 oxidation from the MercuryChem HISTORY collection (ProdHg2from*). In an earlier version of @viral211 's new chemistry mechanism, there were ProdLoss tracers that could be tracked via KPP and outputted in the ProdLoss HISTORY collection. For example, in his `Hg.eqn` file:

```
{OXIDATION BY BR}
Hg0     + Br     = HGBR + RM0pBtM1 :        GCARR2(1.46E-32,1.86,0.0);
HGBR             = Hg0 + RMBtM0 :           GCARR2(1.6E-9,1.86,-7801.0);
HGBR    + Br     = Hg0 + RMBpBtM0 :         3.9E-11;
HGBR    + NO2    = HG0 + RMBpNO2tM0 :       3.0E-12;
HGBR    + NO2    = HGBRNO2 + RMBpNO2tM2 :   GCJPLPR(4.3E-30,5.9,0.0,1.2E-10,1.90,0.0,0.6,0.0,0.0);
HGBR    + HO2    = HGBRHO2 + RMBpHO2tM2 :   GCJPLPR(4.3E-30,5.9,0.0,6.9E-11,2.40,0.0,0.6,0.0,0.0);
HGBR    + ClO    = HGBRCLO + RMBpCLOtM2 :   GCJPLPR(4.3E-30,5.9,0.0,6.9e-11,2.40,0.0,0.6,0.0,0.0);
HGBR    + BrO    = HGBRBRO + RMBpBROtM2 :   GCJPLPR(4.3E-30,5.9,0.0,6.9E-11,2.40,0.0,0.6,0.0,0.0);
HGBR    + OH     = HGBROH + RMBpOHtM2 :     GCJPLPR(4.3E-30,5.9,0.0,6.9E-11,2.40,0.0,0.6,0.0,0.0);
HGBR    + Br     = HGBR2 + RMBpBRtM2 :      3.0E-11;
HGBRO   + CH4    = HGBROH + RMBOpCH4tM2 :   GCARR(4.1E-12,0.0,-856.0);
HGBRO   + CO     = HGBR + RMBOpCOtMB :      GCARR(6.0E-11,0.0,-550.0);
HGBR    + O3     = HGBRO + RMBpO3tM2 :      3.0E-11;

```
These RM* tracers were then outputted by ProdLoss. However, this didn't seem to make it into the release version. I was wondering if this functionality could be added in a similar way to a newer GEOS-Chem version, or if there was a reason this wasn't added in? This would make it easier to benchmark simulations and evaluate how Hg chemistry changes between versions.

### PR DESCRIPTION
**Pull request by yantosca**
This is the corresponding PR to issue #1284.  It adds several minor fixes to the Hg added by @arifein, namely:

  - Fixing code to archive the prod and loss diagnostics in `GeosCore/mercury_mod.F90`
  - Added prod families PHg0, PHg2, PHg2Br, PHg2OH, PHg2Cl to `Hg.kpp` and `species_database_hg.yml`
  - Setting the units for prod and loss diagnostics to `molec cm-3 s-1` for all KPP-based simulations
  - Rebuilding the Hg mechanism with KPP 2.5.0
  - Adding the ProdLoss collection for Hg species to `run/GCClassic/HISTORY.rc.templates/HISTORY.rc.Hg`

Also note: I have updated default Hg restart file so that it now contains the PHg* species.  You can download the updated file from: http://ftp.as.harvard.edu/gcgrid/data/ExtData/GEOSCHEM_RESTARTS/v2021-12/GEOSChem.Restart.Hg.20190101_0000z.nc4.  This will let you start a simulation without having to change the time cycle flag for `SPC_` from  `EFYO` to `EY` in `HEMCO_Config.rc`.

Also tagging @viral211 @lfreese @hmhorow

### CODE REVIEW

**Review by Jourdan-He — APPROVED** [review]
Looks great!

**Comment by yantosca** [comment]
Thanks @Jourdan-He, I'll merge it into patch/14.0.1.

**Comment by yantosca** [comment]
GEOS-Chem Classic integration tests all passed except for the CO2 simulation:

```console
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 47
Execution tests failed: 1
Execution tests not yet completed: 0
```
The error in the CO2 simulation was tracked down to an incorrect entry in `HEMCO_Config.rc` for `CEDS_CO2_SHP`, and has now been fixed in #1356.

**Comment by jennyfisher** [comment]
Hi @yantosca @msulprizio - I'm trying to get the version of GCClassic with all of these Hg simulation fixes. I can't seem to figure out which version this is or what I need to pull. I've cloned 14.0.0-rc3 (I think? Whatever the current main version is). I looked for a branch called patch/14.0.1 or feature/HgFamilies but I couldn't find either of these.

Is there a quick and easy way to get a version with all the Hg updates? Thanks!

**Comment by yantosca** [comment]
Hi @jennyfisher, you can take the dev branch and I think that will have the fixes.  We are very close to releasing 14.0.0 (once the benchmarks are approved).

**Comment by arifein** [comment]
Hi @jennyfisher, regarding 1.: It worked for me to run v14 with these lines deleted from HEMCO_Config.rc, so I would also be on board with this.
For 2. + 3., the others would know better. I am not up to date with how different the Br fields are in the `Oxidants_for_Hg_sim_2016.nc4` file vs. the stored v14 GCClassic Output. If these oxidant fields are quite different, it might require a re-calibration of the Hg chemical scheme.

**Comment by yantosca** [comment]
@jennyfisher @arifein: We are awaiting the 14.0.0 10 year benchmark and would use those oxidant fields.  We might have those available before 14.1.0 ships.  I can change it to the 13.0.0 oxidant fields for now.

I can also make sure that the HEMCO_Config.rc.Hg template file is updated accordingly.

We are a bit stretched thin right now due to circumstances beyond our control.  Thanks for your patience as we sort this out.

**Comment by jennyfisher** [comment]
Thanks both. In this case, sounds like we should remove the extra lines from HEMCO_Config.rc (point 1 but leave all else as is for now. Would be interested in opinion of @viral211 on point 3.

Bob - no rush, and the 13.0.0 fields are the ones in use now so I don't think you need to change that one until the 10-year benchmark is complete. Thanks!

**Comment by viral211** [comment]
@jennyfisher @arifein  @yantosca: The Hg2 gas-particle partitioning no longer uses the AERO_* fields; the aerosol fields are included in the GLOBAL_* fields. These fields can also be removed from HEMCO_Config.rc
The Br fields in version 14.0 will be very different from version 13.0 since sea salt aerosol debromination has been turned off in the newer versions. @arifein is right that using these fields will need recalibration of the reduction rates.
Also, the mechanism expects the oxidant fields to be in molec/cm3, so we won't be able to directly point to the SpecicesConc fields in the GCClassic output. Maybe HEMCO can handle the unit conversion, but I am not sure about it. @yantosca would know.

**Comment by jennyfisher** [comment]
Thanks @viral211 

So for now we should remove the Br fields noted above and the AERO_ fields from the HEMCO_Config.rc, and leave all other fields (e.g. oxidants) pointing to the 13.0.0 versions.

@yantosca - let us know if this makes sense or if you need more clarity!

**Comment by yantosca** [comment]
This should be all done on PR #1367 now.

**Pull request merged**
