### PR TITLE
GEOS-Chem Classic netCDF satellite diagnostics (supersedes PR #1134)

### PR DESCRIPTION
**Pull request by yantosca**
This PR will bring the netCDF satellite diagnostics (prepared by @jdshutter, with updates by @yantosca) into the 14.1.0 development branch.  This PR supersedes the existing PR #1134.

Updates by @yantosca 
- Satellite diagnostics can be archived independently of the corresponding History diagnostics (i.e. the satellite diagnostic arrays do not use existing History diagnostic arrays)
- The `SatDiagn` diagnostic collection has been added to all GEOS-Chem Classic `HISTORY.rc` template files
- Updated CHANGELOG.md to the base branch to facilitate merging
- Collapsed !$OMP parallel loops for efficiency

### CODE REVIEW

**Comment by yantosca** [comment]
Closes #770

**Comment by yantosca** [comment]
GCHP integration tests all passed:
```console
==============================================================================
GCHP: Execution Test Results

Number of execution tests: 3
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gchp_fullchem_benchmark_merra2_c48...............Execute Simulation.....PASS
gchp_fullchem_standard_merra2_c24................Execute Simulation.....PASS
gchp_TransportTracers_geosfp_c24.................Execute Simulation.....PASS
 
Summary of execution test results:
------------------------------------------------------------------------------
Execution tests passed:        3
Execution tests failed:        0
Execution tests not completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
The TOMAS integration tests failed.  Looking into a fix now.
```console
gc_4x5_fullchem_TOMAS15_merra2_47L...............Execute Simulation.....FAIL
gc_4x5_fullchem_TOMAS40_merra2_47L...............Execute Simulation.....FAIL
```

**Comment by yantosca** [comment]
The failure of TOMAS integration tests was caused by a `USE Gamap_Mod` statement being removed from `GeosCore/gc_environment_mod.F90.  We have restored this statement for now.  Once the TOMAS in GCHP updates are merged into dev/14.1.0, we can remove all bpch diagnostics.

In the meantime, we have removed the `legacy_bpch` option from the `geoschem_config.yml.*` files (except for fullchem), as the  only remaining bpch diagnostics are now in the TOMAS simulation.

**Comment by yantosca** [comment]
GEOS-Chem Classic integration tests have been restarted.

**Comment by yantosca** [comment]
All GEOS-Chem Classic executable files have been built properly.  The fix in commit ad625bb1d05c14170b7cb4558063835577a582a should now cause the TOMAS integration tests to finish successfully.
```console
==============================================================================
GEOS-Chem Classic: Compilation Test Results

Using 8 OpenMP threads
Number of compilation tests: 8
==============================================================================
 
Compiliation tests:
------------------------------------------------------------------------------
GCClassic........................................Configure & Build......PASS
GCClassic with APM...............................Configure & Build......PASS
GCClassic with BPCH diagnostics..................Configure & Build......PASS
GCClassic with Hg (as a KPP mechanism)...........Configure & Build......PASS
GCClassic with Luo et al wetdep..................Configure & Build......PASS
GCClassic with RRTMG.............................Configure & Build......PASS
GCClassic with TOMAS15...........................Configure & Build......PASS
GCClassic with TOMAS40...........................Configure & Build......PASS
 
Summary of compilation test results:
------------------------------------------------------------------------------
Complilation tests passed:        8
Complilation tests failed:        0
Complilation tests not completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All compilation tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
Integration tests timed out due to latency on Cannon.  Now resubmitted.

**Comment by yantosca** [comment]
Resubmitted GC-Classic integration tests all passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

Using 24 OpenMP threads
Number of execution tests: 48
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gc_025x03125_CH4_geosfp_47L_na...................Execute Simulation.....PASS
gc_025x03125_fullchem_geosfp_47L_na..............Execute Simulation.....PASS
gc_05x0625_CH4_merra2_47L_na.....................Execute Simulation.....PASS
gc_05x0625_fullchem_merra2_47L_na................Execute Simulation.....PASS
gc_2x25_aerosol_merra2...........................Execute Simulation.....PASS
gc_2x25_CH4_merra2...............................Execute Simulation.....PASS
gc_2x25_CO2_merra2...............................Execute Simulation.....PASS
gc_2x25_fullchem_merra2..........................Execute Simulation.....PASS
gc_2x25_Hg_merra2................................Execute Simulation.....PASS
gc_2x25_metals_merra2............................Execute Simulation.....PASS
gc_2x25_POPs_BaP_merra2..........................Execute Simulation.....PASS
gc_2x25_tagCH4_merra2............................Execute Simulation.....PASS
gc_2x25_tagCO_merra2.............................Execute Simulation.....PASS
gc_2x25_tagO3_merra2.............................Execute Simulation.....PASS
gc_2x25_TransportTracers_merra2..................Execute Simulation.....PASS
gc_2x25_TransportTracers_merra2_LuoWd............Execute Simulation.....PASS
gc_4x5_aerosol_geosfp............................Execute Simulation.....PASS
gc_4x5_aerosol_merra2............................Execute Simulation.....PASS
gc_4x5_CH4_geosfp................................Execute Simulation.....PASS
gc_4x5_CH4_merra2................................Execute Simulation.....PASS
gc_4x5_fullchem_aciduptake_merra2................Execute Simulation.....PASS
gc_4x5_fullchem_APM_merra2.......................Execute Simulation.....PASS
gc_4x5_fullchem_benchmark_merra2.................Execute Simulation.....PASS
gc_4x5_fullchem_complexSOA_merra2................Execute Simulation.....PASS
gc_4x5_fullchem_complexSOA_SVPOA_merra2..........Execute Simulation.....PASS
gc_4x5_fullchem_geosfp...........................Execute Simulation.....PASS
gc_4x5_fullchem_marinePOA_merra2.................Execute Simulation.....PASS
gc_4x5_fullchem_merra2...........................Execute Simulation.....PASS
gc_4x5_fullchem_merra2_47L.......................Execute Simulation.....PASS
gc_4x5_fullchem_merra2_LuoWd.....................Execute Simulation.....PASS
gc_4x5_fullchem_RRTMG_merra2.....................Execute Simulation.....PASS
gc_4x5_fullchem_TOMAS15_merra2_47L...............Execute Simulation.....PASS
gc_4x5_fullchem_TOMAS40_merra2_47L...............Execute Simulation.....PASS
gc_4x5_Hg_geosfp.................................Execute Simulation.....PASS
gc_4x5_Hg_merra2.................................Execute Simulation.....PASS
gc_4x5_metals_merra2.............................Execute Simulation.....PASS
gc_4x5_POPs_BaP_geosfp...........................Execute Simulation.....PASS
gc_4x5_POPs_BaP_merra2...........................Execute Simulation.....PASS
gc_4x5_tagCH4_geosfp.............................Execute Simulation.....PASS
gc_4x5_tagCH4_merra2.............................Execute Simulation.....PASS
gc_4x5_tagCO_geosfp..............................Execute Simulation.....PASS
gc_4x5_tagCO_merra2..............................Execute Simulation.....PASS
gc_4x5_tagO3_geosfp..............................Execute Simulation.....PASS
gc_4x5_tagO3_merra2..............................Execute Simulation.....PASS
gc_4x5_TransportTracers_geosfp...................Execute Simulation.....PASS
gc_4x5_TransportTracers_geosfp_LuoWd.............Execute Simulation.....PASS
gc_4x5_TransportTracers_merra2...................Execute Simulation.....PASS
gc_4x5_TransportTracers_merra2_LuoWd.............Execute Simulation.....PASS
 
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 48
Execution tests failed: 0
Execution tests not yet completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Review by msulprizio — APPROVED** [review]
These updates look good to merge

**Pull request merged**
