### PR TITLE
[WIP] KPP updates, including sulfate chemistry and cleaned-up hetchem rate-law functions

### PR DESCRIPTION
**Pull request by yantosca**
This PR supersedes PR #817, which has now been closed.

The features in this update are:

  1. Cleanup of hetchem rate-law functions for KPP
    a. Also includes several modifications for computational efficiency
  2. Sulfate chemistry rate-law functions for KPP (M. Long)
  3. Sea-salt chemistry rate-law functions for KPP.
  4. HMS reactions for KPP (currently commented-out)

These KPP updates are currently in the feature/13.2.0+KPPupdates branch, which have been merged with the dev branch (at commit 80b2263714c73c8b9e6495293a129c666a0e6e25).  All conflicts have been resolved and this branch can be merged.

There is a corresponding GCClassic tracking branch "feature/13.2.0+KPPupdates, which was at commit 06979b583d192d827503eb7081878a0dd37322de at the time of this merge.

### CODE REVIEW

**Comment by yantosca** [comment]
Integration tests and benchmarks are currently pending.  I will report on those as the results are available.

**Comment by yantosca** [comment]
Also note, this branch as-is will probably break the aerosol-only and aciduptake simulations.  Fixes for these will be pushed to this PR shortly.

**Comment by tsherwen** [comment]
Hello @yantosca, 

Great to see all these changes coming through - thanks for all your work on this!

I was wondering if you were able to give an idea of your timescale for pushing the aciduptake simulation changes?

We have been working at York with simulations that extend the nitrate photolysis code to include nitrate on dust aerosols. For reasons of various commits/updates, I working on whether it would be best to do some new runs to test some ideas in v10 or in v13.3 bleeding-edge code. We want to do these runs on a timescale of a fortnight, so which we use would depend on whether the aciduptake simulation updates were pushed into v13.3 / bleeding edge code. 

Cheers, 

Tomas

**Comment by yantosca** [comment]
Thanks for writing @tsherwen.  I was away for a couple of days, sorry for the late reply.

I have my hands tied with some other responsibilities, but I need to merge the aciduptake code up to 13.2.0.  I hope to be working on it this week but it may not be done by the timeline you have specified.  Also, we have had some computer downtime for maintenance (that went longer than planned) so it has been difficult to get jobs scheduled lately.

NOTE: The dust acid uptake code has been ported into KPP by Mike Long in the `feature/msl/dustaciduptake` branch, but that has yet to be merged with the latest 13.2.0 code.   You could take a look at that to start.

**Comment by yantosca** [comment]
This PR has been superseded by #897.  We had to split off the sulfur chemistry from the hetchem rate-law function modifications because the sulfur chemistry needed more validation.

**Pull request closed without merging**
