### PR TITLE
[PULL REQUEST] SIV chemistry updates from Mike Long merged atop PR #1161 -- Supersedes #1166

### PR DESCRIPTION
**Pull request by yantosca**
## Overview

This PR now supersedes #1166.  It is the S(IV) chemistry updates from Mike Long (@msl3v) merged to the "dev" branch atop PR #1161.  Also contains some minor updates by Bob Yantosca (@yantosca).

## Instructions

As this PR will make changes to the KPP chemistry mechanism, PR #1169 should be merged into dev first.

### CODE REVIEW

**Comment by yantosca** [comment]
Integration tests in progress.

**Comment by yantosca** [comment]
All GEOS-Chem Classic integration tests passed
```console
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 48
Execution tests failed: 0
Execution tests not yet completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
The GCHP benchmark integration test failed
```console
==============================================================================
GCHP: Execution Test Results

Number of execution tests: 3
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gchp_fullchem_benchmark_merra2_c48...............Execute Simulation.....FAIL
gchp_fullchem_standard_merra2_c24................Execute Simulation.....PASS
gchp_TransportTracers_geosfp_c24.................Execute Simulation.....PASS
 
Summary of execution test results:
------------------------------------------------------------------------------
Execution tests passed:        2
Execution tests failed:        1
Execution tests not completed: 0
```
The error message was:
==============================================================================
GCHP: Execution Test Results

Number of execution tests: 3
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gchp_fullchem_benchmark_merra2_c48...............Execute Simulation.....FAIL
gchp_fullchem_standard_merra2_c24................Execute Simulation.....PASS
gchp_TransportTracers_geosfp_c24.................Execute Simulation.....PASS
 
Summary of execution test results:
------------------------------------------------------------------------------
Execution tests passed:        2
Execution tests failed:        1
Execution tests not completed: 0
```
The error was:
```console
GEOS-Chem ERROR [0018]: The mapData%slot2Id array corresponding to collection "SpeciesConc" contains missing values! This can indicate that this collection is either undefined or turned off.  Please check the HISTORY.rc configuration file in your run directory.
 --> LOCATION:  -> at Get_Mapping (in module Headers/state_diag_mod.F90)
 
GEOS-Chem ERROR [0018]: Error encountered in "Get_Mapping": SpeciesConc
 --> LOCATION:  -> at Get_MapData_and_NumSlots (in module Headers/state_diag_mod.F90)
 
GEOS-Chem ERROR [0018]: Error encountered in "Get_MapData_and_NumSlots"!
 --> LOCATION:  -> at Init_and_Register_R8_4D (in module Headers/state_diag_mod.F90)
 
GEOS-Chem ERROR [0018]: Error encountered in "Init_and_Register", diagID =SpeciesConc
 --> LOCATION:  -> at Init_State_Diag (in Headers/state_diag_mod.F90)
 
GEOS-Chem ERROR [0018]: Error encountered within call to "Init_State_Diag"!
 --> LOCATION:  -> at GC_Init_StateObj (in GeosCore/gc_environment_mod.F90)
===> Run ended at Mon Mar 14 16:58:20 EDT 2022
```

**Comment by yantosca** [comment]
I think this is due to HSO3m and SO3m not being advected species anymore.  Will push a fix and retest.

**Comment by yantosca** [comment]
Removing HSO3m and SO3mm from the SpeciesConc collection in the GCHP HISTORY.rc.fullchem template file solves this issue.  GCHP integration tests all pass:

```console
==============================================================================
GCHP: Execution Test Results

Number of execution tests: 3
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gchp_fullchem_benchmark_merra2_c48...............Execute Simulation.....PASS
gchp_fullchem_standard_merra2_c24................Execute Simulation.....PASS
gchp_TransportTracers_geosfp_c24.................Execute Simulation.....PASS
 
Summary of execution test results:
------------------------------------------------------------------------------
Execution tests passed:        3
Execution tests failed:        0
Execution tests not completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Review by msulprizio — APPROVED** [review]
These modifications look good to merge after PR #1161 is merged.

**Comment by msulprizio** [comment]
Internal benchmark plots and tables for this update can currently be found at http://ftp.as.harvard.edu/gcgrid/geos-chem/validation/InternalBenchmarks/13.4.0/GCC_13.4.0-alpha.21. 

The overall impact on model output appears small. For example, global mass differences for select species are:

```
###################################################################################
### Global mass (Gg) at end of simulation (Trop only)                           ###
### Ref = GCC_13.4.0-alpha.20; Dev = GCC_13.4.0-alpha.21                        ###
###################################################################################
                                    Ref                 Dev     Dev - Ref    % diff
HBr                :           7.176643            7.253128      0.076485     1.066
HCl                :         297.524170          297.648682      0.124512     0.042
HOBr               :           7.022534            7.188446      0.165912     2.363
HOCl               :           5.749225            5.807306      0.058081     1.010
SO2                :         406.362946          406.138885     -0.224060    -0.055
SO3mm              :           0.697430                 nan           nan       nan
SO4                :        1644.606079         1644.084473     -0.521606    -0.032
SO4s               :           0.420955            0.067558     -0.353397   -83.951
```

The impact on global mean OH is:

```
###############################################################################
### OH Metrics
### Ref = GCC_13.4.0-alpha.20; Dev = GCC_13.4.0-alpha.21
###############################################################################

------------------------------------------------------------
Global mass-weighted OH concentration [10^5 molec cm^-3]
------------------------------------------------------------
Ref      : 10.69238032867
Dev      : 10.69127396158
Abs diff : -0.00110636709
%   diff : -0.010347
```

**Pull request merged**
