### PR TITLE
GEOS-Chem with APM

### PR DESCRIPTION
**Pull request by ganluoasrc**
APM has been incorporated with GEOS-Chem.

### CODE REVIEW

**Comment by yantosca** [comment]
Thanks Gan!  We will take a look at this soon

**Comment by ganluoasrc** [comment]
You are welcome. Please let me know if you any questions.

Best wishes

Gan
________________________________

**Comment by yantosca** [comment]
Hi Gan --

I downloaded your pull request code into a branch off of the GEOS-Chem repository.  I made a few modifications on top of your master:

(1) I put all of the APM routines (except apm_driv_mod.F90, which needs to stay in GeosCore) in the APM folder.  I updated Makefile_header.mk and the other Makefiles accordingly.  Our policy is to put optional, third-party code into separate folders, so that it is kept separate as much as possible from the "Core" GC routines. 

(2) Gfortran 8.2 wouldn't compile properly because some of the #ifdefs were "#if defined ( APM )", with a space between the "d" and the "(".  I changed those to "#if defined( APM )", and then it was able to compile properly.

(3) I noted a few locations in the code that might have to be changed at a later time.  For example, the wetdep code uses a use-associated array from another module:

    #if defined( APM )
          ! NOTE: This should really go into State_CHM!! (bmy, 6/17/19)
          REAL(fp), PUBLIC, ALLOCATABLE, TARGET :: PSO4_SO2APM2(:,:,:)
    #endif

For GEOS-Chem "Classic" this is OK, but when we run in the MPI environment (e.g. WRF-GC), then this can be problematic.  That array should really be in a State variable like State_Chm or similar.  We can cross that bridge later.

There might be also another problem in apm_driv_mod.F90 -- In 12.4.0 and higher, we will have FlexGrid, which will let users pick custom grids.  We are going to retire the GRID2x25 and GRID4x5 #ifdefs.  

    !NOTE: FlexGrid will probably break this (bmy, 6/17/19)
    #if   defined( GRID2x25 )
          REAL,SAVE                :: SEABIRDEM(144,91,2)
          REAL                     :: BIRDNH3(144,91)
    #else
          REAL,SAVE                :: SEABIRDEM(72,46,2)
          REAL                     :: BIRDNH3(72,46)
    #endif

So instead of 144,91 and 72,46 we should use the FlexGrid lon and lat dimensions (which will be State_Grid%NX and State_Grid%NY).  I can fix that after I merge up to 12.4.0.

(4) I will need your APM run directory, as well as any files that need to go into the shared data directories.  APM is trying to read data from a file that I don't have, and I get this error:

    forrtl: severe (29): file not found, unit 199, file /local/ryantosca/GC/rundirs/APM/geosfp_4x5_standard/apm_tmp.dat
    Image              PC                Routine            Line        Source             
    libifcoremt.so.5   00002B2D6E8D198F  for__io_return        Unknown  Unknown
    libifcoremt.so.5   00002B2D6E8F5424  for_open              Unknown  Unknown
    geos.mp            00000000008DA02A  apm_init_mod_mp_a         586  apm_init_mod.F
    geos.mp            0000000000562D18  MAIN__                    689  main.F
    geos.mp            000000000040393E  Unknown               Unknown  Unknown
    libc-2.17.so       00002B2D70D7C3D5  __libc_start_main     Unknown  Unknown
    geos.mp            0000000000403849  Unknown               Unknown  Unknown

Once I have a good run directory I can do unit tests and diff tests, which we will need to certify the version.

But other than these minor things, it was pretty easy to get your APM code going.  Thanks for the good work!  

Best,
Bob Y.

**Comment by yantosca** [comment]
I am finding some issues trying to compile APM with GEOS-Chem with gfortran

(1) Need to comment out these lines at the end of routine saltemit in apm_init_mod.F:

      !FLUSH(28)
      !FLUSH(29)

(2) Need to comment out these lines at the end of routine  sulf_emit in apm_init_mod.F:

      !FLUSH(21)
      !FLUSH(22)
      !FLUSH(23)
      !FLUSH(24)

(3) Am getting a division by zero error at this line in apm_opti_mod.F:

          do IDS = 1, MDS
            READ(88,110)IDS1,DSa   !um
            IF(IDS1.GT.0.) THEN
             IF(ITABLE.EQ.1) DSb=DS1(IDS)
             IF(ITABLE.EQ.2) DSb=DS2(IDS)
             IF(ITABLE.EQ.3) DSb=DS3(IDS)
             YTEMP = abs(DSa-DSb)/DSa  !double check    <--- DSa is zero 
             IF(IDS.GT.1) THEN
             IF(YTEMP.GT.0.01) THEN
              WRITE(6,*)"STOP: NEED to check DS",DSa,DSb
             ENDIF
             ENDIF
            ENDIF
          enddo

which seems to be choking at this line of  OPTAB20120823/OPTABLE_BC.txt

     ***Dshell (um)***
      1  0.000E+00

Because DSa is zero, the division blows up.  Should we just set YTEMP to zero in such a case?

**Comment by yantosca** [comment]
It looks like YTEMP isn't used for much else than the error trap, so I added a quick fix that will allow me to continue testing:

          do IDS = 1, MDS
            READ(88,110)IDS1,DSa   !um
            print*, '### apm read: ', ids1, dsa
            call flush(6)
            IF(IDS1.GT.0.) THEN
             IF(ITABLE.EQ.1) DSb=DS1(IDS)
             IF(ITABLE.EQ.2) DSb=DS2(IDS)
             IF(ITABLE.EQ.3) DSb=DS3(IDS)
    !----------------------------------------------------------
    ! BMY KLUDGE TO AVOID DIV-BY-ZERO
    !         YTEMP = abs(DSa-DSb)/DSa  !double check
             IF ( DSa > 0.0 ) THEN
              YTEMP = abs(DSa-DSb)/DSa  !double check
             ELSE
              YTEMP = 0.0
             ENDIF
    !----------------------------------------------------------
             IF(IDS.GT.1) THEN
             IF(YTEMP.GT.0.01) THEN
              WRITE(6,*)"STOP: NEED to check DS",DSa,DSb
             ENDIF
             ENDIF
            ENDIF
          enddo

**Comment by ganluoasrc** [comment]
DSa is diameter of shell size for black carbon. For bin1, it is 0.
So we need to modify the code as:
abs(DSa-DSb)/max(1.d-30,DSa)

**Comment by yantosca** [comment]
I am going to close this pull request, as we have now merged this code up to 12.6.0.  Thanks Gan!

**Comment by ganluoasrc** [comment]
Hi Bob,


You are welcome!


Best


Gan

________________________________

**Pull request closed without merging**
