### PR TITLE
[PULL REQUEST] Updated HEMCO_Config.rc and ExtData.rc templates for AEIC2019 emissions

### PR DESCRIPTION
**Pull request by yantosca**
This PR implements the AEIC2019 aircraft emissions, as described by @seastham [in this technical note](https://github.com/geoschem/geos-chem/files/8307152/AEIC_2019_technical_note.pdf).

We have currently made the updates to the various `HEMCO_Config.rc` and `ExtData.rc` template files, but we still need to verify that the annual totals are as expected.  We will run HEMCO standalone simulations and will post the results here.  Until then, please consider this as a draft PR.

### CODE REVIEW

**Comment by yantosca** [comment]
Question for @msulprizio, @sdeastham: Should we also consider an option to  using monthly-mean AEIC2019 emissions?  Because this data is daily and at 0.5 x 0.625 degrees resolution, I think reading/regridding will add overhead to the simulation time.

HEMCO standalone results pending.

**Comment by djxjacob** [comment]
Yes, good point. I think that we should use the monthly mean emissions as default in the standard model.  Daniel

**Comment by yantosca** [comment]
@djxjacob: Very well, we can take the monthly mean outputs from the HEMCO standalone runs and use those.  I will work on that next week.

**Comment by yantosca** [comment]
> @djxjacob: Very well, we can take the monthly mean outputs from the HEMCO standalone runs and use those. I will work on that next week.

On second thought, it's better to take the monthly mean of the raw data files with the CDO operators.  That will suffice and it's fast.

**Comment by yantosca** [comment]
## File preparation

Original daily AEIC 2019 data files were produced by Seb Eastham (@sdeastham).  File post-processing was done by Bob Yantosca (@yantosca):

  1. Ran [nc_chunk.pl](https://github.com/geoschem/geos-chem/blob/dev/NcdfUtil/perl/nc_chunk.pl) on the AEIC 2019 daily raw data files to chunk and compress them with netCDF deflation level 1.  This reduced individual file sizes from about 39 MB to about 23 MB.
  2. Ran script [add_time_unlimited.sh](http://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/AEIC2019/v2022-03/2019/scripts/add_time_unlimited.sh) on each of the daily AEIC 2019 data files to convert the `time` dimension from fixed to `UNLIMITED`.  This step is needed for creating the monthly mean data files.
  3. Grouped the AEIC 2019 daily data files into monthly directories (e.g. `01/, 02/ .. 12/`).  This makes file management easier.
  4. Ran script [aeic_daily_to_monmean.sh](http://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/AEIC2019/v2022-03/2019-monmean/scripts/aeic_daily_to_monmean.sh) to create monthly mean data files from the daily data files.
  5. Ran script  [nc_chunk.pl](https://github.com/geoschem/geos-chem/blob/dev/NcdfUtil/perl/nc_chunk.pl) on the monthly-mean data files to chunk and compress them with netCDF deflation level 1.  This reduces the size of the monthly-mean data files from 550 MB to about 39MB each.

## Validation

Performed the following runs with the HEMCO standalone.  The output of each run was archived to the GEOS-Chem 4x5 grid.

  1. **Reference simulation**": Used AEIC 2005 monthly mean aircraft emissions at 1 x 1 resolution.
  2. **AEIC 2019 daily simulation**: Used AEIC 2019 daily aircraft emissions at 0.5 x 0.625 resolution.
  3. **AEIC 2019 monthly mean simulation**: Used AEIC 2019 monthly-mean aircraft emissions at 0.5 x 0.625  resolution.

The outputs are shown below:

### AEIC 2019 daily vs. AEIC 2005 monthly mean (Run 2 vs. Run 1)
```console
###################################################################################
### Emissions totals [Tg] for AEIC 2005 vs. AEIC 2019 daily emissions           ###
###                                                                             ###
### Ref = AEIC 2005; Dev = AEIC_2019; Output grid = 4x5                         ###
###################################################################################
                           Ref           Dev     Dev - Ref    % diff
ACET Aircraft  :      0.010319      0.006891     -0.003428   -33.219
ALD2 Aircraft  :      0.119344      0.079699     -0.039645   -33.219
ALK4 Aircraft  :      0.511878      0.398869     -0.113009   -22.077
BCPI Aircraft  :      0.064991      0.216570      0.151579   233.229
C2H6 Aircraft  :      0.014568      0.009729     -0.004839   -33.219
C3H8 Aircraft  :      0.002182      0.001457     -0.000725   -33.219
CH2O Aircraft  :      0.343858      0.229632     -0.114226   -33.219
CO Aircraft    :      8.988858     15.497085      6.508227    72.403
HNO2 Aircraft  :           nan      1.368607           nan       nan
MACR Aircraft  :      0.011985      0.100050      0.088065   734.763
NO Aircraft    :     21.041348     30.235683      9.194334    43.697
NO2 Aircraft   :           nan      6.355527           nan       nan
OCPI Aircraft  :      0.064991      0.091015      0.026023    40.041
PRPE Aircraft  :      0.452629      0.332172     -0.120457   -26.613
RCHO Aircraft  :      0.402163      0.068601     -0.333562   -82.942
SO2 Aircraft   :      2.547664      3.639599      1.091934    42.860
SO4 Aircraft   :      0.077990      0.111416      0.033427    42.860
SOAP Aircraft  :      0.620231      1.069299      0.449068    72.403
```
Plots: [AEIC_2005_vs_2019.daily.4x5.pdf](https://github.com/geoschem/geos-chem/files/8319019/AEIC_2005_vs_2019.daily.4x5.pdf)

### AEIC 2019 monthly mean vs. AEIC 2005 monthly mean (Run 3 vs. Run 1)
```console
###################################################################################
### Emissions totals [Tg] for AEIC 2005 vs. AEIC 2019 monthly mean emissions    ###
###                                                                             ###
### Ref = AEIC 2005; Dev = AEIC_2019; Output grid = 4x5                         ###
###################################################################################
                          Ref            Dev     Dev - Ref    % diff
ACET Aircraft  :     0.010319       0.006891     -0.003428   -33.219
ALD2 Aircraft  :     0.119344       0.079699     -0.039645   -33.219
ALK4 Aircraft  :     0.511878       0.398869     -0.113009   -22.077
BCPI Aircraft  :     0.064991       0.216570      0.151579   233.229
C2H6 Aircraft  :     0.014568       0.009729     -0.004839   -33.219
C3H8 Aircraft  :     0.002182       0.001457     -0.000725   -33.219
CH2O Aircraft  :     0.343858       0.229632     -0.114226   -33.219
CO Aircraft    :     8.988858      15.497085      6.508227    72.403
HNO2 Aircraft  :          nan       1.368607           nan       nan
MACR Aircraft  :     0.011985       0.100050      0.088064   734.763
NO Aircraft    :    21.041348      30.235684      9.194336    43.697
NO2 Aircraft   :          nan       6.355527           nan       nan
OCPI Aircraft  :     0.064991       0.091015      0.026023    40.041
PRPE Aircraft  :     0.452629       0.332172     -0.120457   -26.613
RCHO Aircraft  :     0.402163       0.068601     -0.333562   -82.942
SO2 Aircraft   :     2.547664       3.639599      1.091934    42.860
SO4 Aircraft   :     0.077990       0.111416      0.033427    42.860
SOAP Aircraft  :     0.620231       1.069299      0.449068    72.403
```
Plots: [AEIC_2005_vs_2019.monmean.4x5.pdf](https://github.com/geoschem/geos-chem/files/8319031/AEIC_2005_vs_2019.monmean.4x5.pdf)

### Results
As expected, we get the same totals when using the AEIC daily or monthly-mean emissions.  The daily emissions can be used for research purposes but they will incur additional computational overhead due to additional I/O and regridding.  For most GEOS-Chem simulations, the AEIC monthly-mean emissons should suffice.

**Comment by sdeastham** [comment]
Thanks Bob! Out of interest, what was the difference in computational cost?

**Comment by yantosca** [comment]
> Thanks Bob! Out of interest, what was the difference in computational cost? [EDIT: I know this won't really scale well given it was HEMCO standalone rather than GC, but am curious nonetheless if the data is available]

I didn't do a strict timing but I think the daily standalone simulation took on the order of an hour or more whereas the monthly-mean simulation took on the order of about 10 minutes.  The daily data I/O is definitely a killer.

**Comment by sdeastham** [comment]
Oh, wow! That's a huge difference. I'll be very curious to see what happens in GCHP - my hope would be that MAPL can help but I have no idea how realistic that hope is!

**Comment by sdeastham** [comment]
Absolutely! And as long as users still have the option to use the finer-resolution data that's no problem. If someone was interested in aviation impacts (especially near-airport) they may well want the finer resolution data - both spatial and temporal - but for the average user I fully agree they'd rather have the 6x reduction in read time.

**Comment by yantosca** [comment]
@sdeastham, yes we will keep both daily and monthly emissions.  There are comments in the HEMCO_Config.rc file explaining what the recommended settings are.

**Comment by sdeastham** [comment]
Hi @yantosca - the new AEIC2019 data are simply on the lowest 36 layers of the GEOS 72 layer grid. These are all identical between the 47 and 72 layer grids, so no regridding should be needed.

**Comment by sdeastham** [comment]
Hi @yantosca - I've run a GCHP simulation with no problem. I'd recommend against padding (or regridding) - padding would add unnecessary file size, and regridding shouldn't be necessary. What do we do with (eg) NEI files where the emissions only go up a few levels?

**Comment by yantosca** [comment]
Thanks @sdeastham.  I've found the reason for the error, and a quick fix is described here: https://github.com/geoschem/HEMCO/issues/138.  I'll implement this in HEMCO.

**Comment by yantosca** [comment]
@sdeastham, I also think that this issue only shows up in GEOS-Chem Classic, which is why you might not have seen it.  In GCHP we rely on MAPL for the data input & regridding.  Thanks again!  Benchmarking is now underway (tagged 13.4.0-alpha.22).

**Comment by yantosca** [comment]
The fix described in https://github.com/geoschem/HEMCO/issues/138 has been added to HEMCO and integration tests for AEIC aircraft emissions have been re-submitted.

**Comment by yantosca** [comment]
GCHP integration tests (rerun) failed due to typos in the `HEMCO_Config.rc.fullchem` template file.  This has now been fixed in commit 001fd105f543ba897a92bce704713163b28d4b5b.  Will submit the GCHP integration tests again.

**Comment by yantosca** [comment]
GCHP integration tests failed again due to typos in ExtData.rc.  This has been fixed in commit b950fec3ef988e80d7daeff5d8be2a62f8be5d90.  GCHP integration tests have been restarted again.

**Comment by yantosca** [comment]
GCHP integration tests failed again due to incorrect filenames in ExtData.rc.  Now fixed with commit ff13092b86069e81ffda11c75d97e009101988f9 and restarted GCHP integration tests.

**Comment by yantosca** [comment]
All GEOS-Chem Classic integration tests passed:
```console
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 48
Execution tests failed: 0
Execution tests not yet completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
After several attempts, all GCHP integration tests also now pass:
```console
==============================================================================
GCHP: Execution Test Results

Number of execution tests: 3
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gchp_fullchem_benchmark_merra2_c48...............Execute Simulation.....PASS
gchp_fullchem_standard_merra2_c24................Execute Simulation.....PASS
gchp_TransportTracers_geosfp_c24.................Execute Simulation.....PASS
 
Summary of execution test results:
------------------------------------------------------------------------------
Execution tests passed:        3
Execution tests failed:        0
Execution tests not completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
we are OK to move to the alpha benchmark stage.

**Pull request merged**
